## Install Required Libraries

In [ ]:
%%capture
import os
if "COLAB_" not in "".join(os.environ.keys()):
    !pip install unsloth
else:
    # Do this only in Colab notebooks! Otherwise use pip install unsloth
    !pip install --no-deps bitsandbytes accelerate xformers==0.0.29.post3 peft trl triton cut_cross_entropy unsloth_zoo
    !pip install sentencepiece protobuf "datasets>=3.4.1" huggingface_hub hf_transfer
    !pip install --no-deps unsloth

In [ ]:
!pip install -q datasets transformers evaluate sentence-transformers openai pandas numpy tqdm python-dotenv  google-generativeai requests tqdm -q sacrebleu rouge_score bert_score

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 11.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 6.6 MB/s eta 0:00:00
  Building wheel for rouge_score (setup.py) ... done

In [ ]:
!pip install anthropic

Collecting anthropic
  Downloading anthropic-0.76.0-py3-none-any.whl.metadata (28 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from anthropic) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from anthropic) (1.9.0)
Requirement already satisfied: docstring-parser<1,>=0.15 in /usr/local/lib/python3.12/dist-packages (from anthropic) (0.17.0)
Requirement already satisfied: httpx<1,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from anthropic) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from anthropic) (0.12.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from anthropic) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from anthropic) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.10 in /usr/local/lib/python3.12/dist-packages (from anthropic) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->anthropic) (3.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->anthropic) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->anthropic) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.25.0->anthropic) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->anthropic) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->anthropic) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->anthropic) (0.4.2)
Downloading anthropic-0.76.0-py3-none-any.whl (390 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 390.3/390.3 kB 8.5 MB/s eta 0:00:00
Installing collected packages: anthropic
Successfully installed anthropic-0.76.0

In [ ]:
!pip install bart-score

ERROR: Could not find a version that satisfies the requirement bart-score (from versions: none)
ERROR: No matching distribution found for bart-score

## Import Required Libraries

In [ ]:
import os
import csv
import json
import pandas as pd
import torch
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer
import evaluate
from sentence_transformers import SentenceTransformer, util
from peft import PeftModel

# Other Packages
import pandas as pd
import numpy as np
import os
from huggingface_hub import login
import getpass
from google.colab import userdata
from tqdm.auto import tqdm
import os
import csv

## Display Settings

In [1]:
pd.set_option('display.max_rows', None)        # Show all rows
pd.set_option('display.max_columns', None)     # Show all columns
pd.set_option('display.width', None)           # Don't wrap to next line
pd.set_option('display.max_colwidth', None)    # Show full column content

## Hugginface Login

In [ ]:
HF_TOKEN = userdata.get("HF_TOKEN")
if HF_TOKEN:
    login(token=HF_TOKEN)
    print("Logged in using environment variable")
else:
    print("No HF_TOKEN found")

Logged in using environment variable

## OpenAI Login

In [ ]:
from openai import OpenAI
import os

# OpenAI API key
api_key = userdata.get('OPENAI_API_KEY')

os.environ["OPENAI_API_KEY"] = api_key

client = OpenAI(api_key=api_key)

## Mount Google Drive

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

## Load the test split and choose sample size

In [ ]:
dataset_name = "Lakshan2003/customer-support-client-agent-conversations"
split_name   = "test"
num_samples  = None  # Set to an integer to evaluate a subset (in order) or None for all

test_dataset = load_dataset(dataset_name, split=split_name)
if num_samples is not None:
    test_dataset = test_dataset.select(range(num_samples))  # Keep original order

print(f"Loaded {len(test_dataset)} test samples")

README.md:   0%|          | 0.00/809 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/148M [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/42.4M [00:00<?, ?B/s]

data/validation-00000-of-00001.parquet:   0%|          | 0.00/21.1M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/128335 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/36669 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/18333 [00:00<?, ? examples/s]

Loaded 36669 test samples

### Select and Load a LoRA‑finetuned model

In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel
import torch

lora_adapter = "Lakshan2003/Llama3.2-1B-instruct-customerservice"

# Load the base model
base_model_name = "unsloth/Llama-3.2-1B-Instruct-bnb-4bit"
base_model = AutoModelForCausalLM.from_pretrained(
    base_model_name,
    torch_dtype=torch.float16,
    device_map="auto",
    trust_remote_code=True
)

tokenizer = AutoTokenizer.from_pretrained(base_model_name)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# Load LoRA adapter on top
model = PeftModel.from_pretrained(
    base_model,
    lora_adapter
)

# Merge the adapter
model = model.merge_and_unload()

# Set to eval mode
model.eval()

LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(128256, 2048, padding_idx=128004)
    (layers): ModuleList(
      (0-15): 16 x LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear4bit(in_features=2048, out_features=2048, bias=False)
          (k_proj): Linear4bit(in_features=2048, out_features=512, bias=False)
          (v_proj): Linear4bit(in_features=2048, out_features=512, bias=False)
          (o_proj): Linear4bit(in_features=2048, out_features=2048, bias=False)
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear4bit(in_features=2048, out_features=8192, bias=False)
          (up_proj): Linear4bit(in_features=2048, out_features=8192, bias=False)
          (down_proj): Linear4bit(in_features=8192, out_features=2048, bias=False)
          (act_fn): SiLUActivation()
        )
        (input_layernorm): LlamaRMSNorm((2048,), eps=1e-05)
        (post_attention_layernorm): LlamaRMSNorm((2048,), eps=1e-05)
      )
    )
    (norm): LlamaRMSNorm((2048,), eps=1e-05)
    (rotary_emb): LlamaRotaryEmbedding()
  )
  (lm_head): Linear(in_features=2048, out_features=128256, bias=False)
)

### Prompt Templat for the Model

In [ ]:
ft_prompt = """<|begin_of_text|><|start_header_id|>system<|end_header_id|>
{instruction}<|eot_id|>

<|start_header_id|>user<|end_header_id|>

Conversation History:
{history}

Client Question:
{client_question}

<|eot_id|>

<|start_header_id|>assistant<|end_header_id|>"""

# End of sentence special token
EOS_TOKEN = tokenizer.eos_token

### Generation Settings

In [ ]:
# Sampling parameters (top_p, top_k, etc.)
generation_config = {
    "max_new_tokens": 128,
    "do_sample": True,
    "temperature": 0.7,
    "top_p": 0.9,    # nucleus sampling
    "top_k": 50,
}

### Build Chat template function

In [ ]:
def build_prompt(example):
    # accept dict rows or raw strings
    if isinstance(example, str):
        example = {"client_question": example}
    elif not isinstance(example, dict):
        example = {"client_question": str(example)}

    return ft_prompt.format(
        instruction=example.get("instruction", ""),
        history=example.get("history_summary", ""),
        client_question=example.get("client_question", "")
    )

#### Output file

In [ ]:
lora_adapter = "Llama3.2-1B-instruct-customerservice"
results_dir  = f"/content/drive/MyDrive/fyp-2025/Datasets/TestData/{lora_adapter}"
results_path = os.path.join(results_dir, f"results_lora_customerservice{lora_adapter}.csv")
os.makedirs(results_dir, exist_ok=True)

In [ ]:
model.eval()
torch.set_grad_enabled(False)
if tokenizer.pad_token_id is None:
    tokenizer.pad_token_id = tokenizer.eos_token_id
tokenizer.padding_side = "left"

In [ ]:
SAVE_COLS = [
    "conversation_id",
    "instruction",
    "history",
    "history_summary",
    "client_question",
    "ground_truth",        # from refined_agent_answer
    "generated_answer",
]

In [ ]:
def as_str(x):
    try:
        return str(x)
    except Exception:
        return ""

In [ ]:
# resume Logic
processed_ids, header_written = set(), False
if os.path.exists(results_path):
    try:
        prev = pd.read_csv(results_path)
        if "conversation_id" in prev.columns:
            processed_ids = set(prev["conversation_id"].astype(str))
        header_written = True
        print(f"Resuming from {len(processed_ids)} saved rows.")
    except Exception as e:
        print(f"CSV unreadable, starting fresh: {e}")

In [ ]:
torch.set_grad_enabled(False)

torch.autograd.grad_mode.set_grad_enabled(mode=False)

In [ ]:
to_run = []
for ex in test_dataset:  # expects dict-like rows
    cid = as_str(ex.get("conversation_id", ""))
    if cid and cid in processed_ids:
        continue
    to_run.append(ex)
print(f"Pending: {len(to_run)}")

Pending: 36669

In [ ]:
if getattr(tokenizer, "pad_token", None) is None:
    tokenizer.pad_token = tokenizer.eos_token

eos_ids = [tokenizer.eos_token_id]
end = "<|end|>"
if hasattr(tokenizer, "get_vocab") and end in tokenizer.get_vocab():
    end_id = tokenizer.convert_tokens_to_ids(end)
    if end_id != tokenizer.eos_token_id:
        eos_ids = [tokenizer.eos_token_id, end_id]

In [ ]:
gen_batch_size = 64
pbar = tqdm(total=len(to_run), desc="Generating", unit="rec")

model.eval()
torch.set_grad_enabled(False)

for start in range(0, len(to_run), gen_batch_size):
    batch = to_run[start : start + gen_batch_size]

    prompts, metas = [], []
    for ex in batch:
        instruction     = ex.get("instruction", "")
        history_turns   = ex.get("conversation_history", "")
        history         = ex.get("history_summary", "")
        client_question = ex.get("client_question", "")
        ground_truth    = ex.get("refined_agent_answer", "")

        input_prompt = ft_prompt.format(
            instruction=instruction,
            history=history,
            client_question=client_question
        )
        prompts.append(input_prompt)
        metas.append({
            "conversation_id": str(ex.get("conversation_id", "")),
            "instruction": instruction,
            "history": history_turns,
            "history_summary": history,
            "client_question": client_question,
            "ground_truth": ground_truth,
        })

    enc = tokenizer(
        prompts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=tokenizer.model_max_length,
    ).to(model.device)

    with torch.no_grad():
        out = model.generate(
            **enc,
            **generation_config,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=eos_ids,
            return_dict_in_generate=True,
            use_cache=True,
        )

    seqs = out.sequences
    start_idx = enc.input_ids.shape[1]  # robust slice point for the whole batch
    gen_texts = [
        tokenizer.decode(seqs[i, start_idx:], skip_special_tokens=True).strip()
        for i in range(seqs.size(0))
    ]

    out_df = pd.DataFrame(
        [{**m, "generated_answer": g} for m, g in zip(metas, gen_texts)],
        columns=SAVE_COLS
    )
    out_df.to_csv(
        results_path,
        mode="a",
        header=not os.path.exists(results_path),
        index=False,
        quoting=csv.QUOTE_MINIMAL,
    )

    pbar.update(len(batch))

pbar.close()

Generating:   0%|          | 0/36669 [00:00<?, ?rec/s]

In [ ]:
import pandas as pd
from datasets import Dataset

# Load CSV
df = pd.read_csv(results_path)

# Convert to Dataset
dataset = Dataset.from_pandas(df)

# Define repo name with model + use case
repo_id = "Lakshan2003/Llama3.2-1B-instruct-customerservice-evaldata"

# Push to Hub
dataset.push_to_hub(repo_id, private=True)

# Lexical Overlap Scores Calculation

In [ ]:
import pandas as pd
from datasets import Dataset


df = pd.read_csv(results_path)
preds = df["generated_answer"].tolist()
refs  = df["ground_truth"].tolist()

## Bleu Score Calculation

In [ ]:
# Lexical overlap metrics
bleu   = evaluate.load("bleu").compute(predictions=preds, references=[[r] for r in refs])["bleu"]

bleu

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading extra modules:   0%|          | 0.00/1.55k [00:00<?, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

0.07652430775214872

## Google Bleu Score Calculation

In [ ]:
gbleu  = evaluate.load("google_bleu").compute(predictions=preds, references=refs)["google_bleu"]

gbleu

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

0.11586232817789012

## Meteor Score Calculation

In [ ]:
meteor = evaluate.load("meteor").compute(predictions=preds, references=refs)["meteor"]

Downloading builder script: 0.00B [00:00, ?B/s]

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

In [ ]:
print(meteor)

0.30315228875232403

## Rougue Score Calculation

In [ ]:
rouge  = evaluate.load("rouge").compute(predictions=preds, references=refs)

rouge

Downloading builder script: 0.00B [00:00, ?B/s]

{'rouge1': np.float64(0.3298252278602901),
 'rouge2': np.float64(0.10532743887878304),
 'rougeL': np.float64(0.23316266545852293),
 'rougeLsum': np.float64(0.23318815134746396)}

### Summarized Lexical Overlap Results

In [ ]:
import pandas as pd

# Build a summary table
metrics_table = pd.DataFrame([
    {"metric": "BLEU",         "score": bleu},
    {"metric": "Google BLEU",  "score": gbleu},
    {"metric": "METEOR",       "score": meteor},
    {"metric": "ROUGE-1",      "score": rouge["rouge1"]},
    {"metric": "ROUGE-2",      "score": rouge["rouge2"]},
    {"metric": "ROUGE-L",      "score": rouge["rougeL"]},
])

In [ ]:
metrics_table

        metric     score
0         BLEU  0.076524
1  Google BLEU  0.115862
2       METEOR  0.303152
3      ROUGE-1  0.329825
4      ROUGE-2  0.105327
5      ROUGE-L  0.233163

In [ ]:
from datasets import Dataset

repo = "Lakshan2003/Lexical-Overlap-Results-Llama-3.2-1b-financial-customerservice"

hf_dataset = Dataset.from_pandas(metrics_table.reset_index(drop=True))

# Push to the hub
hf_dataset.push_to_hub(repo)

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.18kB / 1.18kB

README.md:   0%|          | 0.00/297 [00:00<?, ?B/s]

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

CommitInfo(commit_url='https://huggingface.co/datasets/Lakshan2003/Lexical-Overlap-Results-Llama-3.1-8b-financial-customerservice/commit/7db3d45b90256f4bfd3ed06df68b166a0d0a9fd0', commit_message='Upload dataset', commit_description='', oid='7db3d45b90256f4bfd3ed06df68b166a0d0a9fd0', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/Lakshan2003/Lexical-Overlap-Results-Llama-3.1-8b-financial-customerservice', endpoint='https://huggingface.co', repo_type='dataset', repo_id='Lakshan2003/Lexical-Overlap-Results-Llama-3.1-8b-financial-customerservice'), pr_revision=None, pr_num=None)

## Semantic Similarity Metrics

In [ ]:
from datasets import load_dataset

ds = load_dataset("csv", data_files=results_path, split="train")
ds

Generating train split: 0 examples [00:00, ? examples/s]

Dataset({
    features: ['conversation_id', 'instruction', 'history', 'history_summary', 'client_question', 'ground_truth', 'generated_answer'],
    num_rows: 36669
})

In [ ]:
import torch
from sentence_transformers import SentenceTransformer

device = "cuda" if torch.cuda.is_available() else "cpu"
model = SentenceTransformer("sentence-transformers/all-mpnet-base-v2", device=device)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

### Generate embeddings for Groundtruth and generated answer

In [ ]:
def embed_batch(batch):
    gen = [str(x) if x is not None else "" for x in batch["generated_answer"]]
    gt  = [str(x) if x is not None else "" for x in batch["ground_truth"]]

    # normalize_embeddings=True => unit vectors, so cosine = dot product
    gen_emb = model.encode(gen, convert_to_numpy=True, normalize_embeddings=True, batch_size=64, show_progress_bar=False)
    gt_emb  = model.encode(gt,  convert_to_numpy=True, normalize_embeddings=True, batch_size=64, show_progress_bar=False)

    # store as lists
    return {
        "generated_answer_embedding_transformers": [e.tolist() for e in gen_emb],
        "ground_truth_embedding_transformers": [e.tolist() for e in gt_emb],
    }

ds = ds.map(embed_batch, batched=True, batch_size=256)
ds

Map:   0%|          | 0/36669 [00:00<?, ? examples/s]

Dataset({
    features: ['conversation_id', 'instruction', 'history', 'history_summary', 'client_question', 'ground_truth', 'generated_answer', 'generated_answer_embedding_transformers', 'ground_truth_embedding_transformers'],
    num_rows: 36669
})

In [ ]:
import numpy as np

def cosine_batch(batch):
    gen = np.array(batch["generated_answer_embedding_transformers"], dtype=np.float32)
    gt  = np.array(batch["ground_truth_embedding_transformers"], dtype=np.float32)

    # cosine = sum(gen * gt) (using normalized embeddings)
    cos = (gen * gt).sum(axis=1)
    return {"cosine_similarity": cos.tolist()}

ds = ds.map(cosine_batch, batched=True, batch_size=1024)

Map:   0%|          | 0/36669 [00:00<?, ? examples/s]

### BERT Score

In [ ]:
import evaluate
bertscore = evaluate.load("bertscore")

def add_bertscore(batch):
    preds = [str(x) if x else "" for x in batch["generated_answer"]]
    refs  = [str(x) if x else "" for x in batch["ground_truth"]]
    result = bertscore.compute(predictions=preds, references=refs, lang="en")
    return {
        "bertscore_precision": result["precision"],
        "bertscore_recall": result["recall"],
        "bertscore_f1": result["f1"],
    }

ds = ds.map(add_bertscore, batched=True, batch_size=64)

Downloading builder script: 0.00B [00:00, ?B/s]

Map:   0%|          | 0/36669 [00:00<?, ? examples/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/482 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

### BART Score

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

bart_tokenizer = AutoTokenizer.from_pretrained("facebook/bart-large-cnn")
bart_model = AutoModelForSeq2SeqLM.from_pretrained("facebook/bart-large-cnn").to(device)
bart_model.eval()

config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

BartForConditionalGeneration(
  (model): BartModel(
    (shared): BartScaledWordEmbedding(50264, 1024, padding_idx=1)
    (encoder): BartEncoder(
      (embed_tokens): BartScaledWordEmbedding(50264, 1024, padding_idx=1)
      (embed_positions): BartLearnedPositionalEmbedding(1026, 1024)
      (layers): ModuleList(
        (0-11): 12 x BartEncoderLayer(
          (self_attn): BartAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (activation_fn): GELUActivation()
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layernorm_embedding): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    )
    (decoder): BartDecoder(
      (embed_tokens): BartScaledWordEmbedding(50264, 1024, padding_idx=1)
      (embed_positions): BartLearnedPositionalEmbedding(1026, 1024)
      (layers): ModuleList(
        (0-11): 12 x BartDecoderLayer(
          (self_attn): BartAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (activation_fn): GELUActivation()
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (encoder_attn): BartAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (encoder_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layernorm_embedding): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    )
  )
  (lm_head): Linear(in_features=1024, out_features=50264, bias=False)
)

In [ ]:
def compute_bartscore(sources, targets):
    scores = []
    for src, tgt in zip(sources, targets):
        inputs = bart_tokenizer(src, return_tensors="pt", truncation=True, max_length=512).to(device)
        with bart_tokenizer.as_target_tokenizer():
            labels = bart_tokenizer(tgt, return_tensors="pt", truncation=True, max_length=512).to(device)
        with torch.no_grad():
            loss = bart_model(**inputs, labels=labels["input_ids"]).loss
        scores.append(-loss.item())  # negative loss = BARTScore
    return scores

def add_bartscore(batch):
    preds = [str(x) if x else "" for x in batch["generated_answer"]]
    refs  = [str(x) if x else "" for x in batch["ground_truth"]]
    ref_hyp = compute_bartscore(refs, preds)
    hyp_ref = compute_bartscore(preds, refs)
    mean_score = [(a + b) / 2 for a, b in zip(ref_hyp, hyp_ref)]
    return {
        "bartscore_ref_hyp": ref_hyp,
        "bartscore_hyp_ref": hyp_ref,
        "bartscore_mean": mean_score,
    }

In [ ]:
ds = ds.map(add_bartscore, batched=True, batch_size=128)

Map:   0%|          | 0/36669 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:4169: UserWarning: `as_target_tokenizer` is deprecated and will be removed in v5 of Transformers. You can tokenize your labels by using the argument `text_target` of the regular `__call__` method (either in the same call as your input texts if you use the same keyword arguments, or in a separate call.
  warnings.warn(

### Semantic Similarity based Scores

In [ ]:
df = ds.to_pandas()

In [ ]:
print("Summary:")
print(f"Mean cosine similarity : {df['cosine_similarity'].mean():.4f}")
print(f"Mean BERTScore F1      : {df['bertscore_f1'].mean():.4f}")
print(f"Mean BARTScore (mean)  : {df['bartscore_mean'].mean():.4f}")

Summary:
Mean cosine similarity : 0.5909
Mean BERTScore F1      : 0.8821
Mean BARTScore (mean)  : -2.7060

In [ ]:
import os
import pandas as pd

MODEL_NAME = "Llama-3.2_1B-instruct"
SAVE_DIR = "/content/drive/MyDrive/fyp-2025/Datasets/Semantic_Lexical_Similarity_Results"

metrics_rows = [
    {"model": MODEL_NAME, "metric": "BLEU",        "value": float(bleu)},
    {"model": MODEL_NAME, "metric": "Google BLEU", "value": float(gbleu)},
    {"model": MODEL_NAME, "metric": "METEOR",      "value": float(meteor)},
    {"model": MODEL_NAME, "metric": "ROUGE-1",     "value": float(rouge["rouge1"])},
    {"model": MODEL_NAME, "metric": "ROUGE-2",     "value": float(rouge["rouge2"])},
    {"model": MODEL_NAME, "metric": "ROUGE-L",     "value": float(rouge["rougeL"])},
    {"model": MODEL_NAME, "metric": "Cosine Similarity (mean)", "value": float(df["cosine_similarity"].mean())},
    {"model": MODEL_NAME, "metric": "BERTScore F1 (mean)",      "value": float(df["bertscore_f1"].mean())},
    {"model": MODEL_NAME, "metric": "BARTScore (mean)",         "value": float(df["bartscore_mean"].mean())},
]

metrics_table = pd.DataFrame(metrics_rows)

os.makedirs(SAVE_DIR, exist_ok=True)
csv_path = f"{SAVE_DIR}/metrics_{MODEL_NAME}.csv"
metrics_table.to_csv(csv_path, index=False)

print(csv_path)

## Context-Aware similarities

### Conditional BERT Score

In [ ]:
from datasets import load_dataset

ds = load_dataset("csv", data_files=results_path, split="train")
ds

Dataset({
    features: ['conversation_id', 'instruction', 'history', 'history_summary', 'client_question', 'ground_truth', 'generated_answer'],
    num_rows: 36669
})

In [ ]:
import evaluate

conditional_bertscore_metric = evaluate.load("bertscore")

def add_conditional_bertscore(batch):
    conditioned_predictions = []
    conditioned_references  = []

    for hist, question, gen_ans, gt_ans in zip(
        batch["history_summary"],
        batch["client_question"],
        batch["generated_answer"],
        batch["ground_truth"]
    ):
        hist = str(hist) if hist else ""
        question = str(question) if question else ""
        gen_ans = str(gen_ans) if gen_ans else ""
        gt_ans  = str(gt_ans) if gt_ans else ""

        condition = (
            "Conversation History: " + hist.strip() + "\n"
            "Client Question: " + question.strip()
        )

        conditioned_predictions.append(
            condition + "\nAnswer: " + gen_ans
        )

        conditioned_references.append(
            condition + "\nAnswer: " + gt_ans
        )

    scores = conditional_bertscore_metric.compute(
        predictions=conditioned_predictions,
        references=conditioned_references,
        lang="en"
    )

    return {
        "conditional_bertscore_precision": scores["precision"],
        "conditional_bertscore_recall": scores["recall"],
        "conditional_bertscore_f1": scores["f1"],
    }

ds = ds.map(add_conditional_bertscore, batched=True, batch_size=64)

Map:   0%|          | 0/36669 [00:00<?, ? examples/s]

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

#### Context BART Score

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

device = "cuda" if torch.cuda.is_available() else "cpu"

bart_tokenizer = AutoTokenizer.from_pretrained("facebook/bart-large-cnn")
bart_model = AutoModelForSeq2SeqLM.from_pretrained(
    "facebook/bart-large-cnn"
).to(device)

bart_model.eval()

BartForConditionalGeneration(
  (model): BartModel(
    (shared): BartScaledWordEmbedding(50264, 1024, padding_idx=1)
    (encoder): BartEncoder(
      (embed_tokens): BartScaledWordEmbedding(50264, 1024, padding_idx=1)
      (embed_positions): BartLearnedPositionalEmbedding(1026, 1024)
      (layers): ModuleList(
        (0-11): 12 x BartEncoderLayer(
          (self_attn): BartAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (activation_fn): GELUActivation()
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layernorm_embedding): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    )
    (decoder): BartDecoder(
      (embed_tokens): BartScaledWordEmbedding(50264, 1024, padding_idx=1)
      (embed_positions): BartLearnedPositionalEmbedding(1026, 1024)
      (layers): ModuleList(
        (0-11): 12 x BartDecoderLayer(
          (self_attn): BartAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (activation_fn): GELUActivation()
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (encoder_attn): BartAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (encoder_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layernorm_embedding): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    )
  )
  (lm_head): Linear(in_features=1024, out_features=50264, bias=False)
)

In [ ]:
def compute_bartscore(source_texts, target_texts):
    scores = []

    for src, tgt in zip(source_texts, target_texts):
        inputs = bart_tokenizer(
            src,
            return_tensors="pt",
            truncation=True,
            max_length=1024
        ).to(device)

        with bart_tokenizer.as_target_tokenizer():
            labels = bart_tokenizer(
                tgt,
                return_tensors="pt",
                truncation=True,
                max_length=1024
            ).to(device)

        with torch.no_grad():
            loss = bart_model(
                **inputs,
                labels=labels["input_ids"]
            ).loss

        # Negative log-likelihood = BARTScore
        scores.append(-loss.item())

    return scores

In [ ]:
def add_context_aware_bartscore(batch):
    source_texts = []
    generated_targets = []
    reference_targets = []

    for hist, question, gen_ans, gt_ans in zip(
        batch["history_summary"],
        batch["client_question"],
        batch["generated_answer"],
        batch["ground_truth"],
    ):
        hist = str(hist) if hist else ""
        question = str(question) if question else ""
        gen_ans = str(gen_ans) if gen_ans else ""
        gt_ans  = str(gt_ans) if gt_ans else ""

        context_prefix = (
            "Conversation History: " + hist.strip() + "\n"
            "Client Question: " + question.strip()
        )

        # Same source for both directions
        source_texts.append(context_prefix)

        generated_targets.append(gen_ans)
        reference_targets.append(gt_ans)

    # Reference → Generated
    bartscore_ref_to_gen = compute_bartscore(
        source_texts,
        generated_targets
    )

    # Reference → Ground truth
    bartscore_ref_to_gt = compute_bartscore(
        source_texts,
        reference_targets
    )

    bartscore_mean = [
        (a + b) / 2
        for a, b in zip(bartscore_ref_to_gen, bartscore_ref_to_gt)
    ]

    return {
        "bartscore_ctx_ref_gen": bartscore_ref_to_gen,
        "bartscore_ctx_ref_gt": bartscore_ref_to_gt,
        "bartscore_ctx_mean": bartscore_mean,
    }

In [ ]:
ds = ds.map(add_context_aware_bartscore, batched=True, batch_size=128)

Map:   0%|          | 0/36669 [00:00<?, ? examples/s]

#### Context Aware Cosine Similarity

In [ ]:
import torch
from sentence_transformers import SentenceTransformer

device = "cuda" if torch.cuda.is_available() else "cpu"

sentence_encoder = SentenceTransformer(
    "sentence-transformers/all-mpnet-base-v2",
    device=device
)

In [ ]:
def embed_context_aware_sentences(batch):
    generated_texts = []
    reference_texts = []

    for hist, question, gen_ans, gt_ans in zip(
        batch["history_summary"],
        batch["client_question"],
        batch["generated_answer"],
        batch["ground_truth"],
    ):
        hist = str(hist) if hist else ""
        question = str(question) if question else ""
        gen_ans = str(gen_ans) if gen_ans else ""
        gt_ans  = str(gt_ans) if gt_ans else ""

        context_prefix = (
            "Conversation History: " + hist.strip() + "\n"
            "Client Question: " + question.strip()
        )

        generated_texts.append(
            context_prefix + "\nAnswer: " + gen_ans
        )

        reference_texts.append(
            context_prefix + "\nAnswer: " + gt_ans
        )

    generated_embeddings = sentence_encoder.encode(
        generated_texts,
        convert_to_numpy=True,
        normalize_embeddings=True,
        batch_size=64,
        show_progress_bar=False
    )

    reference_embeddings = sentence_encoder.encode(
        reference_texts,
        convert_to_numpy=True,
        normalize_embeddings=True,
        batch_size=64,
        show_progress_bar=False
    )

    return {
        "context_aware_generated_embedding": [e.tolist() for e in generated_embeddings],
        "context_aware_reference_embedding": [e.tolist() for e in reference_embeddings],
    }

ds = ds.map(embed_context_aware_sentences, batched=True, batch_size=256)

Map:   0%|          | 0/36669 [00:00<?, ? examples/s]

In [ ]:
import numpy as np

def context_aware_cosine_similarity(batch):
    gen_emb = np.array(
        batch["context_aware_generated_embedding"],
        dtype=np.float32
    )
    ref_emb = np.array(
        batch["context_aware_reference_embedding"],
        dtype=np.float32
    )

    cosine_scores = (gen_emb * ref_emb).sum(axis=1)

    return {
        "context_aware_cosine_similarity": cosine_scores.tolist()
    }

ds = ds.map(context_aware_cosine_similarity, batched=True, batch_size=1024)

Map:   0%|          | 0/36669 [00:00<?, ? examples/s]

In [ ]:
import numpy as np

def context_aware_cosine_similarity(batch):
    gen_emb = np.array(
        batch["context_aware_generated_embedding"],
        dtype=np.float32
    )
    ref_emb = np.array(
        batch["context_aware_reference_embedding"],
        dtype=np.float32
    )

    cosine_scores = (gen_emb * ref_emb).sum(axis=1)

    return {
        "context_aware_cosine_similarity": cosine_scores.tolist()
    }

ds = ds.map(context_aware_cosine_similarity, batched=True, batch_size=1024)

Map:   0%|          | 0/36669 [00:00<?, ? examples/s]

In [ ]:
df = ds.to_pandas()

In [ ]:
print("Context-aware Evaluation Summary:")

print(f"Mean cosine similarity (context-aware sentence embeddings) : "
      f"{df['context_aware_cosine_similarity'].mean():.4f}")

print(f"Mean BERTScore F1 (context-aware)                          : "
      f"{df['conditional_bertscore_f1'].mean():.4f}")

print(f"Mean BARTScore (context-aware mean)                        : "
      f"{df['bartscore_ctx_mean'].mean():.4f}")

Context-aware Evaluation Summary:
Mean cosine similarity (context-aware sentence embeddings) : 0.9571
Mean BERTScore F1 (context-aware)                          : 0.9686
Mean BARTScore (context-aware mean)                        : -2.6762

In [ ]:
import os
import pandas as pd

MODEL_NAME = "Llama-3.2_1B-instruct"
SAVE_DIR = "/content/drive/MyDrive/fyp-2025/Datasets/Semantic_Lexical_Similarity_Results"

context_metrics_rows = [
    {
        "model": MODEL_NAME,
        "metric": "Cosine Similarity (context-aware sentence embeddings)",
        "value": float(df["context_aware_cosine_similarity"].mean())
    },
    {
        "model": MODEL_NAME,
        "metric": "BERTScore F1 (context-aware)",
        "value": float(df["conditional_bertscore_f1"].mean())
    },
    {
        "model": MODEL_NAME,
        "metric": "BARTScore (context-aware mean)",
        "value": float(df["bartscore_ctx_mean"].mean())
    },
]

context_metrics_table = pd.DataFrame(context_metrics_rows)

os.makedirs(SAVE_DIR, exist_ok=True)
csv_path = f"{SAVE_DIR}/metrics_context_aware_{MODEL_NAME}.csv"
context_metrics_table.to_csv(csv_path, index=False)

print(csv_path)

### LLM as a judge Evaluation

In [ ]:
from datasets import load_dataset, Dataset
import pandas as pd

def inject_history_from_original_test(
    original_repo,
    eval_repo,
):
    print(f"\nInjecting history")
    print(f"Source (original) → {original_repo} [test split]")
    print(f"Target (eval)     → {eval_repo}")

    #  Load original dataset (TEST split contains history)
    orig_ds = load_dataset(original_repo, split="test")
    orig_df = orig_ds.to_pandas()

    history_map = (
        orig_df[["conversation_id", "conversation_history"]]
        .rename(columns={"conversation_history": "history"})
        .drop_duplicates(subset="conversation_id")
    )

    #  Load eval dataset
    eval_ds = load_dataset(eval_repo, split="train")
    eval_df = eval_ds.to_pandas()

    # Drop existing history if any
    if "history" in eval_df.columns:
        eval_df = eval_df.drop(columns=["history"])

    #  Merge history
    merged = eval_df.merge(
        history_map,
        on="conversation_id",
        how="left",
        validate="many_to_one",
    )

    #  Sanity check
    if merged["history"].isna().any():
        raise RuntimeError("Some conversation_ids are missing history")

    #  ENFORCE COLUMN ORDER (history after instruction)
    ordered_cols = [
        "conversation_id",
        "instruction",
        "history",
    ]

    # Append remaining columns in original order
    ordered_cols += [c for c in merged.columns if c not in ordered_cols]

    merged = merged[ordered_cols]

    #  Push back to Hugging Face
    updated_ds = Dataset.from_pandas(merged)
    updated_ds.push_to_hub(eval_repo, private=False)

    print(f"Updated dataset pushed → https://huggingface.co/datasets/{eval_repo}")

In [ ]:
inject_history_from_original_test(
    original_repo="Lakshan2003/customer-support-client-agent-conversations",
    eval_repo="Lakshan2003/Llama3.2-1B-instruct-customerservice-evaldata",
)

Injecting history
Source (original) → Lakshan2003/customer-support-client-agent-conversations [test split]
Target (eval)     → Lakshan2003/Llama3.2-1B-instruct-customerservice-evaldata

README.md:   0%|          | 0.00/809 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/148M [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/42.4M [00:00<?, ?B/s]

data/validation-00000-of-00001.parquet:   0%|          | 0.00/21.1M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/128335 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/36669 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/18333 [00:00<?, ? examples/s]

README.md:   0%|          | 0.00/541 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/43.6M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/36669 [00:00<?, ? examples/s]

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/37 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              :  60%|#####9    | 25.9MB / 43.5MB

Updated dataset pushed → https://huggingface.co/datasets/Lakshan2003/Llama3.2-1B-instruct-customerservice-evaldata

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
import time
import json
import pandas as pd
from anthropic import Anthropic

#### Claude API setup

In [ ]:
from google.colab import userdata
claude_api = userdata.get('claude_api')

In [ ]:
anthropic = Anthropic(api_key=claude_api)

In [ ]:
# Configuration
original_csv = "/content/drive/MyDrive/fyp-2025/Datasets/LLMJudgeData/Llama3.2-1B-instruct-customerservice-evaldata.csv"

processed_folder = "/content/drive/MyDrive/fyp-2025/Datasets/LLMJudgeProcessedData/"
processed_csv = processed_folder + "Llama3.2-1B-instruct-customerservice-evaldata.csv"

batch_size = 25
batch_pause = 1.5  # seconds

In [ ]:
import os

base_path = "/content/drive/MyDrive/fyp-2025/Datasets/LLMJudgeProcessedData/"

for root, dirs, files in os.walk(base_path):
    for file in files:
        print(os.path.join(root, file))

/content/drive/MyDrive/fyp-2025/Datasets/LLMJudgeProcessedData/Virtuoso-large-customerservice-evaldata.csv
/content/drive/MyDrive/fyp-2025/Datasets/LLMJudgeProcessedData/SmolLM3-3B-customerservice-evaldata.csv
/content/drive/MyDrive/fyp-2025/Datasets/LLMJudgeProcessedData/Phi-4-mini-customerservice-evaldata.csv
/content/drive/MyDrive/fyp-2025/Datasets/LLMJudgeProcessedData/GPT-4.1-customerservice-evaldata.csv
/content/drive/MyDrive/fyp-2025/Datasets/LLMJudgeProcessedData/Llama3.2-instruct-customerservice-evaldata.csv
/content/drive/MyDrive/fyp-2025/Datasets/LLMJudgeProcessedData/Gemma3-4B-instruct-customerservice-evaldata.csv
/content/drive/MyDrive/fyp-2025/Datasets/LLMJudgeProcessedData/Qwen3-4B-customerservice-evaldata.csv
/content/drive/MyDrive/fyp-2025/Datasets/LLMJudgeProcessedData/gemini-2.5-flash-customerservice-evaldata.csv
/content/drive/MyDrive/fyp-2025/Datasets/LLMJudgeProcessedData/Llama3.1-8b-instruct-customerservice-evaldata.csv
/content/drive/MyDrive/fyp-2025/Datasets/LLMJudgeProcessedData/Qwen3-8B-customerservice-evaldata.csv
/content/drive/MyDrive/fyp-2025/Datasets/LLMJudgeProcessedData/Llama3.2-1B-instruct-customerservice-evaldata.csv
/content/drive/MyDrive/fyp-2025/Datasets/LLMJudgeProcessedData/Qwen3-1.7B-customerservice-evaldata.csv

#### EVALUATION PROMPT TEMPLATE (outside loop)

In [ ]:
EVAL_PROMPT = """
You are an expert evaluator specializing in customer-service interactions.
Evaluate the Generated Response using the Client Question and Conversation History summary as context, along with a Reference Agent Response provided only as a high-quality example.
The Reference Agent Response is provided only as guidance to illustrate what a professional, contextually appropriate answer might look like.
The Generated Response should NOT replicate or closely mirror it.
Instead, it should demonstrate human-like fluency, contextual understanding, and professionalism while maintaining natural variation in expression and tone.
Your task is to assess how human-like, contextually aware, and professionally appropriate the Generated Response is.

Note:
The Conversation History Summary represents the main context that was used when generating the response.
The full Conversation History is provided only as additional background information to help you better understand the situation if needed.

Context Inputs:
Conversation History: {history}
Conversation Summarized History: {history_summary}
Client Question: {client_question}
Reference Agent Response (for guidance only): {ground_truth}
Generated Response: {generated_answer}

Evaluation Criteria and Scoring (1–5 each):

1. Human-Likeness:
This checks how natural and fluent the Generated Response sounds in normal spoken conversation.
It looks at flow, rhythm, and how close it feels to real human speech.

Rating Scale:
1 = Highly robotic or unnatural
2 = Noticeably rigid or scripted
3 = Generally natural but somewhat stiff
4 = Natural and conversational
5 = Fully natural, smooth, and human-like

2. Continuity and Context Understanding:
This evaluates how well the Generated Response integrates with the preceding conversation whether it maintains continuity,
references earlier details accurately, and demonstrates awareness of situational context.

Rating Scale:
1 = Ignores or contradicts context
2 = Uses context incorrectly or inconsistently
3 = Uses context but with noticeable gaps
4 = Accurate and consistent use of context
5 = Fully coherent, precise integration of context

3. Tone and Clarity:
This measures verbal tone, emotional intelligence, and clarity of expression.
It assesses professionalism, empathy, politeness, and phrasing appropriateness for a spoken customer-service exchange.

Rating Scale:
1 = Unprofessional or unclear
2 = Understandable but flat or loosely structured
3 = Clear and appropriate, with standard professionalism
4 = Professional, well-structured, and concise
5 = Highly polished, clear, respectful, and well-balanced

4. Task Appropriateness:
This evaluates whether the Generated Response successfully and completely addresses the client’s stated need,
while maintaining procedural accuracy typical of a service agent.

Rating Scale:
1 = Does not address the client’s request
2 = Addresses request incompletely
3 = Provides an adequate response
4 = Fully addresses the request
5 = Fully addresses the request and adds meaningful helpful value

Return your answer as valid JSON only.
Do not include any explanation, commentary, additional text, or markdown formatting.
Output must contain JSON only and nothing else.All the below keys and there judgement score should be included in your json response. Strictly follow only below json output.always provide the score for all tasks in the json.

Output Format (return only JSON):
{{
  "Human-Likeness": [1–5],
  "Continuity-and-Context-Understanding": [1–5],
  "Tone-and-Clarity": [1–5],
  "Task-Appropriateness": [1–5]
}}
"""

In [ ]:
# Load Original or Resume From Processed Copy
os.makedirs(processed_folder, exist_ok=True)

if os.path.exists(processed_csv):
    print("Existing processed file found. Resuming from previous progress...")
    df = pd.read_csv(processed_csv)
else:
    print("No processed copy found. Creating one...")
    df = pd.read_csv(original_csv)

    # Add scoring columns if missing
    score_cols = [
        "Human-Likeness",
        "Continuity and Context Understanding",
        "Tone and Clarity",
        "Task Appropriateness"
    ]
    for c in score_cols:
        if c not in df.columns:
            df[c] = ""

    df.to_csv(processed_csv, index=False, encoding="utf-8-sig")

print("Loaded rows:", len(df))

Existing processed file found. Resuming from previous progress...
Loaded rows: 6000

In [ ]:
# 5. Identify Rows That Need Processing
mask = df["Human-Likeness"].isna() | (df["Human-Likeness"] == "")
remaining_rows = df[mask]

start_index = len(df) - len(remaining_rows)
print(f"Starting evaluation from row {start_index}/{len(df)}\n")

batch_counter = 0

Starting evaluation from row 6000/6000

In [ ]:
def safe_get(d, keys, row_idx, field_name):
    """
    d: the JSON dict returned by Claude
    keys: list of alternative keys to try
    """
    for k in keys:
        if k in d:
            return d[k]
    raise KeyError(f"Missing '{field_name}' in JSON at row {row_idx}. JSON keys returned: {list(d.keys())}")

In [ ]:
df.head(2)

,conversation_id,conversation_stage,instruction,history,history_summary,client_question,ground_truth,generated_answer,Human-Likeness,Continuity and Context Understanding,Tone and Clarity,Task Appropriateness
0,de113f1e2694439291a0af26edcc71e5,MIDDLE,You are a professional call-center customer se...,"Client: Hi,erek, I'm calling because I want to...",Delores Smith has requested to transition to p...,"Okay, that sounds simple enough. How why do I ...","I understand your concern, Delores. We ask for...","You're right, you're already receiving electro...",3.0,2.0,3.0,2.0
1,f8ccb93edcd7433eb94df4da1a0e8b73,END,You are a professional call-center customer se...,"Agent: Hi morning, thank you for choosing Mode...","The client, Jeanetta, contacted ModernBank to ...","No,ries, Collin. You've been very helpful so f...","Thank you, Jeanetta. I really appreciate your ...","I completely understand your concern, Jeanetta...",3.0,2.0,3.0,2.0

#### MAIN LOOP

In [ ]:
from tqdm import tqdm
import re
import json

# MAIN EVALUATION LOOP WITH TQDM
for idx in tqdm(remaining_rows.index, desc="Evaluating rows", unit="row"):

    row = df.loc[idx]

    prompt_filled = EVAL_PROMPT.format(
        history=row["history"],
        history_summary=row["history_summary"],
        client_question=row["client_question"],
        ground_truth=row["ground_truth"],
        generated_answer=row["generated_answer"],
    )

    try:
        # SEND REQUEST TO CLAUDE
        response = anthropic.messages.create(
            model="claude-sonnet-4-5",
            max_tokens=500,
            temperature=0,
            messages=[{"role": "user", "content": prompt_filled}],
        )

        # EXTRACT RAW TEXT
        raw_text = response.content[0].text.strip()
        if not raw_text:
            raise ValueError("Claude returned an empty response")

        # CLEAN THE JSON TEXT
        cleaned = raw_text.strip()

        cleaned = re.sub(r"^```[a-zA-Z0-9]*\s*", "", cleaned)
        cleaned = re.sub(r"\s*```$", "", cleaned)
        cleaned = re.sub(r"<[^>]+>", "", cleaned).strip()
        cleaned = cleaned.replace("\ufeff", "").replace("\u200b", "").strip("`").strip()

        # TRY PARSING JSON
        try:
            result_json = json.loads(cleaned)
        except json.JSONDecodeError:
            raise ValueError(f"Invalid JSON from Claude:\n{raw_text}")

        # UPDATE DF ONLY IF SUCCESSFUL
        df.at[idx, "Human-Likeness"] = result_json["Human-Likeness"]
        df.at[idx, "Continuity and Context Understanding"] = result_json[
            "Continuity-and-Context-Understanding"
        ]
        df.at[idx, "Tone and Clarity"] = result_json["Tone-and-Clarity"]
        df.at[idx, "Task Appropriateness"] = result_json["Task-Appropriateness"]

        # SAVE BATCH (SAFE)
        batch_counter += 1

        if batch_counter >= batch_size:
            df.to_csv(processed_csv, index=False, encoding="utf-8-sig")
            print(f"Batch saved (processed up to row {idx}).")
            batch_counter = 0

    except Exception as e:
        # ON ANY ERROR, STOP IMMEDIATELY
        # DO NOT SAVE ANYTHING
        print(f"\nERROR at row {idx}: {e}")
        print("Stopping execution WITHOUT saving this partial batch.")
        break

    time.sleep(batch_pause)

Evaluating rows:   0%|          | 0/2500 [00:00<?, ?row/s]

Evaluating rows:   0%|          | 1/2500 [00:02<1:50:01,  2.64s/row]

Evaluating rows:   0%|          | 2/2500 [00:05<1:51:03,  2.67s/row]

Evaluating rows:   0%|          | 3/2500 [00:07<1:49:26,  2.63s/row]

Evaluating rows:   0%|          | 4/2500 [00:10<1:50:03,  2.65s/row]

Evaluating rows:   0%|          | 5/2500 [00:13<1:50:05,  2.65s/row]

Evaluating rows:   0%|          | 6/2500 [00:17<2:18:09,  3.32s/row]

Evaluating rows:   0%|          | 7/2500 [00:20<2:11:06,  3.16s/row]

Evaluating rows:   0%|          | 8/2500 [00:25<2:28:08,  3.57s/row]

Evaluating rows:   0%|          | 9/2500 [00:27<2:17:16,  3.31s/row]

Evaluating rows:   0%|          | 10/2500 [00:30<2:08:37,  3.10s/row]

Evaluating rows:   0%|          | 11/2500 [00:33<2:03:14,  2.97s/row]

Evaluating rows:   0%|          | 12/2500 [00:36<2:03:03,  2.97s/row]

Evaluating rows:   1%|          | 13/2500 [00:39<2:03:00,  2.97s/row]

Evaluating rows:   1%|          | 14/2500 [00:41<1:58:50,  2.87s/row]

Evaluating rows:   1%|          | 15/2500 [00:44<1:57:55,  2.85s/row]

Evaluating rows:   1%|          | 16/2500 [00:47<1:55:09,  2.78s/row]

Evaluating rows:   1%|          | 17/2500 [00:49<1:55:38,  2.79s/row]

Evaluating rows:   1%|          | 18/2500 [00:52<1:54:13,  2.76s/row]

Evaluating rows:   1%|          | 19/2500 [00:55<1:56:24,  2.82s/row]

Evaluating rows:   1%|          | 20/2500 [01:00<2:24:40,  3.50s/row]

Evaluating rows:   1%|          | 21/2500 [01:03<2:13:46,  3.24s/row]

Evaluating rows:   1%|          | 22/2500 [01:15<4:05:40,  5.95s/row]

Evaluating rows:   1%|          | 23/2500 [01:18<3:25:35,  4.98s/row]

Evaluating rows:   1%|          | 24/2500 [01:21<2:59:46,  4.36s/row]

Batch saved (processed up to row 3524).

Evaluating rows:   1%|          | 25/2500 [01:27<3:26:27,  5.01s/row]

Evaluating rows:   1%|          | 26/2500 [01:30<2:59:47,  4.36s/row]

Evaluating rows:   1%|          | 27/2500 [01:33<2:38:55,  3.86s/row]

Evaluating rows:   1%|          | 28/2500 [01:36<2:25:42,  3.54s/row]

Evaluating rows:   1%|          | 29/2500 [01:40<2:34:23,  3.75s/row]

Evaluating rows:   1%|          | 30/2500 [01:43<2:21:51,  3.45s/row]

Evaluating rows:   1%|          | 31/2500 [01:45<2:11:23,  3.19s/row]

Evaluating rows:   1%|▏         | 32/2500 [01:48<2:06:27,  3.07s/row]

Evaluating rows:   1%|▏         | 33/2500 [01:52<2:15:58,  3.31s/row]

Evaluating rows:   1%|▏         | 34/2500 [01:55<2:08:49,  3.13s/row]

Evaluating rows:   1%|▏         | 35/2500 [01:57<2:03:33,  3.01s/row]

Evaluating rows:   1%|▏         | 36/2500 [02:00<2:06:09,  3.07s/row]

Evaluating rows:   1%|▏         | 37/2500 [02:03<2:01:02,  2.95s/row]

Evaluating rows:   2%|▏         | 38/2500 [02:06<1:57:12,  2.86s/row]

Evaluating rows:   2%|▏         | 39/2500 [02:08<1:55:05,  2.81s/row]

Evaluating rows:   2%|▏         | 40/2500 [02:11<1:55:47,  2.82s/row]

Evaluating rows:   2%|▏         | 41/2500 [02:15<2:05:37,  3.07s/row]

Evaluating rows:   2%|▏         | 42/2500 [02:18<2:01:50,  2.97s/row]

Evaluating rows:   2%|▏         | 43/2500 [02:20<1:58:42,  2.90s/row]

Evaluating rows:   2%|▏         | 44/2500 [02:23<1:56:23,  2.84s/row]

Evaluating rows:   2%|▏         | 45/2500 [02:27<2:12:15,  3.23s/row]

Evaluating rows:   2%|▏         | 46/2500 [02:30<2:06:41,  3.10s/row]

Evaluating rows:   2%|▏         | 47/2500 [02:33<2:02:03,  2.99s/row]

Evaluating rows:   2%|▏         | 48/2500 [02:36<2:09:47,  3.18s/row]

Evaluating rows:   2%|▏         | 49/2500 [02:40<2:17:59,  3.38s/row]

Batch saved (processed up to row 3549).

Evaluating rows:   2%|▏         | 50/2500 [02:47<2:57:52,  4.36s/row]

Evaluating rows:   2%|▏         | 51/2500 [02:50<2:37:39,  3.86s/row]

Evaluating rows:   2%|▏         | 52/2500 [02:54<2:41:04,  3.95s/row]

Evaluating rows:   2%|▏         | 53/2500 [02:56<2:25:27,  3.57s/row]

Evaluating rows:   2%|▏         | 54/2500 [02:59<2:13:23,  3.27s/row]

Evaluating rows:   2%|▏         | 55/2500 [03:10<3:46:55,  5.57s/row]

Evaluating rows:   2%|▏         | 56/2500 [03:13<3:11:16,  4.70s/row]

Evaluating rows:   2%|▏         | 57/2500 [03:17<3:01:52,  4.47s/row]

Evaluating rows:   2%|▏         | 58/2500 [03:19<2:41:46,  3.97s/row]

Evaluating rows:   2%|▏         | 59/2500 [03:22<2:27:43,  3.63s/row]

Evaluating rows:   2%|▏         | 60/2500 [03:26<2:25:12,  3.57s/row]

Evaluating rows:   2%|▏         | 61/2500 [03:28<2:14:17,  3.30s/row]

Evaluating rows:   2%|▏         | 62/2500 [03:31<2:05:56,  3.10s/row]

Evaluating rows:   3%|▎         | 63/2500 [03:35<2:12:52,  3.27s/row]

Evaluating rows:   3%|▎         | 64/2500 [03:37<2:05:10,  3.08s/row]

Evaluating rows:   3%|▎         | 65/2500 [03:40<1:59:53,  2.95s/row]

Evaluating rows:   3%|▎         | 66/2500 [03:43<1:58:23,  2.92s/row]

Evaluating rows:   3%|▎         | 67/2500 [03:46<1:56:39,  2.88s/row]

Evaluating rows:   3%|▎         | 68/2500 [03:48<1:57:33,  2.90s/row]

Evaluating rows:   3%|▎         | 69/2500 [03:51<1:53:59,  2.81s/row]

Evaluating rows:   3%|▎         | 70/2500 [03:54<1:51:49,  2.76s/row]

Evaluating rows:   3%|▎         | 71/2500 [03:56<1:51:44,  2.76s/row]

Evaluating rows:   3%|▎         | 72/2500 [03:59<1:51:20,  2.75s/row]

Evaluating rows:   3%|▎         | 73/2500 [04:02<1:52:14,  2.77s/row]

Evaluating rows:   3%|▎         | 74/2500 [04:05<1:51:05,  2.75s/row]

Batch saved (processed up to row 3574).

Evaluating rows:   3%|▎         | 75/2500 [04:08<2:00:02,  2.97s/row]

Evaluating rows:   3%|▎         | 76/2500 [04:11<1:57:35,  2.91s/row]

Evaluating rows:   3%|▎         | 77/2500 [04:14<1:55:44,  2.87s/row]

Evaluating rows:   3%|▎         | 78/2500 [04:16<1:52:56,  2.80s/row]

Evaluating rows:   3%|▎         | 79/2500 [04:19<1:55:26,  2.86s/row]

Evaluating rows:   3%|▎         | 80/2500 [04:22<1:52:41,  2.79s/row]

Evaluating rows:   3%|▎         | 81/2500 [04:25<1:51:25,  2.76s/row]

Evaluating rows:   3%|▎         | 82/2500 [04:28<1:52:39,  2.80s/row]

Evaluating rows:   3%|▎         | 83/2500 [04:30<1:51:33,  2.77s/row]

Evaluating rows:   3%|▎         | 84/2500 [04:33<1:50:20,  2.74s/row]

Evaluating rows:   3%|▎         | 85/2500 [04:36<1:49:41,  2.73s/row]

Evaluating rows:   3%|▎         | 86/2500 [04:39<1:51:27,  2.77s/row]

Evaluating rows:   3%|▎         | 87/2500 [04:41<1:52:42,  2.80s/row]

Evaluating rows:   4%|▎         | 88/2500 [04:44<1:51:26,  2.77s/row]

Evaluating rows:   4%|▎         | 89/2500 [04:47<1:49:51,  2.73s/row]

Evaluating rows:   4%|▎         | 90/2500 [04:49<1:49:27,  2.73s/row]

Evaluating rows:   4%|▎         | 91/2500 [04:52<1:48:14,  2.70s/row]

Evaluating rows:   4%|▎         | 92/2500 [04:55<1:48:48,  2.71s/row]

Evaluating rows:   4%|▎         | 93/2500 [04:57<1:47:50,  2.69s/row]

Evaluating rows:   4%|▍         | 94/2500 [05:00<1:49:48,  2.74s/row]

Evaluating rows:   4%|▍         | 95/2500 [05:03<1:49:33,  2.73s/row]

Evaluating rows:   4%|▍         | 96/2500 [05:06<1:48:49,  2.72s/row]

Evaluating rows:   4%|▍         | 97/2500 [05:08<1:48:13,  2.70s/row]

Evaluating rows:   4%|▍         | 98/2500 [05:12<2:03:30,  3.09s/row]

Evaluating rows:   4%|▍         | 99/2500 [05:15<1:58:19,  2.96s/row]

Batch saved (processed up to row 3599).

Evaluating rows:   4%|▍         | 100/2500 [05:19<2:07:29,  3.19s/row]

Evaluating rows:   4%|▍         | 101/2500 [05:22<2:05:25,  3.14s/row]

Evaluating rows:   4%|▍         | 102/2500 [05:26<2:19:34,  3.49s/row]

Evaluating rows:   4%|▍         | 103/2500 [05:29<2:09:38,  3.25s/row]

Evaluating rows:   4%|▍         | 104/2500 [05:31<2:02:49,  3.08s/row]

Evaluating rows:   4%|▍         | 105/2500 [05:34<1:58:19,  2.96s/row]

Evaluating rows:   4%|▍         | 106/2500 [05:37<1:54:16,  2.86s/row]

Evaluating rows:   4%|▍         | 107/2500 [05:40<1:52:48,  2.83s/row]

Evaluating rows:   4%|▍         | 108/2500 [05:43<1:59:05,  2.99s/row]

Evaluating rows:   4%|▍         | 109/2500 [05:46<1:55:07,  2.89s/row]

Evaluating rows:   4%|▍         | 110/2500 [05:48<1:52:41,  2.83s/row]

Evaluating rows:   4%|▍         | 111/2500 [05:51<1:51:38,  2.80s/row]

Evaluating rows:   4%|▍         | 112/2500 [05:55<2:01:06,  3.04s/row]

Evaluating rows:   5%|▍         | 113/2500 [05:57<1:57:12,  2.95s/row]

Evaluating rows:   5%|▍         | 114/2500 [06:00<1:53:57,  2.87s/row]

Evaluating rows:   5%|▍         | 115/2500 [06:03<1:52:04,  2.82s/row]

Evaluating rows:   5%|▍         | 116/2500 [06:05<1:50:18,  2.78s/row]

Evaluating rows:   5%|▍         | 117/2500 [06:08<1:48:27,  2.73s/row]

Evaluating rows:   5%|▍         | 118/2500 [06:11<1:48:15,  2.73s/row]

Evaluating rows:   5%|▍         | 119/2500 [06:14<1:58:43,  2.99s/row]

Evaluating rows:   5%|▍         | 120/2500 [06:17<1:55:03,  2.90s/row]

Evaluating rows:   5%|▍         | 121/2500 [06:20<1:52:59,  2.85s/row]

Evaluating rows:   5%|▍         | 122/2500 [06:23<1:55:24,  2.91s/row]

Evaluating rows:   5%|▍         | 123/2500 [06:25<1:52:14,  2.83s/row]

Evaluating rows:   5%|▍         | 124/2500 [06:28<1:51:42,  2.82s/row]

Batch saved (processed up to row 3624).

Evaluating rows:   5%|▌         | 125/2500 [06:32<1:58:33,  3.00s/row]

Evaluating rows:   5%|▌         | 126/2500 [06:34<1:54:35,  2.90s/row]

Evaluating rows:   5%|▌         | 127/2500 [06:37<1:51:34,  2.82s/row]

Evaluating rows:   5%|▌         | 128/2500 [06:40<1:49:50,  2.78s/row]

Evaluating rows:   5%|▌         | 129/2500 [06:43<1:59:14,  3.02s/row]

Evaluating rows:   5%|▌         | 130/2500 [06:46<1:54:39,  2.90s/row]

Evaluating rows:   5%|▌         | 131/2500 [06:50<2:03:31,  3.13s/row]

Evaluating rows:   5%|▌         | 132/2500 [06:52<1:57:11,  2.97s/row]

Evaluating rows:   5%|▌         | 133/2500 [06:58<2:27:50,  3.75s/row]

Evaluating rows:   5%|▌         | 134/2500 [07:01<2:25:55,  3.70s/row]

Evaluating rows:   5%|▌         | 135/2500 [07:04<2:14:16,  3.41s/row]

Evaluating rows:   5%|▌         | 136/2500 [07:08<2:19:42,  3.55s/row]

Evaluating rows:   5%|▌         | 137/2500 [07:11<2:10:03,  3.30s/row]

Evaluating rows:   6%|▌         | 138/2500 [07:13<2:04:11,  3.15s/row]

Evaluating rows:   6%|▌         | 139/2500 [07:16<1:58:52,  3.02s/row]

Evaluating rows:   6%|▌         | 140/2500 [07:19<1:57:07,  2.98s/row]

Evaluating rows:   6%|▌         | 141/2500 [07:22<1:53:11,  2.88s/row]

Evaluating rows:   6%|▌         | 142/2500 [07:24<1:51:33,  2.84s/row]

Evaluating rows:   6%|▌         | 143/2500 [07:28<2:01:30,  3.09s/row]

Evaluating rows:   6%|▌         | 144/2500 [07:31<1:56:55,  2.98s/row]

Evaluating rows:   6%|▌         | 145/2500 [07:34<1:55:14,  2.94s/row]

Evaluating rows:   6%|▌         | 146/2500 [07:36<1:51:43,  2.85s/row]

Evaluating rows:   6%|▌         | 147/2500 [07:39<1:49:56,  2.80s/row]

Evaluating rows:   6%|▌         | 148/2500 [07:42<1:48:00,  2.76s/row]

Evaluating rows:   6%|▌         | 149/2500 [07:44<1:48:01,  2.76s/row]

Batch saved (processed up to row 3649).

Evaluating rows:   6%|▌         | 150/2500 [07:48<1:59:56,  3.06s/row]

Evaluating rows:   6%|▌         | 151/2500 [07:51<1:54:48,  2.93s/row]

Evaluating rows:   6%|▌         | 152/2500 [07:53<1:51:41,  2.85s/row]

Evaluating rows:   6%|▌         | 153/2500 [07:56<1:50:15,  2.82s/row]

Evaluating rows:   6%|▌         | 154/2500 [07:59<1:49:09,  2.79s/row]

Evaluating rows:   6%|▌         | 155/2500 [08:02<1:47:58,  2.76s/row]

Evaluating rows:   6%|▌         | 156/2500 [08:06<2:02:03,  3.12s/row]

Evaluating rows:   6%|▋         | 157/2500 [08:10<2:17:18,  3.52s/row]

Evaluating rows:   6%|▋         | 158/2500 [08:13<2:07:44,  3.27s/row]

Evaluating rows:   6%|▋         | 159/2500 [08:19<2:40:38,  4.12s/row]

Evaluating rows:   6%|▋         | 160/2500 [08:21<2:23:35,  3.68s/row]

Evaluating rows:   6%|▋         | 161/2500 [08:24<2:12:09,  3.39s/row]

Evaluating rows:   6%|▋         | 162/2500 [08:30<2:41:29,  4.14s/row]

Evaluating rows:   7%|▋         | 163/2500 [08:33<2:24:06,  3.70s/row]

Evaluating rows:   7%|▋         | 164/2500 [08:36<2:15:44,  3.49s/row]

Evaluating rows:   7%|▋         | 165/2500 [08:38<2:07:00,  3.26s/row]

Evaluating rows:   7%|▋         | 166/2500 [08:42<2:11:01,  3.37s/row]

Evaluating rows:   7%|▋         | 167/2500 [08:45<2:01:57,  3.14s/row]

Evaluating rows:   7%|▋         | 168/2500 [08:47<1:57:13,  3.02s/row]

Evaluating rows:   7%|▋         | 169/2500 [08:50<1:53:15,  2.92s/row]

Evaluating rows:   7%|▋         | 170/2500 [08:53<1:50:46,  2.85s/row]

Evaluating rows:   7%|▋         | 171/2500 [08:55<1:48:35,  2.80s/row]

Evaluating rows:   7%|▋         | 172/2500 [08:58<1:47:22,  2.77s/row]

Evaluating rows:   7%|▋         | 173/2500 [09:01<1:47:30,  2.77s/row]

Evaluating rows:   7%|▋         | 174/2500 [09:04<1:47:20,  2.77s/row]

Batch saved (processed up to row 3674).

Evaluating rows:   7%|▋         | 175/2500 [09:07<1:55:39,  2.98s/row]

Evaluating rows:   7%|▋         | 176/2500 [09:10<1:52:24,  2.90s/row]

Evaluating rows:   7%|▋         | 177/2500 [09:13<1:51:03,  2.87s/row]

Evaluating rows:   7%|▋         | 178/2500 [09:15<1:48:48,  2.81s/row]

Evaluating rows:   7%|▋         | 179/2500 [09:19<1:58:25,  3.06s/row]

Evaluating rows:   7%|▋         | 180/2500 [09:23<2:07:54,  3.31s/row]

Evaluating rows:   7%|▋         | 181/2500 [09:26<2:01:10,  3.14s/row]

Evaluating rows:   7%|▋         | 182/2500 [09:28<1:56:23,  3.01s/row]

Evaluating rows:   7%|▋         | 183/2500 [09:32<2:08:12,  3.32s/row]

Evaluating rows:   7%|▋         | 184/2500 [09:36<2:14:47,  3.49s/row]

Evaluating rows:   7%|▋         | 185/2500 [09:40<2:15:50,  3.52s/row]

Evaluating rows:   7%|▋         | 186/2500 [09:43<2:06:03,  3.27s/row]

Evaluating rows:   7%|▋         | 187/2500 [09:45<2:00:41,  3.13s/row]

Evaluating rows:   8%|▊         | 188/2500 [09:48<1:54:54,  2.98s/row]

Evaluating rows:   8%|▊         | 189/2500 [09:53<2:19:56,  3.63s/row]

Evaluating rows:   8%|▊         | 190/2500 [09:56<2:08:20,  3.33s/row]

Evaluating rows:   8%|▊         | 191/2500 [09:59<2:02:08,  3.17s/row]

Evaluating rows:   8%|▊         | 192/2500 [10:02<2:08:32,  3.34s/row]

Evaluating rows:   8%|▊         | 193/2500 [10:05<2:00:51,  3.14s/row]

Evaluating rows:   8%|▊         | 194/2500 [10:08<1:55:59,  3.02s/row]

Evaluating rows:   8%|▊         | 195/2500 [10:10<1:51:47,  2.91s/row]

Evaluating rows:   8%|▊         | 196/2500 [10:13<1:49:22,  2.85s/row]

Evaluating rows:   8%|▊         | 197/2500 [10:16<1:47:34,  2.80s/row]

Evaluating rows:   8%|▊         | 198/2500 [10:18<1:45:44,  2.76s/row]

Evaluating rows:   8%|▊         | 199/2500 [10:21<1:45:04,  2.74s/row]

Batch saved (processed up to row 3699).

Evaluating rows:   8%|▊         | 200/2500 [10:25<1:53:25,  2.96s/row]

Evaluating rows:   8%|▊         | 201/2500 [10:27<1:49:44,  2.86s/row]

Evaluating rows:   8%|▊         | 202/2500 [10:30<1:47:28,  2.81s/row]

Evaluating rows:   8%|▊         | 203/2500 [10:33<1:48:09,  2.83s/row]

Evaluating rows:   8%|▊         | 204/2500 [10:36<1:48:23,  2.83s/row]

Evaluating rows:   8%|▊         | 205/2500 [10:38<1:46:00,  2.77s/row]

Evaluating rows:   8%|▊         | 206/2500 [10:41<1:44:56,  2.74s/row]

Evaluating rows:   8%|▊         | 207/2500 [10:44<1:53:39,  2.97s/row]

Evaluating rows:   8%|▊         | 208/2500 [10:48<2:04:18,  3.25s/row]

Evaluating rows:   8%|▊         | 209/2500 [10:51<1:56:58,  3.06s/row]

Evaluating rows:   8%|▊         | 210/2500 [10:54<1:52:16,  2.94s/row]

Evaluating rows:   8%|▊         | 211/2500 [10:57<2:00:24,  3.16s/row]

Evaluating rows:   8%|▊         | 212/2500 [11:03<2:32:22,  4.00s/row]

Evaluating rows:   9%|▊         | 213/2500 [11:06<2:16:43,  3.59s/row]

Evaluating rows:   9%|▊         | 214/2500 [11:09<2:06:47,  3.33s/row]

Evaluating rows:   9%|▊         | 215/2500 [11:11<1:58:19,  3.11s/row]

Evaluating rows:   9%|▊         | 216/2500 [11:15<2:07:08,  3.34s/row]

Evaluating rows:   9%|▊         | 217/2500 [11:18<1:59:52,  3.15s/row]

Evaluating rows:   9%|▊         | 218/2500 [11:22<2:13:19,  3.51s/row]

Evaluating rows:   9%|▉         | 219/2500 [11:25<2:03:38,  3.25s/row]

Evaluating rows:   9%|▉         | 220/2500 [11:27<1:56:42,  3.07s/row]

Evaluating rows:   9%|▉         | 221/2500 [11:30<1:53:22,  2.98s/row]

Evaluating rows:   9%|▉         | 222/2500 [11:33<1:49:41,  2.89s/row]

Evaluating rows:   9%|▉         | 223/2500 [11:36<1:47:32,  2.83s/row]

Evaluating rows:   9%|▉         | 224/2500 [11:39<1:54:11,  3.01s/row]

Batch saved (processed up to row 3724).

Evaluating rows:   9%|▉         | 225/2500 [11:42<1:59:17,  3.15s/row]

Evaluating rows:   9%|▉         | 226/2500 [11:45<1:53:26,  2.99s/row]

Evaluating rows:   9%|▉         | 227/2500 [11:48<1:49:30,  2.89s/row]

Evaluating rows:   9%|▉         | 228/2500 [11:54<2:23:58,  3.80s/row]

Evaluating rows:   9%|▉         | 229/2500 [11:56<2:12:24,  3.50s/row]

Evaluating rows:   9%|▉         | 230/2500 [11:59<2:02:57,  3.25s/row]

Evaluating rows:   9%|▉         | 231/2500 [12:02<1:57:42,  3.11s/row]

Evaluating rows:   9%|▉         | 232/2500 [12:05<1:56:34,  3.08s/row]

Evaluating rows:   9%|▉         | 233/2500 [12:08<1:52:01,  2.97s/row]

Evaluating rows:   9%|▉         | 234/2500 [12:10<1:48:45,  2.88s/row]

Evaluating rows:   9%|▉         | 235/2500 [12:13<1:45:38,  2.80s/row]

Evaluating rows:   9%|▉         | 236/2500 [12:16<1:45:47,  2.80s/row]

Evaluating rows:   9%|▉         | 237/2500 [12:20<1:56:36,  3.09s/row]

Evaluating rows:  10%|▉         | 238/2500 [12:22<1:53:35,  3.01s/row]

Evaluating rows:  10%|▉         | 239/2500 [12:25<1:49:46,  2.91s/row]

Evaluating rows:  10%|▉         | 240/2500 [12:28<1:46:20,  2.82s/row]

Evaluating rows:  10%|▉         | 241/2500 [12:31<1:53:21,  3.01s/row]

Evaluating rows:  10%|▉         | 242/2500 [12:34<1:49:10,  2.90s/row]

Evaluating rows:  10%|▉         | 243/2500 [12:37<1:47:40,  2.86s/row]

Evaluating rows:  10%|▉         | 244/2500 [12:39<1:45:27,  2.80s/row]

Evaluating rows:  10%|▉         | 245/2500 [12:42<1:44:08,  2.77s/row]

Evaluating rows:  10%|▉         | 246/2500 [12:45<1:43:42,  2.76s/row]

Evaluating rows:  10%|▉         | 247/2500 [12:47<1:43:09,  2.75s/row]

Evaluating rows:  10%|▉         | 248/2500 [12:50<1:42:08,  2.72s/row]

Evaluating rows:  10%|▉         | 249/2500 [12:53<1:41:27,  2.70s/row]

Batch saved (processed up to row 3749).

Evaluating rows:  10%|█         | 250/2500 [12:57<1:59:58,  3.20s/row]

Evaluating rows:  10%|█         | 251/2500 [13:00<1:54:28,  3.05s/row]

Evaluating rows:  10%|█         | 252/2500 [13:02<1:49:09,  2.91s/row]

Evaluating rows:  10%|█         | 253/2500 [13:05<1:45:53,  2.83s/row]

Evaluating rows:  10%|█         | 254/2500 [13:08<1:45:39,  2.82s/row]

Evaluating rows:  10%|█         | 255/2500 [13:10<1:44:40,  2.80s/row]

Evaluating rows:  10%|█         | 256/2500 [13:13<1:44:03,  2.78s/row]

Evaluating rows:  10%|█         | 257/2500 [13:16<1:42:19,  2.74s/row]

Evaluating rows:  10%|█         | 258/2500 [13:19<1:43:20,  2.77s/row]

Evaluating rows:  10%|█         | 259/2500 [13:21<1:41:55,  2.73s/row]

Evaluating rows:  10%|█         | 260/2500 [13:24<1:41:25,  2.72s/row]

Evaluating rows:  10%|█         | 261/2500 [13:27<1:40:28,  2.69s/row]

Evaluating rows:  10%|█         | 262/2500 [13:29<1:39:55,  2.68s/row]

Evaluating rows:  11%|█         | 263/2500 [13:33<1:48:37,  2.91s/row]

Evaluating rows:  11%|█         | 264/2500 [13:35<1:46:27,  2.86s/row]

Evaluating rows:  11%|█         | 265/2500 [13:39<1:48:13,  2.91s/row]

Evaluating rows:  11%|█         | 266/2500 [13:41<1:46:02,  2.85s/row]

Evaluating rows:  11%|█         | 267/2500 [13:44<1:44:13,  2.80s/row]

Evaluating rows:  11%|█         | 268/2500 [13:47<1:42:25,  2.75s/row]

Evaluating rows:  11%|█         | 269/2500 [13:49<1:41:03,  2.72s/row]

Evaluating rows:  11%|█         | 270/2500 [13:52<1:40:13,  2.70s/row]

Evaluating rows:  11%|█         | 271/2500 [13:55<1:40:36,  2.71s/row]

Evaluating rows:  11%|█         | 272/2500 [13:57<1:39:59,  2.69s/row]

Evaluating rows:  11%|█         | 273/2500 [14:00<1:40:01,  2.69s/row]

Evaluating rows:  11%|█         | 274/2500 [14:03<1:40:47,  2.72s/row]

Batch saved (processed up to row 3774).

Evaluating rows:  11%|█         | 275/2500 [14:07<1:54:12,  3.08s/row]

Evaluating rows:  11%|█         | 276/2500 [14:09<1:50:01,  2.97s/row]

Evaluating rows:  11%|█         | 277/2500 [14:12<1:47:51,  2.91s/row]

Evaluating rows:  11%|█         | 278/2500 [14:15<1:45:05,  2.84s/row]

Evaluating rows:  11%|█         | 279/2500 [14:17<1:43:47,  2.80s/row]

Evaluating rows:  11%|█         | 280/2500 [14:20<1:43:03,  2.79s/row]

Evaluating rows:  11%|█         | 281/2500 [14:23<1:46:31,  2.88s/row]

Evaluating rows:  11%|█▏        | 282/2500 [14:26<1:43:56,  2.81s/row]

Evaluating rows:  11%|█▏        | 283/2500 [14:29<1:42:21,  2.77s/row]

Evaluating rows:  11%|█▏        | 284/2500 [14:32<1:44:13,  2.82s/row]

Evaluating rows:  11%|█▏        | 285/2500 [14:34<1:42:47,  2.78s/row]

Evaluating rows:  11%|█▏        | 286/2500 [14:37<1:40:45,  2.73s/row]

Evaluating rows:  11%|█▏        | 287/2500 [14:41<1:52:11,  3.04s/row]

Evaluating rows:  12%|█▏        | 288/2500 [14:43<1:48:59,  2.96s/row]

Evaluating rows:  12%|█▏        | 289/2500 [14:46<1:47:45,  2.92s/row]

Evaluating rows:  12%|█▏        | 290/2500 [14:49<1:46:00,  2.88s/row]

Evaluating rows:  12%|█▏        | 291/2500 [14:52<1:43:24,  2.81s/row]

Evaluating rows:  12%|█▏        | 292/2500 [14:54<1:42:19,  2.78s/row]

Evaluating rows:  12%|█▏        | 293/2500 [14:57<1:42:10,  2.78s/row]

Evaluating rows:  12%|█▏        | 294/2500 [15:00<1:40:39,  2.74s/row]

Evaluating rows:  12%|█▏        | 295/2500 [15:03<1:40:52,  2.75s/row]

Evaluating rows:  12%|█▏        | 296/2500 [15:05<1:40:26,  2.73s/row]

Evaluating rows:  12%|█▏        | 297/2500 [15:08<1:39:47,  2.72s/row]

Evaluating rows:  12%|█▏        | 298/2500 [15:11<1:43:23,  2.82s/row]

Evaluating rows:  12%|█▏        | 299/2500 [15:14<1:42:58,  2.81s/row]

Batch saved (processed up to row 3799).

Evaluating rows:  12%|█▏        | 300/2500 [15:17<1:51:22,  3.04s/row]

Evaluating rows:  12%|█▏        | 301/2500 [15:20<1:46:55,  2.92s/row]

Evaluating rows:  12%|█▏        | 302/2500 [15:23<1:45:24,  2.88s/row]

Evaluating rows:  12%|█▏        | 303/2500 [15:26<1:44:10,  2.85s/row]

Evaluating rows:  12%|█▏        | 304/2500 [15:28<1:41:35,  2.78s/row]

Evaluating rows:  12%|█▏        | 305/2500 [15:31<1:40:07,  2.74s/row]

Evaluating rows:  12%|█▏        | 306/2500 [15:34<1:48:40,  2.97s/row]

Evaluating rows:  12%|█▏        | 307/2500 [15:38<1:52:03,  3.07s/row]

Evaluating rows:  12%|█▏        | 308/2500 [15:40<1:47:25,  2.94s/row]

Evaluating rows:  12%|█▏        | 309/2500 [15:43<1:45:08,  2.88s/row]

Evaluating rows:  12%|█▏        | 310/2500 [15:47<1:51:56,  3.07s/row]

Evaluating rows:  12%|█▏        | 311/2500 [15:49<1:47:09,  2.94s/row]

Evaluating rows:  12%|█▏        | 312/2500 [15:52<1:45:07,  2.88s/row]

Evaluating rows:  13%|█▎        | 313/2500 [15:55<1:42:19,  2.81s/row]

Evaluating rows:  13%|█▎        | 314/2500 [15:57<1:41:12,  2.78s/row]

Evaluating rows:  13%|█▎        | 315/2500 [16:00<1:40:41,  2.76s/row]

Evaluating rows:  13%|█▎        | 316/2500 [16:03<1:38:32,  2.71s/row]

Evaluating rows:  13%|█▎        | 317/2500 [16:05<1:38:12,  2.70s/row]

Evaluating rows:  13%|█▎        | 318/2500 [16:08<1:38:47,  2.72s/row]

Evaluating rows:  13%|█▎        | 319/2500 [16:11<1:40:48,  2.77s/row]

Evaluating rows:  13%|█▎        | 320/2500 [16:14<1:40:32,  2.77s/row]

Evaluating rows:  13%|█▎        | 321/2500 [16:17<1:49:30,  3.02s/row]

Evaluating rows:  13%|█▎        | 322/2500 [16:20<1:46:08,  2.92s/row]

Evaluating rows:  13%|█▎        | 323/2500 [16:23<1:43:20,  2.85s/row]

Evaluating rows:  13%|█▎        | 324/2500 [16:25<1:40:53,  2.78s/row]

Batch saved (processed up to row 3824).

Evaluating rows:  13%|█▎        | 325/2500 [16:29<1:49:25,  3.02s/row]

Evaluating rows:  13%|█▎        | 326/2500 [16:32<1:49:24,  3.02s/row]

Evaluating rows:  13%|█▎        | 327/2500 [16:35<1:45:34,  2.92s/row]

Evaluating rows:  13%|█▎        | 328/2500 [16:37<1:44:19,  2.88s/row]

Evaluating rows:  13%|█▎        | 329/2500 [16:40<1:42:18,  2.83s/row]

Evaluating rows:  13%|█▎        | 330/2500 [16:43<1:40:36,  2.78s/row]

Evaluating rows:  13%|█▎        | 331/2500 [16:45<1:39:58,  2.77s/row]

Evaluating rows:  13%|█▎        | 332/2500 [16:48<1:38:46,  2.73s/row]

Evaluating rows:  13%|█▎        | 333/2500 [16:51<1:45:17,  2.92s/row]

Evaluating rows:  13%|█▎        | 334/2500 [16:54<1:42:07,  2.83s/row]

Evaluating rows:  13%|█▎        | 335/2500 [16:57<1:40:18,  2.78s/row]

Evaluating rows:  13%|█▎        | 336/2500 [17:00<1:40:11,  2.78s/row]

Evaluating rows:  13%|█▎        | 337/2500 [17:02<1:38:54,  2.74s/row]

Evaluating rows:  14%|█▎        | 338/2500 [17:05<1:38:32,  2.73s/row]

Evaluating rows:  14%|█▎        | 339/2500 [17:08<1:37:39,  2.71s/row]

Evaluating rows:  14%|█▎        | 340/2500 [17:10<1:36:52,  2.69s/row]

Evaluating rows:  14%|█▎        | 341/2500 [17:13<1:40:43,  2.80s/row]

Evaluating rows:  14%|█▎        | 342/2500 [17:16<1:38:52,  2.75s/row]

Evaluating rows:  14%|█▎        | 343/2500 [17:19<1:37:40,  2.72s/row]

Evaluating rows:  14%|█▍        | 344/2500 [17:21<1:36:51,  2.70s/row]

Evaluating rows:  14%|█▍        | 345/2500 [17:24<1:36:27,  2.69s/row]

Evaluating rows:  14%|█▍        | 346/2500 [17:27<1:36:31,  2.69s/row]

Evaluating rows:  14%|█▍        | 347/2500 [17:29<1:37:15,  2.71s/row]

Evaluating rows:  14%|█▍        | 348/2500 [17:32<1:36:41,  2.70s/row]

Evaluating rows:  14%|█▍        | 349/2500 [17:35<1:36:15,  2.69s/row]

Batch saved (processed up to row 3849).

Evaluating rows:  14%|█▍        | 350/2500 [17:38<1:45:12,  2.94s/row]

Evaluating rows:  14%|█▍        | 351/2500 [17:42<1:58:41,  3.31s/row]

Evaluating rows:  14%|█▍        | 352/2500 [17:45<1:54:48,  3.21s/row]

Evaluating rows:  14%|█▍        | 353/2500 [17:48<1:49:48,  3.07s/row]

Evaluating rows:  14%|█▍        | 354/2500 [17:51<1:44:45,  2.93s/row]

Evaluating rows:  14%|█▍        | 355/2500 [17:53<1:42:01,  2.85s/row]

Evaluating rows:  14%|█▍        | 356/2500 [17:56<1:40:14,  2.81s/row]

Evaluating rows:  14%|█▍        | 357/2500 [17:59<1:40:41,  2.82s/row]

Evaluating rows:  14%|█▍        | 358/2500 [18:02<1:39:54,  2.80s/row]

Evaluating rows:  14%|█▍        | 359/2500 [18:04<1:38:21,  2.76s/row]

Evaluating rows:  14%|█▍        | 360/2500 [18:07<1:39:29,  2.79s/row]

Evaluating rows:  14%|█▍        | 361/2500 [18:11<1:46:30,  2.99s/row]

Evaluating rows:  14%|█▍        | 362/2500 [18:13<1:42:39,  2.88s/row]

Evaluating rows:  15%|█▍        | 363/2500 [18:16<1:39:57,  2.81s/row]

Evaluating rows:  15%|█▍        | 364/2500 [18:18<1:38:01,  2.75s/row]

Evaluating rows:  15%|█▍        | 365/2500 [18:21<1:37:03,  2.73s/row]

Evaluating rows:  15%|█▍        | 366/2500 [18:25<1:46:14,  2.99s/row]

Evaluating rows:  15%|█▍        | 367/2500 [18:27<1:42:41,  2.89s/row]

Evaluating rows:  15%|█▍        | 368/2500 [18:30<1:39:59,  2.81s/row]

Evaluating rows:  15%|█▍        | 369/2500 [18:33<1:38:16,  2.77s/row]

Evaluating rows:  15%|█▍        | 370/2500 [18:35<1:36:58,  2.73s/row]

Evaluating rows:  15%|█▍        | 371/2500 [18:38<1:36:12,  2.71s/row]

Evaluating rows:  15%|█▍        | 372/2500 [18:41<1:35:50,  2.70s/row]

Evaluating rows:  15%|█▍        | 373/2500 [18:44<1:43:41,  2.93s/row]

Evaluating rows:  15%|█▍        | 374/2500 [18:47<1:41:14,  2.86s/row]

Batch saved (processed up to row 3874).

Evaluating rows:  15%|█▌        | 375/2500 [18:51<1:56:54,  3.30s/row]

Evaluating rows:  15%|█▌        | 376/2500 [18:54<1:50:17,  3.12s/row]

Evaluating rows:  15%|█▌        | 377/2500 [18:56<1:45:15,  2.97s/row]

Evaluating rows:  15%|█▌        | 378/2500 [18:59<1:42:59,  2.91s/row]

Evaluating rows:  15%|█▌        | 379/2500 [19:02<1:40:36,  2.85s/row]

Evaluating rows:  15%|█▌        | 380/2500 [19:05<1:41:46,  2.88s/row]

Evaluating rows:  15%|█▌        | 381/2500 [19:08<1:40:47,  2.85s/row]

Evaluating rows:  15%|█▌        | 382/2500 [19:12<1:52:05,  3.18s/row]

Evaluating rows:  15%|█▌        | 383/2500 [19:14<1:46:24,  3.02s/row]

Evaluating rows:  15%|█▌        | 384/2500 [19:17<1:43:09,  2.93s/row]

Evaluating rows:  15%|█▌        | 385/2500 [19:20<1:40:38,  2.86s/row]

Evaluating rows:  15%|█▌        | 386/2500 [19:22<1:40:09,  2.84s/row]

Evaluating rows:  15%|█▌        | 387/2500 [19:25<1:37:57,  2.78s/row]

Evaluating rows:  16%|█▌        | 388/2500 [19:28<1:37:28,  2.77s/row]

Evaluating rows:  16%|█▌        | 389/2500 [19:30<1:35:48,  2.72s/row]

Evaluating rows:  16%|█▌        | 390/2500 [19:33<1:34:47,  2.70s/row]

Evaluating rows:  16%|█▌        | 391/2500 [19:36<1:36:58,  2.76s/row]

Evaluating rows:  16%|█▌        | 392/2500 [19:39<1:36:42,  2.75s/row]

Evaluating rows:  16%|█▌        | 393/2500 [19:42<1:36:42,  2.75s/row]

Evaluating rows:  16%|█▌        | 394/2500 [19:44<1:39:01,  2.82s/row]

Evaluating rows:  16%|█▌        | 395/2500 [19:47<1:37:57,  2.79s/row]

Evaluating rows:  16%|█▌        | 396/2500 [19:50<1:35:59,  2.74s/row]

Evaluating rows:  16%|█▌        | 397/2500 [19:52<1:34:34,  2.70s/row]

Evaluating rows:  16%|█▌        | 398/2500 [19:55<1:34:26,  2.70s/row]

Evaluating rows:  16%|█▌        | 399/2500 [19:58<1:33:32,  2.67s/row]

Batch saved (processed up to row 3899).

Evaluating rows:  16%|█▌        | 400/2500 [20:01<1:43:42,  2.96s/row]

Evaluating rows:  16%|█▌        | 401/2500 [20:04<1:43:37,  2.96s/row]

Evaluating rows:  16%|█▌        | 402/2500 [20:07<1:40:02,  2.86s/row]

Evaluating rows:  16%|█▌        | 403/2500 [20:10<1:43:55,  2.97s/row]

Evaluating rows:  16%|█▌        | 404/2500 [20:13<1:41:48,  2.91s/row]

Evaluating rows:  16%|█▌        | 405/2500 [20:17<1:49:10,  3.13s/row]

Evaluating rows:  16%|█▌        | 406/2500 [20:19<1:44:19,  2.99s/row]

Evaluating rows:  16%|█▋        | 407/2500 [20:23<1:46:52,  3.06s/row]

Evaluating rows:  16%|█▋        | 408/2500 [20:25<1:43:32,  2.97s/row]

Evaluating rows:  16%|█▋        | 409/2500 [20:28<1:41:50,  2.92s/row]

Evaluating rows:  16%|█▋        | 410/2500 [20:31<1:39:54,  2.87s/row]

Evaluating rows:  16%|█▋        | 411/2500 [20:34<1:39:59,  2.87s/row]

Evaluating rows:  16%|█▋        | 412/2500 [20:36<1:37:24,  2.80s/row]

Evaluating rows:  17%|█▋        | 413/2500 [20:39<1:36:27,  2.77s/row]

Evaluating rows:  17%|█▋        | 414/2500 [20:42<1:35:00,  2.73s/row]

Evaluating rows:  17%|█▋        | 415/2500 [20:44<1:35:45,  2.76s/row]

Evaluating rows:  17%|█▋        | 416/2500 [20:47<1:36:51,  2.79s/row]

Evaluating rows:  17%|█▋        | 417/2500 [20:50<1:35:01,  2.74s/row]

Evaluating rows:  17%|█▋        | 418/2500 [20:53<1:35:21,  2.75s/row]

Evaluating rows:  17%|█▋        | 419/2500 [20:55<1:35:22,  2.75s/row]

Evaluating rows:  17%|█▋        | 420/2500 [20:58<1:34:47,  2.73s/row]

Evaluating rows:  17%|█▋        | 421/2500 [21:01<1:34:01,  2.71s/row]

Evaluating rows:  17%|█▋        | 422/2500 [21:04<1:33:26,  2.70s/row]

Evaluating rows:  17%|█▋        | 423/2500 [21:06<1:32:40,  2.68s/row]

Evaluating rows:  17%|█▋        | 424/2500 [21:09<1:31:54,  2.66s/row]

Batch saved (processed up to row 3924).

Evaluating rows:  17%|█▋        | 425/2500 [21:12<1:39:50,  2.89s/row]

Evaluating rows:  17%|█▋        | 426/2500 [21:15<1:37:23,  2.82s/row]

Evaluating rows:  17%|█▋        | 427/2500 [21:18<1:42:50,  2.98s/row]

Evaluating rows:  17%|█▋        | 428/2500 [21:22<1:48:02,  3.13s/row]

Evaluating rows:  17%|█▋        | 429/2500 [21:26<1:55:51,  3.36s/row]

Evaluating rows:  17%|█▋        | 430/2500 [21:28<1:48:43,  3.15s/row]

Evaluating rows:  17%|█▋        | 431/2500 [21:31<1:44:31,  3.03s/row]

Evaluating rows:  17%|█▋        | 432/2500 [21:34<1:40:45,  2.92s/row]

Evaluating rows:  17%|█▋        | 433/2500 [21:37<1:47:44,  3.13s/row]

Evaluating rows:  17%|█▋        | 434/2500 [21:40<1:42:26,  2.97s/row]

Evaluating rows:  17%|█▋        | 435/2500 [21:43<1:39:51,  2.90s/row]

Evaluating rows:  17%|█▋        | 436/2500 [21:45<1:38:31,  2.86s/row]

Evaluating rows:  17%|█▋        | 437/2500 [21:49<1:42:52,  2.99s/row]

Evaluating rows:  18%|█▊        | 438/2500 [21:51<1:40:16,  2.92s/row]

Evaluating rows:  18%|█▊        | 439/2500 [21:55<1:46:05,  3.09s/row]

Evaluating rows:  18%|█▊        | 440/2500 [21:58<1:42:36,  2.99s/row]

Evaluating rows:  18%|█▊        | 441/2500 [22:00<1:40:04,  2.92s/row]

Evaluating rows:  18%|█▊        | 442/2500 [22:03<1:41:06,  2.95s/row]

Evaluating rows:  18%|█▊        | 443/2500 [22:06<1:37:42,  2.85s/row]

Evaluating rows:  18%|█▊        | 444/2500 [22:09<1:35:32,  2.79s/row]

Evaluating rows:  18%|█▊        | 445/2500 [22:11<1:34:06,  2.75s/row]

Evaluating rows:  18%|█▊        | 446/2500 [22:14<1:32:52,  2.71s/row]

Evaluating rows:  18%|█▊        | 447/2500 [22:17<1:32:57,  2.72s/row]

Evaluating rows:  18%|█▊        | 448/2500 [22:19<1:32:31,  2.71s/row]

Evaluating rows:  18%|█▊        | 449/2500 [22:22<1:32:40,  2.71s/row]

Batch saved (processed up to row 3949).

Evaluating rows:  18%|█▊        | 450/2500 [22:26<1:40:04,  2.93s/row]

Evaluating rows:  18%|█▊        | 451/2500 [22:28<1:38:06,  2.87s/row]

Evaluating rows:  18%|█▊        | 452/2500 [22:31<1:36:22,  2.82s/row]

Evaluating rows:  18%|█▊        | 453/2500 [22:34<1:34:28,  2.77s/row]

Evaluating rows:  18%|█▊        | 454/2500 [22:36<1:34:05,  2.76s/row]

Evaluating rows:  18%|█▊        | 455/2500 [22:39<1:33:18,  2.74s/row]

Evaluating rows:  18%|█▊        | 456/2500 [22:42<1:33:11,  2.74s/row]

Evaluating rows:  18%|█▊        | 457/2500 [22:45<1:33:04,  2.73s/row]

Evaluating rows:  18%|█▊        | 458/2500 [22:47<1:32:40,  2.72s/row]

Evaluating rows:  18%|█▊        | 459/2500 [22:50<1:33:07,  2.74s/row]

Evaluating rows:  18%|█▊        | 460/2500 [22:53<1:32:12,  2.71s/row]

Evaluating rows:  18%|█▊        | 461/2500 [22:55<1:32:57,  2.74s/row]

Evaluating rows:  18%|█▊        | 462/2500 [22:58<1:32:03,  2.71s/row]

Evaluating rows:  19%|█▊        | 463/2500 [23:01<1:32:33,  2.73s/row]

Evaluating rows:  19%|█▊        | 464/2500 [23:04<1:41:22,  2.99s/row]

Evaluating rows:  19%|█▊        | 465/2500 [23:07<1:37:56,  2.89s/row]

Evaluating rows:  19%|█▊        | 466/2500 [23:10<1:35:29,  2.82s/row]

Evaluating rows:  19%|█▊        | 467/2500 [23:12<1:33:18,  2.75s/row]

Evaluating rows:  19%|█▊        | 468/2500 [23:15<1:31:37,  2.71s/row]

Evaluating rows:  19%|█▉        | 469/2500 [23:18<1:30:54,  2.69s/row]

Evaluating rows:  19%|█▉        | 470/2500 [23:20<1:31:18,  2.70s/row]

Evaluating rows:  19%|█▉        | 471/2500 [23:23<1:29:47,  2.66s/row]

Evaluating rows:  19%|█▉        | 472/2500 [23:26<1:30:16,  2.67s/row]

Evaluating rows:  19%|█▉        | 473/2500 [23:29<1:37:52,  2.90s/row]

Evaluating rows:  19%|█▉        | 474/2500 [23:32<1:35:55,  2.84s/row]

Batch saved (processed up to row 3974).

Evaluating rows:  19%|█▉        | 475/2500 [23:35<1:42:03,  3.02s/row]

Evaluating rows:  19%|█▉        | 476/2500 [23:38<1:38:08,  2.91s/row]

Evaluating rows:  19%|█▉        | 477/2500 [23:40<1:35:31,  2.83s/row]

Evaluating rows:  19%|█▉        | 478/2500 [23:43<1:33:11,  2.77s/row]

Evaluating rows:  19%|█▉        | 479/2500 [23:46<1:31:22,  2.71s/row]

Evaluating rows:  19%|█▉        | 480/2500 [23:48<1:31:20,  2.71s/row]

Evaluating rows:  19%|█▉        | 481/2500 [23:51<1:30:10,  2.68s/row]

Evaluating rows:  19%|█▉        | 482/2500 [23:54<1:30:07,  2.68s/row]

Evaluating rows:  19%|█▉        | 483/2500 [23:57<1:32:51,  2.76s/row]

Evaluating rows:  19%|█▉        | 484/2500 [24:01<1:45:10,  3.13s/row]

Evaluating rows:  19%|█▉        | 485/2500 [24:03<1:40:06,  2.98s/row]

Evaluating rows:  19%|█▉        | 486/2500 [24:06<1:36:33,  2.88s/row]

Evaluating rows:  19%|█▉        | 487/2500 [24:09<1:40:28,  2.99s/row]

Evaluating rows:  20%|█▉        | 488/2500 [24:12<1:37:31,  2.91s/row]

Evaluating rows:  20%|█▉        | 489/2500 [24:15<1:37:33,  2.91s/row]

Evaluating rows:  20%|█▉        | 490/2500 [24:17<1:34:29,  2.82s/row]

Evaluating rows:  20%|█▉        | 491/2500 [24:20<1:33:03,  2.78s/row]

Evaluating rows:  20%|█▉        | 492/2500 [24:23<1:31:34,  2.74s/row]

Evaluating rows:  20%|█▉        | 493/2500 [24:25<1:30:26,  2.70s/row]

Evaluating rows:  20%|█▉        | 494/2500 [24:28<1:30:46,  2.71s/row]

Evaluating rows:  20%|█▉        | 495/2500 [24:31<1:31:33,  2.74s/row]

Evaluating rows:  20%|█▉        | 496/2500 [24:34<1:31:19,  2.73s/row]

Evaluating rows:  20%|█▉        | 497/2500 [24:36<1:32:03,  2.76s/row]

Evaluating rows:  20%|█▉        | 498/2500 [24:40<1:41:43,  3.05s/row]

Evaluating rows:  20%|█▉        | 499/2500 [24:43<1:38:43,  2.96s/row]

Batch saved (processed up to row 3999).

Evaluating rows:  20%|██        | 500/2500 [24:47<1:45:23,  3.16s/row]

Evaluating rows:  20%|██        | 501/2500 [24:49<1:40:03,  3.00s/row]

Evaluating rows:  20%|██        | 502/2500 [24:53<1:53:00,  3.39s/row]

Evaluating rows:  20%|██        | 503/2500 [24:56<1:45:16,  3.16s/row]

Evaluating rows:  20%|██        | 504/2500 [24:59<1:41:05,  3.04s/row]

Evaluating rows:  20%|██        | 505/2500 [25:02<1:38:42,  2.97s/row]

Evaluating rows:  20%|██        | 506/2500 [25:04<1:36:56,  2.92s/row]

Evaluating rows:  20%|██        | 507/2500 [25:07<1:34:35,  2.85s/row]

Evaluating rows:  20%|██        | 508/2500 [25:10<1:32:39,  2.79s/row]

Evaluating rows:  20%|██        | 509/2500 [25:12<1:30:26,  2.73s/row]

Evaluating rows:  20%|██        | 510/2500 [25:15<1:29:08,  2.69s/row]

Evaluating rows:  20%|██        | 511/2500 [25:18<1:30:05,  2.72s/row]

Evaluating rows:  20%|██        | 512/2500 [25:20<1:29:19,  2.70s/row]

Evaluating rows:  21%|██        | 513/2500 [25:23<1:32:27,  2.79s/row]

Evaluating rows:  21%|██        | 514/2500 [25:27<1:37:36,  2.95s/row]

Evaluating rows:  21%|██        | 515/2500 [25:29<1:34:14,  2.85s/row]

Evaluating rows:  21%|██        | 516/2500 [25:32<1:32:34,  2.80s/row]

Evaluating rows:  21%|██        | 517/2500 [25:35<1:31:02,  2.75s/row]

Evaluating rows:  21%|██        | 518/2500 [25:38<1:32:17,  2.79s/row]

Evaluating rows:  21%|██        | 519/2500 [25:40<1:32:54,  2.81s/row]

Evaluating rows:  21%|██        | 520/2500 [25:43<1:32:30,  2.80s/row]

Evaluating rows:  21%|██        | 521/2500 [25:46<1:31:55,  2.79s/row]

Evaluating rows:  21%|██        | 522/2500 [25:49<1:30:51,  2.76s/row]

Evaluating rows:  21%|██        | 523/2500 [25:51<1:29:35,  2.72s/row]

Evaluating rows:  21%|██        | 524/2500 [25:54<1:29:09,  2.71s/row]

Batch saved (processed up to row 4024).

Evaluating rows:  21%|██        | 525/2500 [25:58<1:38:25,  2.99s/row]

Evaluating rows:  21%|██        | 526/2500 [26:01<1:43:56,  3.16s/row]

Evaluating rows:  21%|██        | 527/2500 [26:04<1:38:47,  3.00s/row]

Evaluating rows:  21%|██        | 528/2500 [26:06<1:35:41,  2.91s/row]

Evaluating rows:  21%|██        | 529/2500 [26:09<1:34:45,  2.88s/row]

Evaluating rows:  21%|██        | 530/2500 [26:12<1:33:14,  2.84s/row]

Evaluating rows:  21%|██        | 531/2500 [26:15<1:32:01,  2.80s/row]

Evaluating rows:  21%|██▏       | 532/2500 [26:17<1:30:34,  2.76s/row]

Evaluating rows:  21%|██▏       | 533/2500 [26:20<1:31:38,  2.80s/row]

Evaluating rows:  21%|██▏       | 534/2500 [26:23<1:29:27,  2.73s/row]

Evaluating rows:  21%|██▏       | 535/2500 [26:25<1:28:14,  2.69s/row]

Evaluating rows:  21%|██▏       | 536/2500 [26:28<1:27:33,  2.68s/row]

Evaluating rows:  21%|██▏       | 537/2500 [26:31<1:27:41,  2.68s/row]

Evaluating rows:  22%|██▏       | 538/2500 [26:34<1:35:07,  2.91s/row]

Evaluating rows:  22%|██▏       | 539/2500 [26:37<1:33:20,  2.86s/row]

Evaluating rows:  22%|██▏       | 540/2500 [26:40<1:31:48,  2.81s/row]

Evaluating rows:  22%|██▏       | 541/2500 [26:42<1:30:55,  2.78s/row]

Evaluating rows:  22%|██▏       | 542/2500 [26:45<1:29:31,  2.74s/row]

Evaluating rows:  22%|██▏       | 543/2500 [26:48<1:29:17,  2.74s/row]

Evaluating rows:  22%|██▏       | 544/2500 [26:50<1:28:44,  2.72s/row]

Evaluating rows:  22%|██▏       | 545/2500 [26:53<1:29:40,  2.75s/row]

Evaluating rows:  22%|██▏       | 546/2500 [26:56<1:28:15,  2.71s/row]

Evaluating rows:  22%|██▏       | 547/2500 [26:59<1:27:34,  2.69s/row]

Evaluating rows:  22%|██▏       | 548/2500 [27:01<1:27:47,  2.70s/row]

Evaluating rows:  22%|██▏       | 549/2500 [27:04<1:27:05,  2.68s/row]

Batch saved (processed up to row 4049).

Evaluating rows:  22%|██▏       | 550/2500 [27:08<1:38:49,  3.04s/row]

Evaluating rows:  22%|██▏       | 551/2500 [27:10<1:35:04,  2.93s/row]

Evaluating rows:  22%|██▏       | 552/2500 [27:13<1:31:50,  2.83s/row]

Evaluating rows:  22%|██▏       | 553/2500 [27:16<1:30:39,  2.79s/row]

Evaluating rows:  22%|██▏       | 554/2500 [27:19<1:32:12,  2.84s/row]

Evaluating rows:  22%|██▏       | 555/2500 [27:21<1:31:16,  2.82s/row]

Evaluating rows:  22%|██▏       | 556/2500 [27:24<1:30:31,  2.79s/row]

Evaluating rows:  22%|██▏       | 557/2500 [27:27<1:29:05,  2.75s/row]

Evaluating rows:  22%|██▏       | 558/2500 [27:29<1:27:37,  2.71s/row]

Evaluating rows:  22%|██▏       | 559/2500 [27:32<1:27:28,  2.70s/row]

Evaluating rows:  22%|██▏       | 560/2500 [27:35<1:26:44,  2.68s/row]

Evaluating rows:  22%|██▏       | 561/2500 [27:37<1:26:38,  2.68s/row]

Evaluating rows:  22%|██▏       | 562/2500 [27:40<1:26:22,  2.67s/row]

Evaluating rows:  23%|██▎       | 563/2500 [27:43<1:27:49,  2.72s/row]

Evaluating rows:  23%|██▎       | 564/2500 [27:46<1:27:49,  2.72s/row]

Evaluating rows:  23%|██▎       | 565/2500 [27:48<1:28:13,  2.74s/row]

Evaluating rows:  23%|██▎       | 566/2500 [27:51<1:27:14,  2.71s/row]

Evaluating rows:  23%|██▎       | 567/2500 [27:54<1:26:20,  2.68s/row]

Evaluating rows:  23%|██▎       | 568/2500 [27:56<1:26:09,  2.68s/row]

Evaluating rows:  23%|██▎       | 569/2500 [27:59<1:26:28,  2.69s/row]

Evaluating rows:  23%|██▎       | 570/2500 [28:02<1:27:30,  2.72s/row]

Evaluating rows:  23%|██▎       | 571/2500 [28:04<1:26:32,  2.69s/row]

Evaluating rows:  23%|██▎       | 572/2500 [28:07<1:25:49,  2.67s/row]

Evaluating rows:  23%|██▎       | 573/2500 [28:10<1:25:38,  2.67s/row]

Evaluating rows:  23%|██▎       | 574/2500 [28:12<1:25:57,  2.68s/row]

Batch saved (processed up to row 4074).

Evaluating rows:  23%|██▎       | 575/2500 [28:16<1:33:27,  2.91s/row]

Evaluating rows:  23%|██▎       | 576/2500 [28:19<1:31:13,  2.84s/row]

Evaluating rows:  23%|██▎       | 577/2500 [28:21<1:29:34,  2.79s/row]

Evaluating rows:  23%|██▎       | 578/2500 [28:24<1:29:50,  2.80s/row]

Evaluating rows:  23%|██▎       | 579/2500 [28:28<1:35:27,  2.98s/row]

Evaluating rows:  23%|██▎       | 580/2500 [28:30<1:33:18,  2.92s/row]

Evaluating rows:  23%|██▎       | 581/2500 [28:33<1:32:38,  2.90s/row]

Evaluating rows:  23%|██▎       | 582/2500 [28:36<1:31:11,  2.85s/row]

Evaluating rows:  23%|██▎       | 583/2500 [28:39<1:29:23,  2.80s/row]

Evaluating rows:  23%|██▎       | 584/2500 [28:41<1:27:36,  2.74s/row]

Evaluating rows:  23%|██▎       | 585/2500 [28:44<1:26:32,  2.71s/row]

Evaluating rows:  23%|██▎       | 586/2500 [28:46<1:26:04,  2.70s/row]

Evaluating rows:  23%|██▎       | 587/2500 [28:49<1:29:10,  2.80s/row]

Evaluating rows:  24%|██▎       | 588/2500 [28:53<1:34:21,  2.96s/row]

Evaluating rows:  24%|██▎       | 589/2500 [28:55<1:30:53,  2.85s/row]

Evaluating rows:  24%|██▎       | 590/2500 [28:59<1:36:17,  3.02s/row]

Evaluating rows:  24%|██▎       | 591/2500 [29:02<1:32:33,  2.91s/row]

Evaluating rows:  24%|██▎       | 592/2500 [29:04<1:30:11,  2.84s/row]

Evaluating rows:  24%|██▎       | 593/2500 [29:07<1:28:09,  2.77s/row]

Evaluating rows:  24%|██▍       | 594/2500 [29:10<1:27:42,  2.76s/row]

Evaluating rows:  24%|██▍       | 595/2500 [29:12<1:26:48,  2.73s/row]

Evaluating rows:  24%|██▍       | 596/2500 [29:15<1:27:02,  2.74s/row]

Evaluating rows:  24%|██▍       | 597/2500 [29:18<1:27:48,  2.77s/row]

Evaluating rows:  24%|██▍       | 598/2500 [29:20<1:26:29,  2.73s/row]

Evaluating rows:  24%|██▍       | 599/2500 [29:24<1:30:00,  2.84s/row]

Batch saved (processed up to row 4099).

Evaluating rows:  24%|██▍       | 600/2500 [29:27<1:39:48,  3.15s/row]

Evaluating rows:  24%|██▍       | 601/2500 [29:30<1:35:01,  3.00s/row]

Evaluating rows:  24%|██▍       | 602/2500 [29:33<1:30:52,  2.87s/row]

Evaluating rows:  24%|██▍       | 603/2500 [29:35<1:28:34,  2.80s/row]

Evaluating rows:  24%|██▍       | 604/2500 [29:38<1:26:59,  2.75s/row]

Evaluating rows:  24%|██▍       | 605/2500 [29:41<1:25:42,  2.71s/row]

Evaluating rows:  24%|██▍       | 606/2500 [29:44<1:32:53,  2.94s/row]

Evaluating rows:  24%|██▍       | 607/2500 [29:47<1:32:02,  2.92s/row]

Evaluating rows:  24%|██▍       | 608/2500 [29:50<1:29:47,  2.85s/row]

Evaluating rows:  24%|██▍       | 609/2500 [29:52<1:28:57,  2.82s/row]

Evaluating rows:  24%|██▍       | 610/2500 [29:55<1:28:21,  2.81s/row]

Evaluating rows:  24%|██▍       | 611/2500 [29:58<1:27:13,  2.77s/row]

Evaluating rows:  24%|██▍       | 612/2500 [30:00<1:26:18,  2.74s/row]

Evaluating rows:  25%|██▍       | 613/2500 [30:03<1:26:38,  2.75s/row]

Evaluating rows:  25%|██▍       | 614/2500 [30:06<1:25:48,  2.73s/row]

Evaluating rows:  25%|██▍       | 615/2500 [30:09<1:24:55,  2.70s/row]

Evaluating rows:  25%|██▍       | 616/2500 [30:11<1:24:54,  2.70s/row]

Evaluating rows:  25%|██▍       | 617/2500 [30:14<1:23:53,  2.67s/row]

Evaluating rows:  25%|██▍       | 618/2500 [30:17<1:26:29,  2.76s/row]

Evaluating rows:  25%|██▍       | 619/2500 [30:20<1:26:28,  2.76s/row]

Evaluating rows:  25%|██▍       | 620/2500 [30:22<1:27:11,  2.78s/row]

Evaluating rows:  25%|██▍       | 621/2500 [30:25<1:26:19,  2.76s/row]

Evaluating rows:  25%|██▍       | 622/2500 [30:28<1:26:21,  2.76s/row]

Evaluating rows:  25%|██▍       | 623/2500 [30:31<1:25:12,  2.72s/row]

Evaluating rows:  25%|██▍       | 624/2500 [30:33<1:24:29,  2.70s/row]

Batch saved (processed up to row 4124).

Evaluating rows:  25%|██▌       | 625/2500 [30:37<1:31:26,  2.93s/row]

Evaluating rows:  25%|██▌       | 626/2500 [30:39<1:29:33,  2.87s/row]

Evaluating rows:  25%|██▌       | 627/2500 [30:43<1:35:47,  3.07s/row]

Evaluating rows:  25%|██▌       | 628/2500 [30:46<1:35:52,  3.07s/row]

Evaluating rows:  25%|██▌       | 629/2500 [30:49<1:33:12,  2.99s/row]

Evaluating rows:  25%|██▌       | 630/2500 [30:52<1:31:00,  2.92s/row]

Evaluating rows:  25%|██▌       | 631/2500 [30:54<1:28:15,  2.83s/row]

Evaluating rows:  25%|██▌       | 632/2500 [30:57<1:27:12,  2.80s/row]

Evaluating rows:  25%|██▌       | 633/2500 [30:59<1:25:13,  2.74s/row]

Evaluating rows:  25%|██▌       | 634/2500 [31:02<1:24:33,  2.72s/row]

Evaluating rows:  25%|██▌       | 635/2500 [31:05<1:24:43,  2.73s/row]

Evaluating rows:  25%|██▌       | 636/2500 [31:08<1:24:40,  2.73s/row]

Evaluating rows:  25%|██▌       | 637/2500 [31:10<1:24:18,  2.72s/row]

Evaluating rows:  26%|██▌       | 638/2500 [31:13<1:23:14,  2.68s/row]

Evaluating rows:  26%|██▌       | 639/2500 [31:16<1:22:34,  2.66s/row]

Evaluating rows:  26%|██▌       | 640/2500 [31:18<1:24:14,  2.72s/row]

Evaluating rows:  26%|██▌       | 641/2500 [31:21<1:23:04,  2.68s/row]

Evaluating rows:  26%|██▌       | 642/2500 [31:24<1:22:33,  2.67s/row]

Evaluating rows:  26%|██▌       | 643/2500 [31:26<1:22:24,  2.66s/row]

Evaluating rows:  26%|██▌       | 644/2500 [31:29<1:22:55,  2.68s/row]

Evaluating rows:  26%|██▌       | 645/2500 [31:32<1:23:27,  2.70s/row]

Evaluating rows:  26%|██▌       | 646/2500 [31:34<1:23:16,  2.69s/row]

Evaluating rows:  26%|██▌       | 647/2500 [31:37<1:23:04,  2.69s/row]

Evaluating rows:  26%|██▌       | 648/2500 [31:40<1:24:23,  2.73s/row]

Evaluating rows:  26%|██▌       | 649/2500 [31:43<1:23:25,  2.70s/row]

Batch saved (processed up to row 4149).

Evaluating rows:  26%|██▌       | 650/2500 [31:46<1:33:38,  3.04s/row]

Evaluating rows:  26%|██▌       | 651/2500 [31:49<1:29:51,  2.92s/row]

Evaluating rows:  26%|██▌       | 652/2500 [31:52<1:28:07,  2.86s/row]

Evaluating rows:  26%|██▌       | 653/2500 [31:54<1:25:51,  2.79s/row]

Evaluating rows:  26%|██▌       | 654/2500 [31:57<1:25:13,  2.77s/row]

Evaluating rows:  26%|██▌       | 655/2500 [32:00<1:23:53,  2.73s/row]

Evaluating rows:  26%|██▌       | 656/2500 [32:02<1:22:50,  2.70s/row]

Evaluating rows:  26%|██▋       | 657/2500 [32:05<1:22:28,  2.69s/row]

Evaluating rows:  26%|██▋       | 658/2500 [32:08<1:22:10,  2.68s/row]

Evaluating rows:  26%|██▋       | 659/2500 [32:11<1:25:43,  2.79s/row]

Evaluating rows:  26%|██▋       | 660/2500 [32:13<1:24:58,  2.77s/row]

Evaluating rows:  26%|██▋       | 661/2500 [32:16<1:24:29,  2.76s/row]

Evaluating rows:  26%|██▋       | 662/2500 [32:19<1:25:21,  2.79s/row]

Evaluating rows:  27%|██▋       | 663/2500 [32:22<1:23:58,  2.74s/row]

Evaluating rows:  27%|██▋       | 664/2500 [32:24<1:24:45,  2.77s/row]

Evaluating rows:  27%|██▋       | 665/2500 [32:27<1:23:29,  2.73s/row]

Evaluating rows:  27%|██▋       | 666/2500 [32:30<1:24:09,  2.75s/row]

Evaluating rows:  27%|██▋       | 667/2500 [32:33<1:23:24,  2.73s/row]

Evaluating rows:  27%|██▋       | 668/2500 [32:35<1:23:04,  2.72s/row]

Evaluating rows:  27%|██▋       | 669/2500 [32:38<1:22:31,  2.70s/row]

Evaluating rows:  27%|██▋       | 670/2500 [32:41<1:23:04,  2.72s/row]

Evaluating rows:  27%|██▋       | 671/2500 [32:44<1:29:50,  2.95s/row]

Evaluating rows:  27%|██▋       | 672/2500 [32:47<1:27:19,  2.87s/row]

Evaluating rows:  27%|██▋       | 673/2500 [32:50<1:26:28,  2.84s/row]

Evaluating rows:  27%|██▋       | 674/2500 [32:52<1:24:32,  2.78s/row]

Batch saved (processed up to row 4174).

Evaluating rows:  27%|██▋       | 675/2500 [32:57<1:41:01,  3.32s/row]

Evaluating rows:  27%|██▋       | 676/2500 [32:59<1:34:03,  3.09s/row]

Evaluating rows:  27%|██▋       | 677/2500 [33:03<1:37:56,  3.22s/row]

Evaluating rows:  27%|██▋       | 678/2500 [33:06<1:32:39,  3.05s/row]

Evaluating rows:  27%|██▋       | 679/2500 [33:08<1:30:43,  2.99s/row]

Evaluating rows:  27%|██▋       | 680/2500 [33:11<1:28:22,  2.91s/row]

Evaluating rows:  27%|██▋       | 681/2500 [33:15<1:33:59,  3.10s/row]

Evaluating rows:  27%|██▋       | 682/2500 [33:17<1:29:45,  2.96s/row]

Evaluating rows:  27%|██▋       | 683/2500 [33:20<1:27:09,  2.88s/row]

Evaluating rows:  27%|██▋       | 684/2500 [33:23<1:25:24,  2.82s/row]

Evaluating rows:  27%|██▋       | 685/2500 [33:26<1:26:26,  2.86s/row]

Evaluating rows:  27%|██▋       | 686/2500 [33:28<1:25:36,  2.83s/row]

Evaluating rows:  27%|██▋       | 687/2500 [33:31<1:24:55,  2.81s/row]

Evaluating rows:  28%|██▊       | 688/2500 [33:34<1:23:47,  2.77s/row]

Evaluating rows:  28%|██▊       | 689/2500 [33:37<1:22:34,  2.74s/row]

Evaluating rows:  28%|██▊       | 690/2500 [33:39<1:21:54,  2.72s/row]

Evaluating rows:  28%|██▊       | 691/2500 [33:43<1:29:18,  2.96s/row]

Evaluating rows:  28%|██▊       | 692/2500 [33:45<1:27:05,  2.89s/row]

Evaluating rows:  28%|██▊       | 693/2500 [33:48<1:25:50,  2.85s/row]

Evaluating rows:  28%|██▊       | 694/2500 [33:51<1:24:03,  2.79s/row]

Evaluating rows:  28%|██▊       | 695/2500 [33:54<1:22:17,  2.74s/row]

Evaluating rows:  28%|██▊       | 696/2500 [33:56<1:22:15,  2.74s/row]

Evaluating rows:  28%|██▊       | 697/2500 [33:59<1:22:40,  2.75s/row]

Evaluating rows:  28%|██▊       | 698/2500 [34:02<1:21:48,  2.72s/row]

Evaluating rows:  28%|██▊       | 699/2500 [34:04<1:21:03,  2.70s/row]

Batch saved (processed up to row 4199).

Evaluating rows:  28%|██▊       | 700/2500 [34:08<1:27:56,  2.93s/row]

Evaluating rows:  28%|██▊       | 701/2500 [34:10<1:25:12,  2.84s/row]

Evaluating rows:  28%|██▊       | 702/2500 [34:13<1:23:27,  2.79s/row]

Evaluating rows:  28%|██▊       | 703/2500 [34:16<1:22:25,  2.75s/row]

Evaluating rows:  28%|██▊       | 704/2500 [34:18<1:21:58,  2.74s/row]

Evaluating rows:  28%|██▊       | 705/2500 [34:21<1:21:05,  2.71s/row]

Evaluating rows:  28%|██▊       | 706/2500 [34:24<1:20:08,  2.68s/row]

Evaluating rows:  28%|██▊       | 707/2500 [34:26<1:19:19,  2.65s/row]

Evaluating rows:  28%|██▊       | 708/2500 [34:29<1:19:01,  2.65s/row]

Evaluating rows:  28%|██▊       | 709/2500 [34:32<1:27:06,  2.92s/row]

Evaluating rows:  28%|██▊       | 710/2500 [34:35<1:24:31,  2.83s/row]

Evaluating rows:  28%|██▊       | 711/2500 [34:38<1:22:55,  2.78s/row]

Evaluating rows:  28%|██▊       | 712/2500 [34:41<1:24:27,  2.83s/row]

Evaluating rows:  29%|██▊       | 713/2500 [34:43<1:22:47,  2.78s/row]

Evaluating rows:  29%|██▊       | 714/2500 [34:46<1:21:47,  2.75s/row]

Evaluating rows:  29%|██▊       | 715/2500 [34:49<1:20:33,  2.71s/row]

Evaluating rows:  29%|██▊       | 716/2500 [34:51<1:20:02,  2.69s/row]

Evaluating rows:  29%|██▊       | 717/2500 [34:54<1:20:01,  2.69s/row]

Evaluating rows:  29%|██▊       | 718/2500 [34:57<1:20:27,  2.71s/row]

Evaluating rows:  29%|██▉       | 719/2500 [34:59<1:19:33,  2.68s/row]

Evaluating rows:  29%|██▉       | 720/2500 [35:02<1:19:24,  2.68s/row]

Evaluating rows:  29%|██▉       | 721/2500 [35:05<1:19:21,  2.68s/row]

Evaluating rows:  29%|██▉       | 722/2500 [35:07<1:19:05,  2.67s/row]

Evaluating rows:  29%|██▉       | 723/2500 [35:11<1:25:57,  2.90s/row]

Evaluating rows:  29%|██▉       | 724/2500 [35:14<1:23:44,  2.83s/row]

Batch saved (processed up to row 4224).

Evaluating rows:  29%|██▉       | 725/2500 [35:17<1:29:59,  3.04s/row]

Evaluating rows:  29%|██▉       | 726/2500 [35:21<1:36:34,  3.27s/row]

Evaluating rows:  29%|██▉       | 727/2500 [35:24<1:31:56,  3.11s/row]

Evaluating rows:  29%|██▉       | 728/2500 [35:26<1:28:56,  3.01s/row]

Evaluating rows:  29%|██▉       | 729/2500 [35:29<1:26:39,  2.94s/row]

Evaluating rows:  29%|██▉       | 730/2500 [35:32<1:24:09,  2.85s/row]

Evaluating rows:  29%|██▉       | 731/2500 [35:35<1:23:24,  2.83s/row]

Evaluating rows:  29%|██▉       | 732/2500 [35:37<1:21:24,  2.76s/row]

Evaluating rows:  29%|██▉       | 733/2500 [35:40<1:22:51,  2.81s/row]

Evaluating rows:  29%|██▉       | 734/2500 [35:43<1:21:30,  2.77s/row]

Evaluating rows:  29%|██▉       | 735/2500 [35:46<1:21:43,  2.78s/row]

Evaluating rows:  29%|██▉       | 736/2500 [35:48<1:20:15,  2.73s/row]

Evaluating rows:  29%|██▉       | 737/2500 [35:51<1:18:57,  2.69s/row]

Evaluating rows:  30%|██▉       | 738/2500 [35:53<1:18:30,  2.67s/row]

Evaluating rows:  30%|██▉       | 739/2500 [35:56<1:19:09,  2.70s/row]

Evaluating rows:  30%|██▉       | 740/2500 [35:59<1:18:36,  2.68s/row]

Evaluating rows:  30%|██▉       | 741/2500 [36:01<1:18:24,  2.67s/row]

Evaluating rows:  30%|██▉       | 742/2500 [36:04<1:18:09,  2.67s/row]

Evaluating rows:  30%|██▉       | 743/2500 [36:07<1:19:00,  2.70s/row]

Evaluating rows:  30%|██▉       | 744/2500 [36:10<1:18:34,  2.68s/row]

Evaluating rows:  30%|██▉       | 745/2500 [36:12<1:17:59,  2.67s/row]

Evaluating rows:  30%|██▉       | 746/2500 [36:15<1:17:24,  2.65s/row]

Evaluating rows:  30%|██▉       | 747/2500 [36:18<1:19:57,  2.74s/row]

Evaluating rows:  30%|██▉       | 748/2500 [36:20<1:19:14,  2.71s/row]

Evaluating rows:  30%|██▉       | 749/2500 [36:23<1:18:51,  2.70s/row]

Batch saved (processed up to row 4249).

Evaluating rows:  30%|███       | 750/2500 [36:27<1:25:28,  2.93s/row]

Evaluating rows:  30%|███       | 751/2500 [36:30<1:26:19,  2.96s/row]

Evaluating rows:  30%|███       | 752/2500 [36:32<1:23:35,  2.87s/row]

Evaluating rows:  30%|███       | 753/2500 [36:35<1:21:58,  2.82s/row]

Evaluating rows:  30%|███       | 754/2500 [36:39<1:29:24,  3.07s/row]

Evaluating rows:  30%|███       | 755/2500 [36:41<1:27:10,  3.00s/row]

Evaluating rows:  30%|███       | 756/2500 [36:44<1:24:54,  2.92s/row]

Evaluating rows:  30%|███       | 757/2500 [36:47<1:22:07,  2.83s/row]

Evaluating rows:  30%|███       | 758/2500 [36:50<1:23:43,  2.88s/row]

Evaluating rows:  30%|███       | 759/2500 [36:52<1:22:10,  2.83s/row]

Evaluating rows:  30%|███       | 760/2500 [36:55<1:20:22,  2.77s/row]

Evaluating rows:  30%|███       | 761/2500 [36:58<1:20:14,  2.77s/row]

Evaluating rows:  30%|███       | 762/2500 [37:01<1:26:18,  2.98s/row]

Evaluating rows:  31%|███       | 763/2500 [37:04<1:23:23,  2.88s/row]

Evaluating rows:  31%|███       | 764/2500 [37:07<1:23:11,  2.88s/row]

Evaluating rows:  31%|███       | 765/2500 [37:09<1:21:06,  2.80s/row]

Evaluating rows:  31%|███       | 766/2500 [37:12<1:19:56,  2.77s/row]

Evaluating rows:  31%|███       | 767/2500 [37:15<1:19:02,  2.74s/row]

Evaluating rows:  31%|███       | 768/2500 [37:17<1:18:15,  2.71s/row]

Evaluating rows:  31%|███       | 769/2500 [37:20<1:17:52,  2.70s/row]

Evaluating rows:  31%|███       | 770/2500 [37:23<1:17:51,  2.70s/row]

Evaluating rows:  31%|███       | 771/2500 [37:27<1:30:43,  3.15s/row]

Evaluating rows:  31%|███       | 772/2500 [37:30<1:27:40,  3.04s/row]

Evaluating rows:  31%|███       | 773/2500 [37:33<1:24:56,  2.95s/row]

Evaluating rows:  31%|███       | 774/2500 [37:35<1:22:56,  2.88s/row]

Batch saved (processed up to row 4274).

Evaluating rows:  31%|███       | 775/2500 [37:39<1:32:21,  3.21s/row]

Evaluating rows:  31%|███       | 776/2500 [37:42<1:27:20,  3.04s/row]

Evaluating rows:  31%|███       | 777/2500 [37:45<1:24:37,  2.95s/row]

Evaluating rows:  31%|███       | 778/2500 [37:47<1:22:53,  2.89s/row]

Evaluating rows:  31%|███       | 779/2500 [37:50<1:21:15,  2.83s/row]

Evaluating rows:  31%|███       | 780/2500 [37:53<1:19:42,  2.78s/row]

Evaluating rows:  31%|███       | 781/2500 [37:55<1:18:32,  2.74s/row]

Evaluating rows:  31%|███▏      | 782/2500 [37:58<1:17:30,  2.71s/row]

Evaluating rows:  31%|███▏      | 783/2500 [38:02<1:24:06,  2.94s/row]

Evaluating rows:  31%|███▏      | 784/2500 [38:05<1:28:27,  3.09s/row]

Evaluating rows:  31%|███▏      | 785/2500 [38:08<1:24:54,  2.97s/row]

Evaluating rows:  31%|███▏      | 786/2500 [38:10<1:21:57,  2.87s/row]

Evaluating rows:  31%|███▏      | 787/2500 [38:13<1:20:00,  2.80s/row]

Evaluating rows:  32%|███▏      | 788/2500 [38:16<1:18:28,  2.75s/row]

Evaluating rows:  32%|███▏      | 789/2500 [38:18<1:17:52,  2.73s/row]

Evaluating rows:  32%|███▏      | 790/2500 [38:21<1:18:12,  2.74s/row]

Evaluating rows:  32%|███▏      | 791/2500 [38:24<1:18:31,  2.76s/row]

Evaluating rows:  32%|███▏      | 792/2500 [38:26<1:17:25,  2.72s/row]

Evaluating rows:  32%|███▏      | 793/2500 [38:29<1:17:04,  2.71s/row]

Evaluating rows:  32%|███▏      | 794/2500 [38:32<1:17:05,  2.71s/row]

Evaluating rows:  32%|███▏      | 795/2500 [38:35<1:16:43,  2.70s/row]

Evaluating rows:  32%|███▏      | 796/2500 [38:37<1:17:07,  2.72s/row]

Evaluating rows:  32%|███▏      | 797/2500 [38:40<1:16:59,  2.71s/row]

Evaluating rows:  32%|███▏      | 798/2500 [38:43<1:16:21,  2.69s/row]

Evaluating rows:  32%|███▏      | 799/2500 [38:45<1:16:03,  2.68s/row]

Batch saved (processed up to row 4299).

Evaluating rows:  32%|███▏      | 800/2500 [38:49<1:25:36,  3.02s/row]

Evaluating rows:  32%|███▏      | 801/2500 [38:52<1:22:50,  2.93s/row]

Evaluating rows:  32%|███▏      | 802/2500 [38:55<1:23:57,  2.97s/row]

Evaluating rows:  32%|███▏      | 803/2500 [38:58<1:21:36,  2.89s/row]

Evaluating rows:  32%|███▏      | 804/2500 [39:00<1:21:49,  2.89s/row]

Evaluating rows:  32%|███▏      | 805/2500 [39:03<1:19:47,  2.82s/row]

Evaluating rows:  32%|███▏      | 806/2500 [39:06<1:18:06,  2.77s/row]

Evaluating rows:  32%|███▏      | 807/2500 [39:08<1:17:54,  2.76s/row]

Evaluating rows:  32%|███▏      | 808/2500 [39:11<1:16:42,  2.72s/row]

Evaluating rows:  32%|███▏      | 809/2500 [39:14<1:16:09,  2.70s/row]

Evaluating rows:  32%|███▏      | 810/2500 [39:16<1:15:27,  2.68s/row]

Evaluating rows:  32%|███▏      | 811/2500 [39:20<1:20:10,  2.85s/row]

Evaluating rows:  32%|███▏      | 812/2500 [39:22<1:18:03,  2.77s/row]

Evaluating rows:  33%|███▎      | 813/2500 [39:25<1:16:53,  2.73s/row]

Evaluating rows:  33%|███▎      | 814/2500 [39:28<1:16:00,  2.71s/row]

Evaluating rows:  33%|███▎      | 815/2500 [39:30<1:15:18,  2.68s/row]

Evaluating rows:  33%|███▎      | 816/2500 [39:33<1:17:40,  2.77s/row]

Evaluating rows:  33%|███▎      | 817/2500 [39:36<1:16:35,  2.73s/row]

Evaluating rows:  33%|███▎      | 818/2500 [39:38<1:16:12,  2.72s/row]

Evaluating rows:  33%|███▎      | 819/2500 [39:41<1:15:29,  2.69s/row]

Evaluating rows:  33%|███▎      | 820/2500 [39:44<1:14:35,  2.66s/row]

Evaluating rows:  33%|███▎      | 821/2500 [39:47<1:16:15,  2.72s/row]

Evaluating rows:  33%|███▎      | 822/2500 [39:49<1:15:51,  2.71s/row]

Evaluating rows:  33%|███▎      | 823/2500 [39:52<1:15:46,  2.71s/row]

Evaluating rows:  33%|███▎      | 824/2500 [39:55<1:15:30,  2.70s/row]

Batch saved (processed up to row 4324).

Evaluating rows:  33%|███▎      | 825/2500 [39:59<1:30:12,  3.23s/row]

Evaluating rows:  33%|███▎      | 826/2500 [40:02<1:26:19,  3.09s/row]

Evaluating rows:  33%|███▎      | 827/2500 [40:04<1:22:15,  2.95s/row]

Evaluating rows:  33%|███▎      | 828/2500 [40:07<1:20:18,  2.88s/row]

Evaluating rows:  33%|███▎      | 829/2500 [40:10<1:18:07,  2.81s/row]

Evaluating rows:  33%|███▎      | 830/2500 [40:12<1:16:30,  2.75s/row]

Evaluating rows:  33%|███▎      | 831/2500 [40:16<1:22:45,  2.98s/row]

Evaluating rows:  33%|███▎      | 832/2500 [40:19<1:20:46,  2.91s/row]

Evaluating rows:  33%|███▎      | 833/2500 [40:21<1:19:13,  2.85s/row]

Evaluating rows:  33%|███▎      | 834/2500 [40:24<1:17:08,  2.78s/row]

Evaluating rows:  33%|███▎      | 835/2500 [40:27<1:16:02,  2.74s/row]

Evaluating rows:  33%|███▎      | 836/2500 [40:30<1:16:44,  2.77s/row]

Evaluating rows:  33%|███▎      | 837/2500 [40:32<1:17:10,  2.78s/row]

Evaluating rows:  34%|███▎      | 838/2500 [40:35<1:15:53,  2.74s/row]

Evaluating rows:  34%|███▎      | 839/2500 [40:38<1:15:58,  2.74s/row]

Evaluating rows:  34%|███▎      | 840/2500 [40:40<1:15:12,  2.72s/row]

Evaluating rows:  34%|███▎      | 841/2500 [40:43<1:14:50,  2.71s/row]

Evaluating rows:  34%|███▎      | 842/2500 [40:46<1:14:37,  2.70s/row]

Evaluating rows:  34%|███▎      | 843/2500 [40:48<1:13:58,  2.68s/row]

Evaluating rows:  34%|███▍      | 844/2500 [40:51<1:13:35,  2.67s/row]

Evaluating rows:  34%|███▍      | 845/2500 [40:54<1:13:42,  2.67s/row]

Evaluating rows:  34%|███▍      | 846/2500 [40:57<1:21:01,  2.94s/row]

Evaluating rows:  34%|███▍      | 847/2500 [41:00<1:19:30,  2.89s/row]

In [ ]:
df = pd.read_csv(processed_csv)

In [ ]:
from datasets import Dataset

repo = "Lakshan2003/Llama3.2-1b-instruct-customerservice-LLM-as-a-judge-data"

# Convert to HF Dataset (remove index column if exists)
hf_dataset = Dataset.from_pandas(df.reset_index(drop=True))

# Push to the hub (creates parquet automatically)
hf_dataset.push_to_hub(repo, private=False)

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/6 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              :   1%|          | 35.9kB / 7.16MB

README.md:   0%|          | 0.00/790 [00:00<?, ?B/s]

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

CommitInfo(commit_url='https://huggingface.co/datasets/Lakshan2003/Llama3.2-1b-instruct-customerservice-LLM-as-a-judge-data/commit/81f0c330da7a5d80da48ea798d7f9db924f1954d', commit_message='Upload dataset', commit_description='', oid='81f0c330da7a5d80da48ea798d7f9db924f1954d', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/Lakshan2003/Llama3.2-1b-instruct-customerservice-LLM-as-a-judge-data', endpoint='https://huggingface.co', repo_type='dataset', repo_id='Lakshan2003/Llama3.2-1b-instruct-customerservice-LLM-as-a-judge-data'), pr_revision=None, pr_num=None)

In [ ]:
from datasets import load_dataset
import pandas as pd

# Load dataset from Hugging Face
dataset = load_dataset(
    "Lakshan2003/Llama3.2-1b-instruct-customerservice-LLM-as-a-judge-data",
    split="train"
)

# Convert to pandas DataFrame
df = dataset.to_pandas()

# Correct column names (exact match)
task_columns = [
    "Human-Likeness",
    "Continuity and Context Understanding",
    "Tone and Clarity",
    "Task Appropriateness",
]

# Ensure numeric dtype
df[task_columns] = df[task_columns].apply(pd.to_numeric, errors="coerce")

# Compute task-wise mean
task_wise_mean = df[task_columns].mean()

# Convert to clean table
task_wise_mean_df = task_wise_mean.reset_index()
task_wise_mean_df.columns = ["Task", "Mean Score"]

data/train-00000-of-00001.parquet:   0%|          | 0.00/7.16M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/6000 [00:00<?, ? examples/s]

In [ ]:
print(task_wise_mean_df)

                                   Task  Mean Score
0                        Human-Likeness    3.164833
1  Continuity and Context Understanding    2.357500
2                      Tone and Clarity    3.342167
3                  Task Appropriateness    2.171333