In [ ]:
!pip install anthropic

Collecting anthropic
  Downloading anthropic-0.76.0-py3-none-any.whl.metadata (28 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from anthropic) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from anthropic) (1.9.0)
Requirement already satisfied: docstring-parser<1,>=0.15 in /usr/local/lib/python3.12/dist-packages (from anthropic) (0.17.0)
Requirement already satisfied: httpx<1,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from anthropic) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from anthropic) (0.12.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from anthropic) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from anthropic) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.10 in /usr/local/lib/python3.12/dist-packages (from anthropic) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->anthropic) (3.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->anthropic) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->anthropic) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.25.0->anthropic) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->anthropic) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->anthropic) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->anthropic) (0.4.2)
Downloading anthropic-0.76.0-py3-none-any.whl (390 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 390.3/390.3 kB 12.1 MB/s eta 0:00:00
Installing collected packages: anthropic
Successfully installed anthropic-0.76.0

In [ ]:
import os
import time
import json
import re
import pandas as pd
from datasets import load_dataset
from tqdm import tqdm
from anthropic import Anthropic
from google.colab import userdata

In [ ]:
from google.colab import drive

# mount drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
MODEL_NAME = "claude-haiku-4-5-20251001"
BATCH_SIZE = 5
SLEEP_TIME = 1.2

OUTPUT_BASE = "/content/drive/MyDrive/fyp-2025/Datasets/PairwiseEvalProcessed/"
os.makedirs(OUTPUT_BASE, exist_ok=True)

claude_api = userdata.get("claude_api")
anthropic = Anthropic(api_key=claude_api)

#### Pairwise Evaluation Prompt

In [ ]:
PAIRWISE_EVAL_PROMPT = """
You are an expert evaluator specializing in customer-service interactions.

Your task is to compare two generated responses (Response A and Response B) to the same client query
and conversation context. Both responses were produced by different AI systems acting as
professional customer-service agents.

Use the Client Question and the Conversation History Summary as the main context for evaluation.
Use the full Conversation History only if additional background is needed.

A Reference Agent Response is provided only as an example of a good customer-service reply.
It is for general guidance only and should NOT be used as a comparison target.
Do not judge responses based on how similar they are to the reference.

Evaluation Criteria (all criteria are equally important):

1. Human-Likeness:
Which response sounds more natural and human-like in a real customer-service conversation?

2. Continuity and Context Understanding:
Which response better reflects the earlier conversation and correctly uses relevant details?

3. Tone and Clarity:
Which response is more professional, polite, empathetic, and easy to understand?

4. Task Appropriateness:
Which response better addresses the client’s request while following realistic customer-service practices?

If both responses are very similar in quality, choose the one that feels slightly more natural and
better connected to the context.

Context Inputs:
Conversation History: {history}
Conversation Summarized History: {history_summary}
Client Question: {client_question}
Reference Agent Response (example only): {ground_truth}

Response A:
{response_a}

Response B:
{response_b}

Choose the single better response overall.

Return your answer as valid JSON only.
Do not include any explanation or extra text.

Output Format:
{{ "winner": "A" or "B" }}
"""

In [ ]:
# Helper Function
def clean_json(text):
    text = text.strip()
    text = re.sub(r"^```[a-zA-Z]*\s*", "", text)
    text = re.sub(r"\s*```$", "", text)
    return text.replace("\ufeff", "").replace("\u200b", "").strip()

def is_unjudged(x):
    return pd.isna(x) or str(x).strip() == "" or str(x) == "None"

def extract_model_name(col):
    return col.replace("generated_answer_", "")

In [ ]:
def run_pairwise_eval(dataset_repo: str):
    print(f"\n=== Running PAIREVAL on {dataset_repo} ===")

    output_csv = os.path.join(
        OUTPUT_BASE,
        dataset_repo.split("/")[-1] + "_processed.csv"
    )

    # Load or resume
    if os.path.exists(output_csv):
        df = pd.read_csv(output_csv)
        print("Resuming from existing processed file")
    else:
        df = load_dataset(dataset_repo, split="train").to_pandas()
        for c in ["judge_pass_1", "judge_pass_2", "final_result"]:
            if c not in df.columns:
                df[c] = ""
        df.to_csv(output_csv, index=False)

    # Detect model outputs
    answer_cols = [c for c in df.columns if c.startswith("generated_answer_")]
    if len(answer_cols) != 2:
        raise ValueError("Dataset must contain exactly two generated_answer_* columns")

    col_a, col_b = answer_cols
    model_a = extract_model_name(col_a)
    model_b = extract_model_name(col_b)

    print(f"Model A: {model_a}")
    print(f"Model B: {model_b}")

    pending_idx = df.index[
        df["judge_pass_1"].apply(is_unjudged) |
        df["judge_pass_2"].apply(is_unjudged)
    ]

    print(f"Pending rows: {len(pending_idx)}")

    batch = 0

    for idx in tqdm(pending_idx, desc="Evaluating rows", unit="row"):
        row = df.loc[idx]

        try:
            # PASS 1 (A vs B)
            if is_unjudged(row["judge_pass_1"]):
                prompt = PAIRWISE_EVAL_PROMPT.format(
                    history=row["history"],
                    history_summary=row["history_summary"],
                    client_question=row["client_question"],
                    ground_truth=row["ground_truth"],
                    response_a=row[col_a],
                    response_b=row[col_b],
                )

                r = anthropic.messages.create(
                    model=MODEL_NAME,
                    temperature=0,
                    max_tokens=100,
                    messages=[{"role": "user", "content": prompt}],
                )

                df.at[idx, "judge_pass_1"] = json.loads(
                    clean_json(r.content[0].text)
                )["winner"]

            # PASS 2 (B vs A)
            if is_unjudged(row["judge_pass_2"]):
                prompt = PAIRWISE_EVAL_PROMPT.format(
                    history=row["history"],
                    history_summary=row["history_summary"],
                    client_question=row["client_question"],
                    ground_truth=row["ground_truth"],
                    response_a=row[col_b],
                    response_b=row[col_a],
                )

                r = anthropic.messages.create(
                    model=MODEL_NAME,
                    temperature=0,
                    max_tokens=50,
                    messages=[{"role": "user", "content": prompt}],
                )

                w = json.loads(clean_json(r.content[0].text))["winner"]
                df.at[idx, "judge_pass_2"] = "A" if w == "B" else "B"

            # FINAL RESULT
            p1 = df.at[idx, "judge_pass_1"]
            p2 = df.at[idx, "judge_pass_2"]

            if p1 == p2 == "A":
                df.at[idx, "final_result"] = model_a
            elif p1 == p2 == "B":
                df.at[idx, "final_result"] = model_b
            else:
                df.at[idx, "final_result"] = "Tie"

            batch += 1
            if batch >= BATCH_SIZE:
                df.to_csv(output_csv, index=False)
                batch = 0

            time.sleep(SLEEP_TIME)

        except Exception as e:
            print(f"SKIPPING row {idx} due to error: {e}")
            df.at[idx, "final_result"] = "Error"
            df.to_csv(output_csv, index=False)
            continue

    df.to_csv(output_csv, index=False)
    print(f"Finished {dataset_repo}")

### gpt4.1-vs-qwen3-4b

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-gpt4.1-vs-qwen3-4b")

=== Running PAIREVAL on Lakshan2003/pairwise-gpt4.1-vs-qwen3-4b ===
Resuming from existing processed file
Model A: gpt_4_1
Model B: qwen3_4b
Pending rows: 0

Evaluating rows: 0row [00:00, ?row/s]

Finished Lakshan2003/pairwise-gpt4.1-vs-qwen3-4b

### pairwise-gpt4.1-vs-phi-4-mini

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-gpt4.1-vs-phi-4-mini")

=== Running PAIREVAL on Lakshan2003/pairwise-gpt4.1-vs-phi-4-mini ===
Resuming from existing processed file
Model A: gpt_4_1
Model B: phi_4_mini
Pending rows: 0

Evaluating rows: 0row [00:00, ?row/s]

Finished Lakshan2003/pairwise-gpt4.1-vs-phi-4-mini

### gpt4.1-vs-llama-3.2-instruct

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-gpt4.1-vs-llama-3.2-instruct")

=== Running PAIREVAL on Lakshan2003/pairwise-gpt4.1-vs-llama-3.2-instruct ===
Resuming from existing processed file
Model A: gpt_4_1
Model B: llama3_2
Pending rows: 0

Evaluating rows: 0row [00:00, ?row/s]

Finished Lakshan2003/pairwise-gpt4.1-vs-llama-3.2-instruct

### gemini-2.5-flash-vs-qwen3-4b

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-4b")

=== Running PAIREVAL on Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-4b ===
Resuming from existing processed file
Model A: gemini_2_5_flash
Model B: qwen3_4b
Pending rows: 0

Evaluating rows: 0row [00:00, ?row/s]

Finished Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-4b

### gemini-2.5-flash-vs-phi-4-mini

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-gemini-2.5-flash-vs-phi-4-mini")

=== Running PAIREVAL on Lakshan2003/pairwise-gemini-2.5-flash-vs-phi-4-mini ===
Resuming from existing processed file
Model A: gemini_2_5_flash
Model B: phi_4_mini
Pending rows: 0

Evaluating rows: 0row [00:00, ?row/s]

Finished Lakshan2003/pairwise-gemini-2.5-flash-vs-phi-4-mini

### gemini-2.5-flash-vs-llama-3.2-instruct

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-gemini-2.5-flash-vs-llama-3.2-instruct")

=== Running PAIREVAL on Lakshan2003/pairwise-gemini-2.5-flash-vs-llama-3.2-instruct ===
Resuming from existing processed file
Model A: gemini_2_5_flash
Model B: llama3_2
Pending rows: 0

Evaluating rows: 0row [00:00, ?row/s]

Finished Lakshan2003/pairwise-gemini-2.5-flash-vs-llama-3.2-instruct

### virtuoso-large-vs-qwen3-4b

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-virtuoso-large-vs-qwen3-4b")

=== Running PAIREVAL on Lakshan2003/pairwise-virtuoso-large-vs-qwen3-4b ===
Resuming from existing processed file
Model A: virtuoso_large
Model B: qwen3_4b
Pending rows: 0

Evaluating rows: 0row [00:00, ?row/s]

Finished Lakshan2003/pairwise-virtuoso-large-vs-qwen3-4b

### virtuoso-large-vs-phi-4-mini

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-virtuoso-large-vs-phi-4-mini")

=== Running PAIREVAL on Lakshan2003/pairwise-virtuoso-large-vs-phi-4-mini ===
Resuming from existing processed file
Model A: virtuoso_large
Model B: phi_4_mini
Pending rows: 0

Evaluating rows: 0row [00:00, ?row/s]

Finished Lakshan2003/pairwise-virtuoso-large-vs-phi-4-mini

### virtuoso-large-vs-llama-3.2-instruct

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-virtuoso-large-vs-llama-3.2-instruct")

=== Running PAIREVAL on Lakshan2003/pairwise-virtuoso-large-vs-llama-3.2-instruct ===
Resuming from existing processed file
Model A: virtuoso_large
Model B: llama3_2
Pending rows: 0

Evaluating rows: 0row [00:00, ?row/s]

Finished Lakshan2003/pairwise-virtuoso-large-vs-llama-3.2-instruct

### gpt4.1-vs-qwen3-8b

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-gpt4.1-vs-qwen3-8b")

=== Running PAIREVAL on Lakshan2003/pairwise-gpt4.1-vs-qwen3-8b ===
Resuming from existing processed file
Model A: gpt_4_1
Model B: qwen3_8b
Pending rows: 0

Evaluating rows: 0row [00:00, ?row/s]

Finished Lakshan2003/pairwise-gpt4.1-vs-qwen3-8b

### gpt4.1-vs-llama3.1-8b

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-gpt4.1-vs-llama3.1-8b")

=== Running PAIREVAL on Lakshan2003/pairwise-gpt4.1-vs-llama3.1-8b ===
Resuming from existing processed file
Model A: gpt_4_1
Model B: llama3_1_8b
Pending rows: 0

Evaluating rows: 0row [00:00, ?row/s]

Finished Lakshan2003/pairwise-gpt4.1-vs-llama3.1-8b

### gpt4.1-vs-qwen3-1.7b

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-gpt4.1-vs-qwen3-1.7b")

=== Running PAIREVAL on Lakshan2003/pairwise-gpt4.1-vs-qwen3-1.7b ===
Resuming from existing processed file
Model A: gpt_4_1
Model B: qwen3_1_7b
Pending rows: 0

Evaluating rows: 0row [00:00, ?row/s]

Finished Lakshan2003/pairwise-gpt4.1-vs-qwen3-1.7b

### gpt4.1-vs-llama3.2-1b

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-gpt4.1-vs-llama3.2-1b")

=== Running PAIREVAL on Lakshan2003/pairwise-gpt4.1-vs-llama3.2-1b ===
Resuming from existing processed file
Model A: gpt_4_1
Model B: llama3_2_1b
Pending rows: 0

Evaluating rows: 0row [00:00, ?row/s]

Finished Lakshan2003/pairwise-gpt4.1-vs-llama3.2-1b

### gemini-2.5-flash-vs-qwen3-8b

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-8b")

=== Running PAIREVAL on Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-8b ===
Resuming from existing processed file
Model A: gemini_2_5_flash
Model B: qwen3_8b
Pending rows: 0

Evaluating rows: 0row [00:00, ?row/s]

Finished Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-8b

### gemini-2.5-flash-vs-llama3.1-8b

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-gemini-2.5-flash-vs-llama3.1-8b")

=== Running PAIREVAL on Lakshan2003/pairwise-gemini-2.5-flash-vs-llama3.1-8b ===
Resuming from existing processed file
Model A: gemini_2_5_flash
Model B: llama3_1_8b
Pending rows: 0

Evaluating rows: 0row [00:00, ?row/s]

Finished Lakshan2003/pairwise-gemini-2.5-flash-vs-llama3.1-8b

### gemini-2.5-flash-vs-qwen3-1.7

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-1.7b")

=== Running PAIREVAL on Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-1.7b ===
Resuming from existing processed file
Model A: gemini_2_5_flash
Model B: qwen3_1_7b
Pending rows: 0

Evaluating rows: 0row [00:00, ?row/s]

Finished Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-1.7b

### gemini-2.5-flash-vs-llama3.2-1b

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-gemini-2.5-flash-vs-llama3.2-1b")

=== Running PAIREVAL on Lakshan2003/pairwise-gemini-2.5-flash-vs-llama3.2-1b ===
Resuming from existing processed file
Model A: gemini_2_5_flash
Model B: llama3_2_1b
Pending rows: 0

Evaluating rows: 0row [00:00, ?row/s]

Finished Lakshan2003/pairwise-gemini-2.5-flash-vs-llama3.2-1b

#### virtuoso-large-vs-qwen3-8b

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-virtuoso-large-vs-qwen3-8b")

=== Running PAIREVAL on Lakshan2003/pairwise-virtuoso-large-vs-qwen3-8b ===
Resuming from existing processed file
Model A: virtuoso_large
Model B: qwen3_8b
Pending rows: 0

Evaluating rows: 0row [00:00, ?row/s]

Finished Lakshan2003/pairwise-virtuoso-large-vs-qwen3-8b

### virtuoso-large-vs-qwen3-1.7b

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-virtuoso-large-vs-qwen3-1.7b")

=== Running PAIREVAL on Lakshan2003/pairwise-virtuoso-large-vs-qwen3-1.7b ===
Resuming from existing processed file
Model A: virtuoso_large
Model B: qwen3_1_7b
Pending rows: 0

Evaluating rows: 0row [00:00, ?row/s]

Finished Lakshan2003/pairwise-virtuoso-large-vs-qwen3-1.7b

### virtuoso-large-vs-llama3.2-1b

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-virtuoso-large-vs-llama3.2-1b")

=== Running PAIREVAL on Lakshan2003/pairwise-virtuoso-large-vs-llama3.2-1b ===
Resuming from existing processed file
Model A: virtuoso_large
Model B: llama3_2_1b
Pending rows: 0

Evaluating rows: 0row [00:00, ?row/s]

Finished Lakshan2003/pairwise-virtuoso-large-vs-llama3.2-1b

### virtuoso-large-vs-llama3.1-8b

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-virtuoso-large-vs-llama3.1-8b")

=== Running PAIREVAL on Lakshan2003/pairwise-virtuoso-large-vs-llama3.1-8b ===
Resuming from existing processed file
Model A: virtuoso_large
Model B: llama3_1_8b
Pending rows: 0

Evaluating rows: 0row [00:00, ?row/s]

Finished Lakshan2003/pairwise-virtuoso-large-vs-llama3.1-8b

### virtuoso-large-vs-gemma-3-4b

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-virtuoso-large-vs-gemma-3-4b")

=== Running PAIREVAL on Lakshan2003/pairwise-virtuoso-large-vs-gemma-3-4b ===

README.md:   0%|          | 0.00/775 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/1.32M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1000 [00:00<?, ? examples/s]

Model A: virtuoso_large
Model B: gemma3_4b
Pending rows: 1000

Evaluating rows: 100%|██████████| 1000/1000 [56:17<00:00,  3.38s/row]

Finished Lakshan2003/pairwise-virtuoso-large-vs-gemma-3-4b

### virtuoso-large-vs-smollm3-3b

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-virtuoso-large-vs-smollm3-3b")

=== Running PAIREVAL on Lakshan2003/pairwise-virtuoso-large-vs-smollm3-3b ===

README.md:   0%|          | 0.00/776 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/1.29M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1000 [00:00<?, ? examples/s]

Model A: virtuoso_large
Model B: smollm3_3b
Pending rows: 1000

Evaluating rows: 100%|██████████| 1000/1000 [56:41<00:00,  3.40s/row]

Finished Lakshan2003/pairwise-virtuoso-large-vs-smollm3-3b

### gemini-2.5-flash-vs-gemma-3-4b

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-gemini-2.5-flash-vs-gemma-3-4b")

=== Running PAIREVAL on Lakshan2003/pairwise-gemini-2.5-flash-vs-gemma-3-4b ===

README.md:   0%|          | 0.00/777 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/1.29M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1000 [00:00<?, ? examples/s]

Model A: gemini_2_5_flash
Model B: gemma3_4b
Pending rows: 1000

Evaluating rows: 100%|██████████| 1000/1000 [57:27<00:00,  3.45s/row]

Finished Lakshan2003/pairwise-gemini-2.5-flash-vs-gemma-3-4b

### pairwise-gemini-2.5-flash-vs-smollm3-3b

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-gemini-2.5-flash-vs-smollm3-3b")

=== Running PAIREVAL on Lakshan2003/pairwise-gemini-2.5-flash-vs-smollm3-3b ===

README.md:   0%|          | 0.00/778 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/1.26M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1000 [00:00<?, ? examples/s]

Model A: gemini_2_5_flash
Model B: smollm3_3b
Pending rows: 1000

Evaluating rows: 100%|██████████| 1000/1000 [48:58<00:00,  2.94s/row]

Finished Lakshan2003/pairwise-gemini-2.5-flash-vs-smollm3-3b

### gpt4.1-vs-gemma-3-4b

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-gpt4.1-vs-gemma-3-4b")

=== Running PAIREVAL on Lakshan2003/pairwise-gpt4.1-vs-gemma-3-4b ===

README.md:   0%|          | 0.00/768 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/1.32M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1000 [00:00<?, ? examples/s]

Model A: gpt_4_1
Model B: gemma3_4b
Pending rows: 1000

Evaluating rows: 100%|██████████| 1000/1000 [47:15<00:00,  2.84s/row]

Finished Lakshan2003/pairwise-gpt4.1-vs-gemma-3-4b

### gpt4.1-vs-smollm3-3b

In [ ]:
run_pairwise_eval("Lakshan2003/pairwise-gpt4.1-vs-smollm3-3b")

=== Running PAIREVAL on Lakshan2003/pairwise-gpt4.1-vs-smollm3-3b ===

README.md:   0%|          | 0.00/769 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/1.29M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1000 [00:00<?, ? examples/s]

Model A: gpt_4_1
Model B: smollm3_3b
Pending rows: 1000

Evaluating rows: 100%|██████████| 1000/1000 [46:20<00:00,  2.78s/row]

Finished Lakshan2003/pairwise-gpt4.1-vs-smollm3-3b

In [ ]:
import os
import pandas as pd
from datasets import Dataset
from huggingface_hub import login

# CONFIG
LOCAL_DIR = "/content/drive/MyDrive/fyp-2025/Datasets/PairwiseEvalProcessed"

# UPLOADS = {
#     "pairwise-virtuoso-large-vs-qwen3-4b_processed.csv":
#         "Lakshan2003/pairwise-virtuoso-large-vs-qwen3-4b",

#     "pairwise-virtuoso-large-vs-phi-4-mini_processed.csv":
#         "Lakshan2003/pairwise-virtuoso-large-vs-phi-4-mini",

#     "pairwise-virtuoso-large-vs-llama-3.2-instruct_processed.csv":
#         "Lakshan2003/pairwise-virtuoso-large-vs-llama-3.2-instruct",

#     "pairwise-gpt4.1-vs-qwen3-4b_processed.csv":
#         "Lakshan2003/pairwise-gpt4.1-vs-qwen3-4b",

#     "pairwise-gpt4.1-vs-phi-4-mini_processed.csv":
#         "Lakshan2003/pairwise-gpt4.1-vs-phi-4-mini",

#     "pairwise-gpt4.1-vs-llama-3.2-instruct_processed.csv":
#         "Lakshan2003/pairwise-gpt4.1-vs-llama-3.2-instruct",

#     "pairwise-gemini-2.5-flash-vs-qwen3-4b_processed.csv":
#         "Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-4b",

#     "pairwise-gemini-2.5-flash-vs-phi-4-mini_processed.csv":
#         "Lakshan2003/pairwise-gemini-2.5-flash-vs-phi-4-mini",

#     "pairwise-gemini-2.5-flash-vs-llama-3.2-instruct_processed.csv":
#         "Lakshan2003/pairwise-gemini-2.5-flash-vs-llama-3.2-instruct",
# }


UPLOADS = {
    # ========= Virtuoso-Large vs =========
    "pairwise-virtuoso-large-vs-qwen3-8b_processed.csv":
        "Lakshan2003/pairwise-virtuoso-large-vs-qwen3-8b",

    "pairwise-virtuoso-large-vs-qwen3-4b_processed.csv":
        "Lakshan2003/pairwise-virtuoso-large-vs-qwen3-4b",

    "pairwise-virtuoso-large-vs-qwen3-1.7b_processed.csv":
        "Lakshan2003/pairwise-virtuoso-large-vs-qwen3-1.7b",

    "pairwise-virtuoso-large-vs-phi-4-mini_processed.csv":
        "Lakshan2003/pairwise-virtuoso-large-vs-phi-4-mini",

    "pairwise-virtuoso-large-vs-llama3.2-1b_processed.csv":
        "Lakshan2003/pairwise-virtuoso-large-vs-llama3.2-1b",

    "pairwise-virtuoso-large-vs-llama3.1-8b_processed.csv":
        "Lakshan2003/pairwise-virtuoso-large-vs-llama3.1-8b",

    "pairwise-virtuoso-large-vs-llama-3.2-instruct_processed.csv":
        "Lakshan2003/pairwise-virtuoso-large-vs-llama-3.2-instruct",

    # 🔹 MISSING — added
    "pairwise-virtuoso-large-vs-gemma-3-4b_processed.csv":
        "Lakshan2003/pairwise-virtuoso-large-vs-gemma-3-4b",

    "pairwise-virtuoso-large-vs-smollm3-3b_processed.csv":
        "Lakshan2003/pairwise-virtuoso-large-vs-smollm3-3b",


    # ========= GPT-4.1 vs =========
    "pairwise-gpt4.1-vs-qwen3-8b_processed.csv":
        "Lakshan2003/pairwise-gpt4.1-vs-qwen3-8b",

    "pairwise-gpt4.1-vs-qwen3-4b_processed.csv":
        "Lakshan2003/pairwise-gpt4.1-vs-qwen3-4b",

    "pairwise-gpt4.1-vs-qwen3-1.7b_processed.csv":
        "Lakshan2003/pairwise-gpt4.1-vs-qwen3-1.7b",

    "pairwise-gpt4.1-vs-phi-4-mini_processed.csv":
        "Lakshan2003/pairwise-gpt4.1-vs-phi-4-mini",

    "pairwise-gpt4.1-vs-llama3.2-1b_processed.csv":
        "Lakshan2003/pairwise-gpt4.1-vs-llama3.2-1b",

    "pairwise-gpt4.1-vs-llama3.1-8b_processed.csv":
        "Lakshan2003/pairwise-gpt4.1-vs-llama3.1-8b",

    "pairwise-gpt4.1-vs-llama-3.2-instruct_processed.csv":
        "Lakshan2003/pairwise-gpt4.1-vs-llama-3.2-instruct",

    # 🔹 MISSING — added
    "pairwise-gpt4.1-vs-gemma-3-4b_processed.csv":
        "Lakshan2003/pairwise-gpt4.1-vs-gemma-3-4b",

    "pairwise-gpt4.1-vs-smollm3-3b_processed.csv":
        "Lakshan2003/pairwise-gpt4.1-vs-smollm3-3b",


    # ========= Gemini-2.5-Flash vs =========
    "pairwise-gemini-2.5-flash-vs-qwen3-8b_processed.csv":
        "Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-8b",

    "pairwise-gemini-2.5-flash-vs-qwen3-4b_processed.csv":
        "Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-4b",

    "pairwise-gemini-2.5-flash-vs-qwen3-1.7b_processed.csv":
        "Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-1.7b",

    "pairwise-gemini-2.5-flash-vs-phi-4-mini_processed.csv":
        "Lakshan2003/pairwise-gemini-2.5-flash-vs-phi-4-mini",

    "pairwise-gemini-2.5-flash-vs-llama3.2-1b_processed.csv":
        "Lakshan2003/pairwise-gemini-2.5-flash-vs-llama3.2-1b",

    "pairwise-gemini-2.5-flash-vs-llama3.1-8b_processed.csv":
        "Lakshan2003/pairwise-gemini-2.5-flash-vs-llama3.1-8b",

    "pairwise-gemini-2.5-flash-vs-llama-3.2-instruct_processed.csv":
        "Lakshan2003/pairwise-gemini-2.5-flash-vs-llama-3.2-instruct",

    # 🔹 MISSING — added
    "pairwise-gemini-2.5-flash-vs-gemma-3-4b_processed.csv":
        "Lakshan2003/pairwise-gemini-2.5-flash-vs-gemma-3-4b",

    "pairwise-gemini-2.5-flash-vs-smollm3-3b_processed.csv":
        "Lakshan2003/pairwise-gemini-2.5-flash-vs-smollm3-3b",
}

# Upload loop (THIS replaces parquet correctly)
for local_file, repo_id in UPLOADS.items():
    local_path = os.path.join(LOCAL_DIR, local_file)

    if not os.path.exists(local_path):
        raise FileNotFoundError(local_path)

    print(f"\nProcessing {local_file} → {repo_id}")

    # Load processed CSV
    df = pd.read_csv(local_path)

    # Sanity check (important)
    print(df[["judge_pass_1", "judge_pass_2", "final_result"]].head())

    # Convert to HF Dataset
    dataset = Dataset.from_pandas(df, preserve_index=False)

    # Push to hub (this OVERWRITES parquet)
    dataset.push_to_hub(
        repo_id,
        split="train",
        commit_message="Replace parquet with updated PAIREVAL judge results"
    )

print("\nAll parquet datasets replaced successfully.")

Processing pairwise-virtuoso-large-vs-qwen3-8b_processed.csv → Lakshan2003/pairwise-virtuoso-large-vs-qwen3-8b
  judge_pass_1 judge_pass_2    final_result
0            B            B        qwen3_8b
1            A            A  virtuoso_large
2            A            A  virtuoso_large
3            A            A  virtuoso_large
4            B            B        qwen3_8b

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.30MB / 1.30MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing pairwise-virtuoso-large-vs-qwen3-4b_processed.csv → Lakshan2003/pairwise-virtuoso-large-vs-qwen3-4b
  judge_pass_1 judge_pass_2    final_result
0            A            A  virtuoso_large
1            A            A  virtuoso_large
2            B            A             Tie
3            A            A  virtuoso_large
4            B            A             Tie

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.28MB / 1.28MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing pairwise-virtuoso-large-vs-qwen3-1.7b_processed.csv → Lakshan2003/pairwise-virtuoso-large-vs-qwen3-1.7b
  judge_pass_1 judge_pass_2    final_result
0            A            B             Tie
1            B            B      qwen3_1_7b
2            A            A  virtuoso_large
3            A            A  virtuoso_large
4            A            A  virtuoso_large

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.27MB / 1.27MB

                              : 100%|##########| 1.27MB / 1.27MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing pairwise-virtuoso-large-vs-phi-4-mini_processed.csv → Lakshan2003/pairwise-virtuoso-large-vs-phi-4-mini
  judge_pass_1 judge_pass_2    final_result
0            A            A  virtuoso_large
1            A            A  virtuoso_large
2            A            A  virtuoso_large
3            A            A  virtuoso_large
4            B            B      phi_4_mini

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.28MB / 1.28MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing pairwise-virtuoso-large-vs-llama3.2-1b_processed.csv → Lakshan2003/pairwise-virtuoso-large-vs-llama3.2-1b
  judge_pass_1 judge_pass_2    final_result
0            A            A  virtuoso_large
1            A            A  virtuoso_large
2            A            A  virtuoso_large
3            A            A  virtuoso_large
4            A            B             Tie

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.32MB / 1.32MB

                              : 100%|##########| 1.32MB / 1.32MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing pairwise-virtuoso-large-vs-llama3.1-8b_processed.csv → Lakshan2003/pairwise-virtuoso-large-vs-llama3.1-8b
  judge_pass_1 judge_pass_2    final_result
0            A            A  virtuoso_large
1            A            A  virtuoso_large
2            B            A             Tie
3            A            A  virtuoso_large
4            B            B     llama3_1_8b

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.29MB / 1.29MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing pairwise-virtuoso-large-vs-llama-3.2-instruct_processed.csv → Lakshan2003/pairwise-virtuoso-large-vs-llama-3.2-instruct
  judge_pass_1 judge_pass_2    final_result
0            A            A  virtuoso_large
1            A            A  virtuoso_large
2            B            A             Tie
3            A            A  virtuoso_large
4            A            A  virtuoso_large

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.29MB / 1.29MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing pairwise-virtuoso-large-vs-gemma-3-4b_processed.csv → Lakshan2003/pairwise-virtuoso-large-vs-gemma-3-4b
  judge_pass_1 judge_pass_2    final_result
0            A            A  virtuoso_large
1            A            A  virtuoso_large
2            A            A  virtuoso_large
3            A            A  virtuoso_large
4            A            A  virtuoso_large

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.32MB / 1.32MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing pairwise-virtuoso-large-vs-smollm3-3b_processed.csv → Lakshan2003/pairwise-virtuoso-large-vs-smollm3-3b
  judge_pass_1 judge_pass_2    final_result
0            A            A  virtuoso_large
1            A            A  virtuoso_large
2            A            A  virtuoso_large
3            A            A  virtuoso_large
4            A            A  virtuoso_large

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.29MB / 1.29MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing pairwise-gpt4.1-vs-qwen3-8b_processed.csv → Lakshan2003/pairwise-gpt4.1-vs-qwen3-8b
  judge_pass_1 judge_pass_2 final_result
0            A            B          Tie
1            A            A      gpt_4_1
2            A            B          Tie
3            A            A      gpt_4_1
4            B            B     qwen3_8b

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.30MB / 1.30MB

                              : 100%|##########| 1.30MB / 1.30MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing pairwise-gpt4.1-vs-qwen3-4b_processed.csv → Lakshan2003/pairwise-gpt4.1-vs-qwen3-4b
  judge_pass_1 judge_pass_2 final_result
0            B            A          Tie
1            A            A      gpt_4_1
2            A            A      gpt_4_1
3            A            A      gpt_4_1
4            B            B     qwen3_4b

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.28MB / 1.28MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing pairwise-gpt4.1-vs-qwen3-1.7b_processed.csv → Lakshan2003/pairwise-gpt4.1-vs-qwen3-1.7b
  judge_pass_1 judge_pass_2 final_result
0            A            B          Tie
1            B            B   qwen3_1_7b
2            A            A      gpt_4_1
3            A            A      gpt_4_1
4            A            B          Tie

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.27MB / 1.27MB

                              : 100%|##########| 1.27MB / 1.27MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing pairwise-gpt4.1-vs-phi-4-mini_processed.csv → Lakshan2003/pairwise-gpt4.1-vs-phi-4-mini
  judge_pass_1 judge_pass_2 final_result
0            A            A      gpt_4_1
1            A            A      gpt_4_1
2            A            A      gpt_4_1
3            A            A      gpt_4_1
4            B            B   phi_4_mini

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.28MB / 1.28MB

                              : 100%|##########| 1.28MB / 1.28MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing pairwise-gpt4.1-vs-llama3.2-1b_processed.csv → Lakshan2003/pairwise-gpt4.1-vs-llama3.2-1b
  judge_pass_1 judge_pass_2 final_result
0            A            A      gpt_4_1
1            A            A      gpt_4_1
2            A            A      gpt_4_1
3            A            A      gpt_4_1
4            A            A      gpt_4_1

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.32MB / 1.32MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing pairwise-gpt4.1-vs-llama3.1-8b_processed.csv → Lakshan2003/pairwise-gpt4.1-vs-llama3.1-8b
  judge_pass_1 judge_pass_2 final_result
0            A            A      gpt_4_1
1            B            A          Tie
2            A            B          Tie
3            A            A      gpt_4_1
4            B            B  llama3_1_8b

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.29MB / 1.29MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing pairwise-gpt4.1-vs-llama-3.2-instruct_processed.csv → Lakshan2003/pairwise-gpt4.1-vs-llama-3.2-instruct
  judge_pass_1 judge_pass_2 final_result
0            A            B          Tie
1            A            A      gpt_4_1
2            B            B     llama3_2
3            A            A      gpt_4_1
4            B            A          Tie

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.29MB / 1.29MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing pairwise-gpt4.1-vs-gemma-3-4b_processed.csv → Lakshan2003/pairwise-gpt4.1-vs-gemma-3-4b
  judge_pass_1 judge_pass_2 final_result
0            A            A      gpt_4_1
1            A            A      gpt_4_1
2            A            A      gpt_4_1
3            A            A      gpt_4_1
4            B            B    gemma3_4b

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.32MB / 1.32MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing pairwise-gpt4.1-vs-smollm3-3b_processed.csv → Lakshan2003/pairwise-gpt4.1-vs-smollm3-3b
  judge_pass_1 judge_pass_2 final_result
0            A            A      gpt_4_1
1            A            A      gpt_4_1
2            A            A      gpt_4_1
3            A            A      gpt_4_1
4            B            A          Tie

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.29MB / 1.29MB

                              : 100%|##########| 1.29MB / 1.29MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing pairwise-gemini-2.5-flash-vs-qwen3-8b_processed.csv → Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-8b
  judge_pass_1 judge_pass_2      final_result
0            A            B               Tie
1            A            A  gemini_2_5_flash
2            B            B          qwen3_8b
3            B            B          qwen3_8b
4            B            B          qwen3_8b

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.27MB / 1.27MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing pairwise-gemini-2.5-flash-vs-qwen3-4b_processed.csv → Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-4b
  judge_pass_1 judge_pass_2      final_result
0            A            A  gemini_2_5_flash
1            A            A  gemini_2_5_flash
2            B            B          qwen3_4b
3            A            B               Tie
4            B            A               Tie

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.25MB / 1.25MB

                              : 100%|##########| 1.25MB / 1.25MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing pairwise-gemini-2.5-flash-vs-qwen3-1.7b_processed.csv → Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-1.7b
  judge_pass_1 judge_pass_2      final_result
0            B            B        qwen3_1_7b
1            A            B               Tie
2            B            A               Tie
3            A            A  gemini_2_5_flash
4            B            A               Tie

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.24MB / 1.24MB

                              : 100%|##########| 1.24MB / 1.24MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing pairwise-gemini-2.5-flash-vs-phi-4-mini_processed.csv → Lakshan2003/pairwise-gemini-2.5-flash-vs-phi-4-mini
  judge_pass_1 judge_pass_2      final_result
0            A            A  gemini_2_5_flash
1            A            A  gemini_2_5_flash
2            B            B        phi_4_mini
3            B            B        phi_4_mini
4            B            B        phi_4_mini

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.25MB / 1.25MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing pairwise-gemini-2.5-flash-vs-llama3.2-1b_processed.csv → Lakshan2003/pairwise-gemini-2.5-flash-vs-llama3.2-1b
  judge_pass_1 judge_pass_2      final_result
0            A            A  gemini_2_5_flash
1            A            A  gemini_2_5_flash
2            B            B       llama3_2_1b
3            A            B               Tie
4            A            B               Tie

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.29MB / 1.29MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing pairwise-gemini-2.5-flash-vs-llama3.1-8b_processed.csv → Lakshan2003/pairwise-gemini-2.5-flash-vs-llama3.1-8b
  judge_pass_1 judge_pass_2      final_result
0            A            A  gemini_2_5_flash
1            A            A  gemini_2_5_flash
2            B            B       llama3_1_8b
3            B            B       llama3_1_8b
4            B            B       llama3_1_8b

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.26MB / 1.26MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing pairwise-gemini-2.5-flash-vs-llama-3.2-instruct_processed.csv → Lakshan2003/pairwise-gemini-2.5-flash-vs-llama-3.2-instruct
  judge_pass_1 judge_pass_2      final_result
0            A            A  gemini_2_5_flash
1            A            A  gemini_2_5_flash
2            B            B          llama3_2
3            B            B          llama3_2
4            A            A  gemini_2_5_flash

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.26MB / 1.26MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing pairwise-gemini-2.5-flash-vs-gemma-3-4b_processed.csv → Lakshan2003/pairwise-gemini-2.5-flash-vs-gemma-3-4b
  judge_pass_1 judge_pass_2      final_result
0            A            A  gemini_2_5_flash
1            A            A  gemini_2_5_flash
2            A            A  gemini_2_5_flash
3            A            A  gemini_2_5_flash
4            A            A  gemini_2_5_flash

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.29MB / 1.29MB

                              : 100%|##########| 1.29MB / 1.29MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing pairwise-gemini-2.5-flash-vs-smollm3-3b_processed.csv → Lakshan2003/pairwise-gemini-2.5-flash-vs-smollm3-3b
  judge_pass_1 judge_pass_2      final_result
0            A            A  gemini_2_5_flash
1            A            A  gemini_2_5_flash
2            A            A  gemini_2_5_flash
3            A            A  gemini_2_5_flash
4            A            A  gemini_2_5_flash

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 1.26MB / 1.26MB

                              : 100%|##########| 1.26MB / 1.26MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

All parquet datasets replaced successfully.

## Summarized Pairwise Results

In [ ]:
import pandas as pd
from datasets import load_dataset, Dataset

# CONFIG
PAIRWISE_REPOS = [
    # ========= Virtuoso-Large vs =========
    "Lakshan2003/pairwise-virtuoso-large-vs-llama3.2-1b",
    "Lakshan2003/pairwise-virtuoso-large-vs-llama3.1-8b",
    "Lakshan2003/pairwise-virtuoso-large-vs-qwen3-1.7b",
    "Lakshan2003/pairwise-virtuoso-large-vs-qwen3-4b",
    "Lakshan2003/pairwise-virtuoso-large-vs-qwen3-8b",
    "Lakshan2003/pairwise-virtuoso-large-vs-phi-4-mini",
    "Lakshan2003/pairwise-virtuoso-large-vs-gemma-3-4b",
    "Lakshan2003/pairwise-virtuoso-large-vs-smollm3-3b",
    "Lakshan2003/pairwise-virtuoso-large-vs-llama-3.2-instruct",

    # ========= Gemini-2.5-Flash vs =========
    "Lakshan2003/pairwise-gemini-2.5-flash-vs-llama3.2-1b",
    "Lakshan2003/pairwise-gemini-2.5-flash-vs-llama3.1-8b",
    "Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-1.7b",
    "Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-4b",
    "Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-8b",
    "Lakshan2003/pairwise-gemini-2.5-flash-vs-phi-4-mini",
    "Lakshan2003/pairwise-gemini-2.5-flash-vs-gemma-3-4b",
    "Lakshan2003/pairwise-gemini-2.5-flash-vs-smollm3-3b",
    "Lakshan2003/pairwise-gemini-2.5-flash-vs-llama-3.2-instruct",

    # ========= GPT-4.1 vs =========
    "Lakshan2003/pairwise-gpt4.1-vs-llama3.2-1b",
    "Lakshan2003/pairwise-gpt4.1-vs-llama3.1-8b",
    "Lakshan2003/pairwise-gpt4.1-vs-qwen3-1.7b",
    "Lakshan2003/pairwise-gpt4.1-vs-qwen3-4b",
    "Lakshan2003/pairwise-gpt4.1-vs-qwen3-8b",
    "Lakshan2003/pairwise-gpt4.1-vs-phi-4-mini",
    "Lakshan2003/pairwise-gpt4.1-vs-gemma-3-4b",
    "Lakshan2003/pairwise-gpt4.1-vs-smollm3-3b",
    "Lakshan2003/pairwise-gpt4.1-vs-llama-3.2-instruct",
]

SUMMARY_REPO = "Lakshan2003/pairwise-eval-results"
JUDGE_NAME = "claude-haiku-4-5"

# These are IDENTIFIERS, not full names
LLM_KEYS = ["virtuoso", "gpt4", "gemini"]


def get_models_from_columns(df: pd.DataFrame):
    """Extract the two model names exactly as used in final_result."""
    cols = [c for c in df.columns if c.startswith("generated_answer_")]
    if len(cols) != 2:
        raise ValueError(f"Expected 2 generated_answer_* columns, got {len(cols)}")

    m1 = cols[0].replace("generated_answer_", "")
    m2 = cols[1].replace("generated_answer_", "")
    return m1, m2


def classify_llm_slm(model_a: str, model_b: str):
    """Determine which model is LLM vs SLM based on known LLM keys."""
    a_is_llm = any(k in model_a for k in LLM_KEYS)
    b_is_llm = any(k in model_b for k in LLM_KEYS)

    if a_is_llm and not b_is_llm:
        return model_a, model_b
    if b_is_llm and not a_is_llm:
        return model_b, model_a

    # Fallback (should not normally happen)
    print(f"WARNING: Could not confidently classify LLM/SLM between {model_a} and {model_b}")
    return model_a, model_b


rows = []

# Aggregate results
for repo in PAIRWISE_REPOS:
    print(f"Loading {repo}")
    df = load_dataset(repo, split="train").to_pandas()

    model_a, model_b = get_models_from_columns(df)
    llm, slm = classify_llm_slm(model_a, model_b)

    llm_wins = 0
    slm_wins = 0
    ties = 0
    valid = 0

    for r in df["final_result"]:
        if r == llm:
            llm_wins += 1
            valid += 1
        elif r == slm:
            slm_wins += 1
            valid += 1
        elif r == "Tie":
            ties += 1
            valid += 1
        else:
            # ignore invalid / empty / Error rows
            continue

    rows.append({
        "llm": llm,
        "slm": slm,
        "llm_wins": llm_wins,
        "slm_wins": slm_wins,
        "ties": ties,
        "llm_win_pct": llm_wins / valid * 100 if valid else 0.0,
        "slm_win_pct": slm_wins / valid * 100 if valid else 0.0,
        "tie_pct": ties / valid * 100 if valid else 0.0,
        "tested_records": valid,
        "judge": JUDGE_NAME
    })

summary_df = (
    pd.DataFrame(rows)
    .sort_values(["llm", "slm"])
    .reset_index(drop=True)
)

for col in ["llm_win_pct", "slm_win_pct", "tie_pct"]:
    summary_df[col] = summary_df[col].round(2)

Loading Lakshan2003/pairwise-virtuoso-large-vs-llama3.2-1b
Loading Lakshan2003/pairwise-virtuoso-large-vs-llama3.1-8b
Loading Lakshan2003/pairwise-virtuoso-large-vs-qwen3-1.7b
Loading Lakshan2003/pairwise-virtuoso-large-vs-qwen3-4b
Loading Lakshan2003/pairwise-virtuoso-large-vs-qwen3-8b
Loading Lakshan2003/pairwise-virtuoso-large-vs-phi-4-mini
Loading Lakshan2003/pairwise-virtuoso-large-vs-gemma-3-4b
Loading Lakshan2003/pairwise-virtuoso-large-vs-smollm3-3b
Loading Lakshan2003/pairwise-virtuoso-large-vs-llama-3.2-instruct
Loading Lakshan2003/pairwise-gemini-2.5-flash-vs-llama3.2-1b
Loading Lakshan2003/pairwise-gemini-2.5-flash-vs-llama3.1-8b
Loading Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-1.7b
Loading Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-4b
Loading Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-8b
Loading Lakshan2003/pairwise-gemini-2.5-flash-vs-phi-4-mini
Loading Lakshan2003/pairwise-gemini-2.5-flash-vs-gemma-3-4b
Loading Lakshan2003/pairwise-gemini-2.5-flash-vs-smollm3-3b
Loading Lakshan2003/pairwise-gemini-2.5-flash-vs-llama-3.2-instruct
Loading Lakshan2003/pairwise-gpt4.1-vs-llama3.2-1b
WARNING: Could not confidently classify LLM/SLM between gpt_4_1 and llama3_2_1b
Loading Lakshan2003/pairwise-gpt4.1-vs-llama3.1-8b
WARNING: Could not confidently classify LLM/SLM between gpt_4_1 and llama3_1_8b
Loading Lakshan2003/pairwise-gpt4.1-vs-qwen3-1.7b
WARNING: Could not confidently classify LLM/SLM between gpt_4_1 and qwen3_1_7b
Loading Lakshan2003/pairwise-gpt4.1-vs-qwen3-4b
WARNING: Could not confidently classify LLM/SLM between gpt_4_1 and qwen3_4b
Loading Lakshan2003/pairwise-gpt4.1-vs-qwen3-8b
WARNING: Could not confidently classify LLM/SLM between gpt_4_1 and qwen3_8b
Loading Lakshan2003/pairwise-gpt4.1-vs-phi-4-mini
WARNING: Could not confidently classify LLM/SLM between gpt_4_1 and phi_4_mini
Loading Lakshan2003/pairwise-gpt4.1-vs-gemma-3-4b
WARNING: Could not confidently classify LLM/SLM between gpt_4_1 and gemma3_4b
Loading Lakshan2003/pairwise-gpt4.1-vs-smollm3-3b
WARNING: Could not confidently classify LLM/SLM between gpt_4_1 and smollm3_3b
Loading Lakshan2003/pairwise-gpt4.1-vs-llama-3.2-instruct
WARNING: Could not confidently classify LLM/SLM between gpt_4_1 and llama3_2

In [ ]:
DISPLAY_NAME_MAP = {
    # LLMs (no parameter count)
    "virtuoso_large": "Virtuoso-Large",
    "gpt4_1": "GPT-4.1",
    "gemini_2_5_flash": "Gemini-2.5-Flash",
    "gemma3_4b": "Gemma-3-4B",

    # SLMs (explicit parameter counts)
    "qwen3_4b": "Qwen-3-4B-Instruct (4B)",
    "phi_4_mini": "Phi-4-Mini (4B)",
    "llama3_2": "LLaMA-3.2-3B",
    "llama3_2_instruct": "LLaMA-3.2-3B-Instruct",
    "smollm3_3b": "SmolLM-3B-Instruct",
}


def to_display(name):
    return DISPLAY_NAME_MAP.get(name, name)

summary_df["llm"] = summary_df["llm"].apply(to_display)
summary_df["slm"] = summary_df["slm"].apply(to_display)

In [ ]:
summary_df.loc[0, "slm_win_pct"]

np.float64(6.3)

In [ ]:
print("\nFinal LLM vs SLM results table (with percentages):")
summary_df

Final LLM vs SLM results table (with percentages):

,llm,slm,llm_wins,slm_wins,ties,llm_win_pct,slm_win_pct,tie_pct,tested_records,judge
0,Gemini-2.5-Flash,Gemma-3-4B,885,63,52,88.50,6.30,5.20,1000,claude-haiku-4-5
1,Gemini-2.5-Flash,llama3_1_8b,286,529,185,28.60,52.90,18.50,1000,claude-haiku-4-5
2,Gemini-2.5-Flash,LLaMA-3.2-3B,374,497,129,37.40,49.70,12.90,1000,claude-haiku-4-5
3,Gemini-2.5-Flash,llama3_2_1b,431,386,183,43.10,38.60,18.30,1000,claude-haiku-4-5
4,Gemini-2.5-Flash,Phi-4-Mini (4B),405,439,156,40.50,43.90,15.60,1000,claude-haiku-4-5
5,Gemini-2.5-Flash,qwen3_1_7b,498,335,167,49.80,33.50,16.70,1000,claude-haiku-4-5
6,Gemini-2.5-Flash,Qwen-3-4B-Instruct (4B),412,450,138,41.20,45.00,13.80,1000,claude-haiku-4-5
7,Gemini-2.5-Flash,qwen3_8b,266,558,176,26.60,55.80,17.60,1000,claude-haiku-4-5
8,Gemini-2.5-Flash,SmolLM-3B-Instruct,858,78,64,85.80,7.80,6.40,1000,claude-haiku-4-5
9,gpt_4_1,Gemma-3-4B,973,15,12,97.30,1.50,1.20,1000,claude-haiku-4-5
10,gpt_4_1,llama3_1_8b,613,190,197,61.30,19.00,19.70,1000,claude-haiku-4-5
11,gpt_4_1,LLaMA-3.2-3B,670,179,151,67.00,17.90,15.10,1000,claude-haiku-4-5
12,gpt_4_1,llama3_2_1b,686,157,157,68.60,15.70,15.70,1000,claude-haiku-4-5
13,gpt_4_1,Phi-4-Mini (4B),725,149,126,72.50,14.90,12.60,1000,claude-haiku-4-5
14,gpt_4_1,qwen3_1_7b,790,87,123,79.00,8.70,12.30,1000,claude-haiku-4-5
15,gpt_4_1,Qwen-3-4B-Instruct (4B),709,146,145,70.90,14.60,14.50,1000,claude-haiku-4-5
16,gpt_4_1,qwen3_8b,542,238,220,54.20,23.80,22.00,1000,claude-haiku-4-5
17,gpt_4_1,SmolLM-3B-Instruct,965,12,23,96.50,1.20,2.30,1000,claude-haiku-4-5
18,Virtuoso-Large,Gemma-3-4B,958,15,27,95.80,1.50,2.70,1000,claude-haiku-4-5
19,Virtuoso-Large,llama3_1_8b,547,280,173,54.70,28.00,17.30,1000,claude-haiku-4-5
20,Virtuoso-Large,LLaMA-3.2-3B,569,246,185,56.90,24.60,18.50,1000,claude-haiku-4-5
21,Virtuoso-Large,llama3_2_1b,616,198,186,61.60,19.80,18.60,1000,claude-haiku-4-5
22,Virtuoso-Large,Phi-4-Mini (4B),647,199,154,64.70,19.90,15.40,1000,claude-haiku-4-5
23,Virtuoso-Large,qwen3_1_7b,734,128,138,73.40,12.80,13.80,1000,claude-haiku-4-5
24,Virtuoso-Large,Qwen-3-4B-Instruct (4B),626,218,156,62.60,21.80,15.60,1000,claude-haiku-4-5
25,Virtuoso-Large,qwen3_8b,467,319,214,46.70,31.90,21.40,1000,claude-haiku-4-5
26,Virtuoso-Large,SmolLM-3B-Instruct,955,20,25,95.50,2.00,2.50,1000,claude-haiku-4-5

In [ ]:
summary_df.drop(columns=["llm_wins", "slm_wins", "ties"])

,llm,slm,llm_win_pct,slm_win_pct,tie_pct,tested_records,judge
0,Gemini-2.5-Flash,Gemma-3-4B,88.5,6.3,5.2,1000,claude-haiku-4-5
1,Gemini-2.5-Flash,llama3_1_8b,28.6,52.9,18.5,1000,claude-haiku-4-5
2,Gemini-2.5-Flash,LLaMA-3.2-3B,37.4,49.7,12.9,1000,claude-haiku-4-5
3,Gemini-2.5-Flash,llama3_2_1b,43.1,38.6,18.3,1000,claude-haiku-4-5
4,Gemini-2.5-Flash,Phi-4-Mini (4B),40.5,43.9,15.6,1000,claude-haiku-4-5
5,Gemini-2.5-Flash,qwen3_1_7b,49.8,33.5,16.7,1000,claude-haiku-4-5
6,Gemini-2.5-Flash,Qwen-3-4B-Instruct (4B),41.2,45.0,13.8,1000,claude-haiku-4-5
7,Gemini-2.5-Flash,qwen3_8b,26.6,55.8,17.6,1000,claude-haiku-4-5
8,Gemini-2.5-Flash,SmolLM-3B-Instruct,85.8,7.8,6.4,1000,claude-haiku-4-5
9,gpt_4_1,Gemma-3-4B,97.3,1.5,1.2,1000,claude-haiku-4-5
10,gpt_4_1,llama3_1_8b,61.3,19.0,19.7,1000,claude-haiku-4-5
11,gpt_4_1,LLaMA-3.2-3B,67.0,17.9,15.1,1000,claude-haiku-4-5
12,gpt_4_1,llama3_2_1b,68.6,15.7,15.7,1000,claude-haiku-4-5
13,gpt_4_1,Phi-4-Mini (4B),72.5,14.9,12.6,1000,claude-haiku-4-5
14,gpt_4_1,qwen3_1_7b,79.0,8.7,12.3,1000,claude-haiku-4-5
15,gpt_4_1,Qwen-3-4B-Instruct (4B),70.9,14.6,14.5,1000,claude-haiku-4-5
16,gpt_4_1,qwen3_8b,54.2,23.8,22.0,1000,claude-haiku-4-5
17,gpt_4_1,SmolLM-3B-Instruct,96.5,1.2,2.3,1000,claude-haiku-4-5
18,Virtuoso-Large,Gemma-3-4B,95.8,1.5,2.7,1000,claude-haiku-4-5
19,Virtuoso-Large,llama3_1_8b,54.7,28.0,17.3,1000,claude-haiku-4-5
20,Virtuoso-Large,LLaMA-3.2-3B,56.9,24.6,18.5,1000,claude-haiku-4-5
21,Virtuoso-Large,llama3_2_1b,61.6,19.8,18.6,1000,claude-haiku-4-5
22,Virtuoso-Large,Phi-4-Mini (4B),64.7,19.9,15.4,1000,claude-haiku-4-5
23,Virtuoso-Large,qwen3_1_7b,73.4,12.8,13.8,1000,claude-haiku-4-5
24,Virtuoso-Large,Qwen-3-4B-Instruct (4B),62.6,21.8,15.6,1000,claude-haiku-4-5
25,Virtuoso-Large,qwen3_8b,46.7,31.9,21.4,1000,claude-haiku-4-5
26,Virtuoso-Large,SmolLM-3B-Instruct,95.5,2.0,2.5,1000,claude-haiku-4-5

In [ ]:
summary_ds = Dataset.from_pandas(summary_df, preserve_index=False)

summary_ds.push_to_hub(
    SUMMARY_REPO,
    split="train",
    commit_message="Corrected LLM vs SLM pairwise results with percentages (Claude Sonnet judge)"
)

print(f"\nSummary pushed to {SUMMARY_REPO}")

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              : 100%|##########| 5.32kB / 5.32kB

README.md:   0%|          | 0.00/593 [00:00<?, ?B/s]

Summary pushed to Lakshan2003/pairwise-eval-results

### Stag-wise Pairwise Evaluation Results

In [ ]:
import pandas as pd
from datasets import load_dataset

# CONFIG (unchanged)
PAIRWISE_REPOS = [
    "Lakshan2003/pairwise-virtuoso-large-vs-llama3.2-1b",
    "Lakshan2003/pairwise-virtuoso-large-vs-llama3.1-8b",
    "Lakshan2003/pairwise-virtuoso-large-vs-qwen3-1.7b",
    "Lakshan2003/pairwise-virtuoso-large-vs-qwen3-4b",
    "Lakshan2003/pairwise-virtuoso-large-vs-qwen3-8b",
    "Lakshan2003/pairwise-virtuoso-large-vs-phi-4-mini",
    "Lakshan2003/pairwise-virtuoso-large-vs-gemma-3-4b",
    "Lakshan2003/pairwise-virtuoso-large-vs-smollm3-3b",
    "Lakshan2003/pairwise-virtuoso-large-vs-llama-3.2-instruct",

    "Lakshan2003/pairwise-gemini-2.5-flash-vs-llama3.2-1b",
    "Lakshan2003/pairwise-gemini-2.5-flash-vs-llama3.1-8b",
    "Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-1.7b",
    "Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-4b",
    "Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-8b",
    "Lakshan2003/pairwise-gemini-2.5-flash-vs-phi-4-mini",
    "Lakshan2003/pairwise-gemini-2.5-flash-vs-gemma-3-4b",
    "Lakshan2003/pairwise-gemini-2.5-flash-vs-smollm3-3b",
    "Lakshan2003/pairwise-gemini-2.5-flash-vs-llama-3.2-instruct",

    "Lakshan2003/pairwise-gpt4.1-vs-llama3.2-1b",
    "Lakshan2003/pairwise-gpt4.1-vs-llama3.1-8b",
    "Lakshan2003/pairwise-gpt4.1-vs-qwen3-1.7b",
    "Lakshan2003/pairwise-gpt4.1-vs-qwen3-4b",
    "Lakshan2003/pairwise-gpt4.1-vs-qwen3-8b",
    "Lakshan2003/pairwise-gpt4.1-vs-phi-4-mini",
    "Lakshan2003/pairwise-gpt4.1-vs-gemma-3-4b",
    "Lakshan2003/pairwise-gpt4.1-vs-smollm3-3b",
    "Lakshan2003/pairwise-gpt4.1-vs-llama-3.2-instruct",
]

JUDGE_NAME = "claude-haiku-4-5"
LLM_KEYS = ["virtuoso", "gpt4", "gemini"]


def get_models_from_columns(df):
    cols = [c for c in df.columns if c.startswith("generated_answer_")]
    if len(cols) != 2:
        raise ValueError(f"Expected 2 generated_answer_* columns, got {len(cols)}")
    return cols[0].replace("generated_answer_", ""), cols[1].replace("generated_answer_", "")


def classify_llm_slm(model_a, model_b):
    a_is_llm = any(k in model_a for k in LLM_KEYS)
    b_is_llm = any(k in model_b for k in LLM_KEYS)

    if a_is_llm and not b_is_llm:
        return model_a, model_b
    if b_is_llm and not a_is_llm:
        return model_b, model_a

    print(f"WARNING: Could not confidently classify {model_a} vs {model_b}")
    return model_a, model_b


rows = []

for repo in PAIRWISE_REPOS:
    print(f"Loading {repo}")
    df = load_dataset(repo, split="train").to_pandas()

    model_a, model_b = get_models_from_columns(df)
    llm, slm = classify_llm_slm(model_a, model_b)

    for stage, sdf in df.groupby("conversation_stage"):
        llm_wins = 0
        slm_wins = 0
        ties = 0
        valid = 0

        for r in sdf["final_result"]:
            if r == llm:
                llm_wins += 1
                valid += 1
            elif r == slm:
                slm_wins += 1
                valid += 1
            elif r == "Tie":
                ties += 1
                valid += 1

        if valid == 0:
            continue

        rows.append({
            "conversation_stage": stage,
            "llm": llm,
            "slm": slm,
            "llm_wins": llm_wins,
            "slm_wins": slm_wins,
            "ties": ties,
            "llm_win_pct": round(llm_wins / valid * 100, 2),
            "slm_win_pct": round(slm_wins / valid * 100, 2),
            "tie_pct": round(ties / valid * 100, 2),
            "tested_records": valid,
            "judge": JUDGE_NAME
        })


stagewise_summary_df = (
    pd.DataFrame(rows)
    .sort_values(["conversation_stage", "llm", "slm"])
    .reset_index(drop=True)
)

Loading Lakshan2003/pairwise-virtuoso-large-vs-llama3.2-1b
Loading Lakshan2003/pairwise-virtuoso-large-vs-llama3.1-8b
Loading Lakshan2003/pairwise-virtuoso-large-vs-qwen3-1.7b
Loading Lakshan2003/pairwise-virtuoso-large-vs-qwen3-4b
Loading Lakshan2003/pairwise-virtuoso-large-vs-qwen3-8b
Loading Lakshan2003/pairwise-virtuoso-large-vs-phi-4-mini
Loading Lakshan2003/pairwise-virtuoso-large-vs-gemma-3-4b
Loading Lakshan2003/pairwise-virtuoso-large-vs-smollm3-3b
Loading Lakshan2003/pairwise-virtuoso-large-vs-llama-3.2-instruct
Loading Lakshan2003/pairwise-gemini-2.5-flash-vs-llama3.2-1b
Loading Lakshan2003/pairwise-gemini-2.5-flash-vs-llama3.1-8b
Loading Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-1.7b
Loading Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-4b
Loading Lakshan2003/pairwise-gemini-2.5-flash-vs-qwen3-8b
Loading Lakshan2003/pairwise-gemini-2.5-flash-vs-phi-4-mini
Loading Lakshan2003/pairwise-gemini-2.5-flash-vs-gemma-3-4b
Loading Lakshan2003/pairwise-gemini-2.5-flash-vs-smollm3-3b
Loading Lakshan2003/pairwise-gemini-2.5-flash-vs-llama-3.2-instruct
Loading Lakshan2003/pairwise-gpt4.1-vs-llama3.2-1b
WARNING: Could not confidently classify gpt_4_1 vs llama3_2_1b
Loading Lakshan2003/pairwise-gpt4.1-vs-llama3.1-8b
WARNING: Could not confidently classify gpt_4_1 vs llama3_1_8b
Loading Lakshan2003/pairwise-gpt4.1-vs-qwen3-1.7b
WARNING: Could not confidently classify gpt_4_1 vs qwen3_1_7b
Loading Lakshan2003/pairwise-gpt4.1-vs-qwen3-4b
WARNING: Could not confidently classify gpt_4_1 vs qwen3_4b
Loading Lakshan2003/pairwise-gpt4.1-vs-qwen3-8b
WARNING: Could not confidently classify gpt_4_1 vs qwen3_8b
Loading Lakshan2003/pairwise-gpt4.1-vs-phi-4-mini
WARNING: Could not confidently classify gpt_4_1 vs phi_4_mini
Loading Lakshan2003/pairwise-gpt4.1-vs-gemma-3-4b
WARNING: Could not confidently classify gpt_4_1 vs gemma3_4b
Loading Lakshan2003/pairwise-gpt4.1-vs-smollm3-3b
WARNING: Could not confidently classify gpt_4_1 vs smollm3_3b
Loading Lakshan2003/pairwise-gpt4.1-vs-llama-3.2-instruct
WARNING: Could not confidently classify gpt_4_1 vs llama3_2

In [ ]:
pivot_mid = (
    stagewise_summary_df
    .query("conversation_stage == 'MIDDLE'")
    .pivot(index="slm", columns="llm", values="slm_win_pct")
)

In [ ]:
pd.set_option('display.max_rows', None)        # Show all rows
pd.set_option('display.max_columns', None)     # Show all columns
pd.set_option('display.width', None)           # Don't wrap to next line
pd.set_option('display.max_colwidth', None)    # Show full column content

In [ ]:
stagewise_summary_df.drop(columns=["tested_records", "llm_wins", "slm_wins", "ties"], inplace=True)

In [ ]:
stagewise_summary_df.head(100)

,conversation_stage,llm,slm,llm_win_pct,slm_win_pct,tie_pct,judge
0,BEGINNING,gemini_2_5_flash,gemma3_4b,93.94,4.04,2.02,claude-haiku-4-5
1,BEGINNING,gemini_2_5_flash,llama3_1_8b,31.31,40.40,28.28,claude-haiku-4-5
2,BEGINNING,gemini_2_5_flash,llama3_2,42.42,44.44,13.13,claude-haiku-4-5
3,BEGINNING,gemini_2_5_flash,llama3_2_1b,49.49,35.35,15.15,claude-haiku-4-5
4,BEGINNING,gemini_2_5_flash,phi_4_mini,45.45,37.37,17.17,claude-haiku-4-5
5,BEGINNING,gemini_2_5_flash,qwen3_1_7b,56.57,28.28,15.15,claude-haiku-4-5
6,BEGINNING,gemini_2_5_flash,qwen3_4b,49.49,36.36,14.14,claude-haiku-4-5
7,BEGINNING,gemini_2_5_flash,qwen3_8b,44.44,38.38,17.17,claude-haiku-4-5
8,BEGINNING,gemini_2_5_flash,smollm3_3b,92.93,5.05,2.02,claude-haiku-4-5
9,BEGINNING,gpt_4_1,gemma3_4b,97.98,1.01,1.01,claude-haiku-4-5
10,BEGINNING,gpt_4_1,llama3_1_8b,54.55,22.22,23.23,claude-haiku-4-5
11,BEGINNING,gpt_4_1,llama3_2,72.73,18.18,9.09,claude-haiku-4-5
12,BEGINNING,gpt_4_1,llama3_2_1b,65.66,17.17,17.17,claude-haiku-4-5
13,BEGINNING,gpt_4_1,phi_4_mini,71.72,13.13,15.15,claude-haiku-4-5
14,BEGINNING,gpt_4_1,qwen3_1_7b,75.76,11.11,13.13,claude-haiku-4-5
15,BEGINNING,gpt_4_1,qwen3_4b,66.67,14.14,19.19,claude-haiku-4-5
16,BEGINNING,gpt_4_1,qwen3_8b,54.55,19.19,26.26,claude-haiku-4-5
17,BEGINNING,gpt_4_1,smollm3_3b,98.99,1.01,0.00,claude-haiku-4-5
18,BEGINNING,virtuoso_large,gemma3_4b,96.97,1.01,2.02,claude-haiku-4-5
19,BEGINNING,virtuoso_large,llama3_1_8b,47.47,34.34,18.18,claude-haiku-4-5
20,BEGINNING,virtuoso_large,llama3_2,58.59,27.27,14.14,claude-haiku-4-5
21,BEGINNING,virtuoso_large,llama3_2_1b,57.58,25.25,17.17,claude-haiku-4-5
22,BEGINNING,virtuoso_large,phi_4_mini,57.58,26.26,16.16,claude-haiku-4-5
23,BEGINNING,virtuoso_large,qwen3_1_7b,65.66,14.14,20.20,claude-haiku-4-5
24,BEGINNING,virtuoso_large,qwen3_4b,56.57,27.27,16.16,claude-haiku-4-5
25,BEGINNING,virtuoso_large,qwen3_8b,49.49,31.31,19.19,claude-haiku-4-5
26,BEGINNING,virtuoso_large,smollm3_3b,95.96,2.02,2.02,claude-haiku-4-5
27,END,gemini_2_5_flash,gemma3_4b,85.57,6.19,8.25,claude-haiku-4-5
28,END,gemini_2_5_flash,llama3_1_8b,39.18,40.21,20.62,claude-haiku-4-5
29,END,gemini_2_5_flash,llama3_2,37.11,47.42,15.46,claude-haiku-4-5
30,END,gemini_2_5_flash,llama3_2_1b,29.90,41.24,28.87,claude-haiku-4-5
31,END,gemini_2_5_flash,phi_4_mini,34.02,52.58,13.40,claude-haiku-4-5
32,END,gemini_2_5_flash,qwen3_1_7b,45.36,34.02,20.62,claude-haiku-4-5
33,END,gemini_2_5_flash,qwen3_4b,37.11,45.36,17.53,claude-haiku-4-5
34,END,gemini_2_5_flash,qwen3_8b,37.11,35.05,27.84,claude-haiku-4-5
35,END,gemini_2_5_flash,smollm3_3b,95.88,1.03,3.09,claude-haiku-4-5
36,END,gpt_4_1,gemma3_4b,94.85,2.06,3.09,claude-haiku-4-5
37,END,gpt_4_1,llama3_1_8b,45.36,22.68,31.96,claude-haiku-4-5
38,END,gpt_4_1,llama3_2,53.61,28.87,17.53,claude-haiku-4-5
39,END,gpt_4_1,llama3_2_1b,43.30,37.11,19.59,claude-haiku-4-5
40,END,gpt_4_1,phi_4_mini,54.64,26.80,18.56,claude-haiku-4-5
41,END,gpt_4_1,qwen3_1_7b,54.64,21.65,23.71,claude-haiku-4-5
42,END,gpt_4_1,qwen3_4b,58.76,24.74,16.49,claude-haiku-4-5
43,END,gpt_4_1,qwen3_8b,52.58,24.74,22.68,claude-haiku-4-5
44,END,gpt_4_1,smollm3_3b,95.88,1.03,3.09,claude-haiku-4-5
45,END,virtuoso_large,gemma3_4b,92.78,0.00,7.22,claude-haiku-4-5
46,END,virtuoso_large,llama3_1_8b,41.24,37.11,21.65,claude-haiku-4-5
47,END,virtuoso_large,llama3_2,47.42,29.90,22.68,claude-haiku-4-5
48,END,virtuoso_large,llama3_2_1b,42.27,35.05,22.68,claude-haiku-4-5
49,END,virtuoso_large,phi_4_mini,46.39,21.65,31.96,claude-haiku-4-5
50,END,virtuoso_large,qwen3_1_7b,56.70,11.34,31.96,claude-haiku-4-5
51,END,virtuoso_large,qwen3_4b,47.42,26.80,25.77,claude-haiku-4-5
52,END,virtuoso_large,qwen3_8b,55.67,20.62,23.71,claude-haiku-4-5
53,END,virtuoso_large,smollm3_3b,96.91,1.03,2.06,claude-haiku-4-5
54,MIDDLE,gemini_2_5_flash,gemma3_4b,88.18,6.59,5.22,claude-haiku-4-5
55,MIDDLE,gemini_2_5_flash,llama3_1_8b,26.99,55.97,17.04,claude-haiku-4-5
56,MIDDLE,gemini_2_5_flash,llama3_2,36.82,50.62,12.56,claude-haiku-4-5
57,MIDDLE,gemini_2_5_flash,llama3_2_1b,43.91,38.68,17.41,claude-haiku-4-5
58,MIDDLE,gemini_2_5_flash,phi_4_mini,40.67,43.66,15.67,claude-haiku-4-5
59,MIDDLE,gemini_2_5_flash,qwen3_1_7b,49.50,34.08,16.42,claude-haiku-4-5
60,MIDDLE,gemini_2_5_flash,qwen3_4b,40.67,46.02,13.31,claude-haiku-4-5
61,MIDDLE,gemini_2_5_flash,qwen3_8b,23.13,60.45,16.42,claude-haiku-4-5
62,MIDDLE,gemini_2_5_flash,smollm3_3b,83.71,8.96,7.34,claude-haiku-4-5
63,MIDDLE,gpt_4_1,gemma3_4b,97.51,1.49,1.00,claude-haiku-4-5
64,MIDDLE,gpt_4_1,llama3_1_8b,64.05,18.16,17.79,claude-haiku-4-5
65,MIDDLE,gpt_4_1,llama3_2,67.91,16.54,15.55,claude-haiku-4-5
66,MIDDLE,gpt_4_1,llama3_2_1b,72.01,12.94,15.05,claude-haiku-4-5
67,MIDDLE,gpt_4_1,phi_4_mini,74.75,13.68,11.57,claude-haiku-4-5
68,MIDDLE,gpt_4_1,qwen3_1_7b,82.34,6.84,10.82,claude-haiku-4-5
69,MIDDLE,gpt_4_1,qwen3_4b,72.89,13.43,13.68,claude-haiku-4-5
70,MIDDLE,gpt_4_1,qwen3_8b,54.35,24.25,21.39,claude-haiku-4-5
71,MIDDLE,gpt_4_1,smollm3_3b,96.27,1.24,2.49,claude-haiku-4-5
72,MIDDLE,virtuoso_large,gemma3_4b,96.02,1.74,2.24,claude-haiku-4-5
73,MIDDLE,virtuoso_large,llama3_1_8b,57.21,26.12,16.67,claude-haiku-4-5
74,MIDDLE,virtuoso_large,llama3_2,57.84,23.63,18.53,claude-haiku-4-5
75,MIDDLE,virtuoso_large,llama3_2_1b,64.43,17.29,18.28,claude-haiku-4-5
76,MIDDLE,virtuoso_large,phi_4_mini,67.79,18.91,13.31,claude-haiku-4-5
77,MIDDLE,virtuoso_large,qwen3_1_7b,76.37,12.81,10.82,claude-haiku-4-5
78,MIDDLE,virtuoso_large,qwen3_4b,65.17,20.52,14.30,claude-haiku-4-5
79,MIDDLE,virtuoso_large,qwen3_8b,45.27,33.33,21.39,claude-haiku-4-5
80,MIDDLE,virtuoso_large,smollm3_3b,95.27,2.11,2.61,claude-haiku-4-5